[CICADA]
VERSION=0.1.17
DATA_DIR=/var/lib/cicada/data
CONFIG_DIR=/etc/cicada
LOG_DIR=/var/log/cicada
INSTALL_PORT=4567
INSTALL_STATUS=not_installed

# URL de l'API de suivi (fixée lors de la création du package .deb, non modifiable après installation)
TRACKING_API_URL=https://tracking.cicada.reserves-naturelles.org/api
