# Generated by Django 5.0.8 on 2026-08-17 11:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_create_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=25, unique=True, verbose_name='Code du type')),
                ('type_name', models.CharField(max_length=200, verbose_name='Nom du type')),
                ('type_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de zone géographique',
                'verbose_name_plural': 'Types de zones géographiques',
                'db_table': '"ref_geo"."bib_areas_types"',
            },
        ),
        migrations.CreateModel(
            name='LArea',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area_code', models.CharField(max_length=25, verbose_name='Code')),
                ('area_name', models.CharField(max_length=250, verbose_name='Nom')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Centroïde')),
                ('enable', models.BooleanField(default=True, verbose_name='Actif')),
                ('id_type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='geo.areatype', verbose_name='Type de zone')),
                ('parent', models.ForeignKey(blank=True, db_column='id_area_parent', help_text='Région de rattachement, pour un département.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.larea', verbose_name='Zone parente')),
            ],
            options={
                'verbose_name': 'Zone géographique',
                'verbose_name_plural': 'Zones géographiques',
                'db_table': '"ref_geo"."l_areas"',
                'indexes': [models.Index(fields=['area_code'], name='idx_l_areas_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='larea',
            constraint=models.UniqueConstraint(fields=('id_type', 'area_code'), name='uq_l_areas_type_code'),
        ),
    ]
