# Generated by Django 5.0.8 on 2026-01-08 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        ("users", "0004_role_deactivated_at_role_deactivated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("user_registration", "Inscription utilisateur"),
                            ("site_access", "Acces a un site"),
                            ("plan_access", "Acces a un plan de gestion"),
                            ("admin_deactivation", "Desactivation admin_og"),
                            ("referent_validation", "Validation referent site"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Type de demande",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuve"),
                            ("rejected", "Rejete"),
                            ("cancelled", "Annule"),
                            ("expired", "Expire"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "requested_role_level",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Niveau de role demande",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Motif de la demande",
                        null=True,
                        verbose_name="Justification",
                    ),
                ),
                (
                    "validation_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaire de validation"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valide le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis a jour le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expiration automatique de la demande",
                        null=True,
                        verbose_name="Expire le",
                    ),
                ),
                (
                    "requested_organisme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.biborganismes",
                        verbose_name="Organisme demande",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_requests_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "target_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plangestion",
                        verbose_name="Plan cible",
                    ),
                ),
                (
                    "target_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.site",
                        verbose_name="Site cible",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deactivation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur cible",
                    ),
                ),
                (
                    "validator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations_handled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de validation",
                "verbose_name_plural": "Demandes de validation",
                "db_table": "t_validation_requests",
                "db_table_comment": "Table des demandes de validation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Mot de passe hashe avec make_password",
                        max_length=255,
                        verbose_name="Mot de passe (hash)",
                    ),
                ),
                (
                    "nom_role",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "prenom_role",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Prenom"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Motif de l'inscription",
                        null=True,
                        verbose_name="Justification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "requested_organisme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.biborganismes",
                        verbose_name="Organisme demande",
                    ),
                ),
                (
                    "validation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_user",
                        to="notifications.validationrequest",
                        verbose_name="Demande de validation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur en attente",
                "verbose_name_plural": "Utilisateurs en attente",
                "db_table": "t_pending_users",
                "db_table_comment": "Table des utilisateurs en attente de validation",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("validation_request", "Demande de validation"),
                            ("validation_approved", "Validation approuvee"),
                            ("validation_rejected", "Validation rejetee"),
                            ("user_associated_site", "Utilisateur associe a un site"),
                            ("user_associated_plan", "Utilisateur associe a un plan"),
                            ("user_removed_site", "Utilisateur retire d'un site"),
                            ("user_removed_plan", "Utilisateur retire d'un plan"),
                            ("account_deactivated", "Compte desactive"),
                            ("account_activated", "Compte active"),
                            ("site_orphaned", "Site sans utilisateurs"),
                            ("organisme_no_admin", "Organisme sans administrateur"),
                            ("system_alert", "Alerte systeme"),
                            ("info", "Information"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priorite",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL vers laquelle rediriger l'utilisateur",
                        max_length=500,
                        null=True,
                        verbose_name="URL d'action",
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email envoye"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email envoye le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expiration automatique",
                        null=True,
                        verbose_name="Expire le",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "related_organisme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.biborganismes",
                        verbose_name="Organisme lie",
                    ),
                ),
                (
                    "related_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.plangestion",
                        verbose_name="Plan lie",
                    ),
                ),
                (
                    "related_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.site",
                        verbose_name="Site lie",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur lie",
                    ),
                ),
                (
                    "related_validation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.validationrequest",
                        verbose_name="Demande liee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "t_notifications",
                "db_table_comment": "Table des notifications utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["status", "request_type", "-created_at"],
                name="t_validatio_status_d439ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["requester", "status"], name="t_validatio_request_2e837a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="t_validatio_status_d229f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read", "-created_at"],
                name="t_notificat_recipie_0da14b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "-created_at"],
                name="t_notificat_notific_0974f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="t_notificat_recipie_bdc2c7_idx",
            ),
        ),
    ]
