# Generated by Django 5.0.8 on 2026-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Bienvenue"),
                            ("validation_request", "Demande de validation"),
                            ("validation_approved", "Validation approuvée"),
                            ("validation_rejected", "Validation rejetée"),
                            ("user_associated_site", "Utilisateur associé à un site"),
                            ("user_associated_plan", "Utilisateur associé à un plan"),
                            ("user_removed_site", "Utilisateur retiré d'un site"),
                            ("user_removed_plan", "Utilisateur retiré d'un plan"),
                            ("account_deactivated", "Compte désactivé"),
                            ("account_activated", "Compte activé"),
                            ("site_orphaned", "Site sans utilisateurs"),
                            ("organisme_no_admin", "Organisme sans administrateur"),
                            ("system_alert", "Alerte système"),
                            ("info", "Information"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL vers laquelle rediriger l'utilisateur",
                        max_length=500,
                        null=True,
                        verbose_name="URL d'action",
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email envoyé"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email envoyé le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expiration automatique",
                        null=True,
                        verbose_name="Expire le",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": '"ccd_notifications"."t_notifications"',
                "db_table_comment": "Table des notifications utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Mot de passe hashé avec make_password",
                        max_length=255,
                        verbose_name="Mot de passe (hash)",
                    ),
                ),
                (
                    "nom_role",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "prenom_role",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Prénom"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Motif de l'inscription",
                        null=True,
                        verbose_name="Justification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User Agent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur en attente",
                "verbose_name_plural": "Utilisateurs en attente",
                "db_table": '"ccd_notifications"."t_pending_users"',
                "db_table_comment": "Table des utilisateurs en attente de validation",
            },
        ),
        migrations.CreateModel(
            name="ValidationRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("user_registration", "Inscription utilisateur"),
                            ("site_access", "Accès à un site"),
                            ("plan_access", "Accès à un plan de gestion"),
                            ("module_access", "Accès à un module"),
                            ("admin_deactivation", "Désactivation admin_og"),
                            ("referent_validation", "Validation référent site"),
                            ("site_org_link", "Lien site-organisme"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Type de demande",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "target_module",
                    models.CharField(
                        blank=True,
                        help_text="Code du module demandé (ex: zonages)",
                        max_length=50,
                        null=True,
                        verbose_name="Module cible",
                    ),
                ),
                (
                    "requested_role_level",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Niveau de rôle demandé",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Motif de la demande",
                        null=True,
                        verbose_name="Justification",
                    ),
                ),
                (
                    "request_as_referent",
                    models.BooleanField(
                        default=False,
                        help_text="Si vrai, l'utilisateur demande à être référent du site",
                        verbose_name="Demande comme référent",
                    ),
                ),
                (
                    "validation_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaire de validation"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Validé le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expiration automatique de la demande",
                        null=True,
                        verbose_name="Expire le",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de validation",
                "verbose_name_plural": "Demandes de validation",
                "db_table": '"ccd_notifications"."t_validation_requests"',
                "db_table_comment": "Table des demandes de validation",
                "ordering": ["-created_at"],
            },
        ),
    ]
