# Generated by Django 5.0.8 on 2026-01-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("plans", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinataire",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                verbose_name="Organisme lié",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plans.plangestion",
                verbose_name="Plan lié",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.site",
                verbose_name="Site lié",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur lié",
            ),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="requested_organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                verbose_name="Organisme demandé",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="requested_organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                verbose_name="Organisme demandé",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_requests_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="target_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plans.plangestion",
                verbose_name="Plan cible",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="target_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.site",
                verbose_name="Site cible",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deactivation_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur cible",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validations_handled",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validateur",
            ),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="validation_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_user",
                to="notifications.validationrequest",
                verbose_name="Demande de validation",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_validation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.validationrequest",
                verbose_name="Demande liée",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["status", "request_type", "-created_at"],
                name="t_validatio_status_d439ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["requester", "status"], name="t_validatio_request_2e837a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="t_validatio_status_d229f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read", "-created_at"],
                name="t_notificat_recipie_0da14b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "-created_at"],
                name="t_notificat_notific_0974f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="t_notificat_recipie_bdc2c7_idx",
            ),
        ),
    ]
