# Generated by Django 5.0.8 on 2026-01-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrequest",
            name="requester_name_cache",
            field=models.CharField(
                blank=True,
                help_text="Nom du demandeur stocke pour historique apres traitement",
                max_length=150,
                null=True,
                verbose_name="Nom du demandeur (cache)",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Bienvenue"),
                    ("validation_request", "Demande de validation"),
                    ("validation_approved", "Validation approuvee"),
                    ("validation_rejected", "Validation rejetee"),
                    ("user_associated_site", "Utilisateur associe a un site"),
                    ("user_associated_plan", "Utilisateur associe a un plan"),
                    ("user_removed_site", "Utilisateur retire d'un site"),
                    ("user_removed_plan", "Utilisateur retire d'un plan"),
                    ("account_deactivated", "Compte desactive"),
                    ("account_activated", "Compte active"),
                    ("site_orphaned", "Site sans utilisateurs"),
                    ("organisme_no_admin", "Organisme sans administrateur"),
                    ("system_alert", "Alerte systeme"),
                    ("info", "Information"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
