# Generated by Django 5.0.8 on 2026-01-12 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_add_requester_name_cache"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationrequest",
            name="requester_name_cache",
        ),
    ]
