# Generated by Django 5.0.8 on 2026-01-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_validationrequest_request_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("user_registration", "Inscription utilisateur"),
                    ("site_creation", "Création de site"),
                    ("site_access", "Accès à un site"),
                    ("plan_access", "Accès à un plan de gestion"),
                    ("module_access", "Accès à un module"),
                    ("admin_deactivation", "Désactivation admin_og"),
                    ("admin_promotion", "Promotion admin_og"),
                    ("admin_demotion", "Rétrogradation admin_og"),
                    ("referent_validation", "Validation référent site"),
                    ("site_org_link", "Lien site-organisme"),
                    ("invite_org_to_site", "Invitation organisme vers site"),
                    ("invite_user_to_site", "Invitation utilisateur vers site"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type de demande",
            ),
        ),
    ]
