# Generated by Django 5.0.8 on 2026-01-14 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_add_module_access"),
        ("plans", "0001_initial"),
        ("users", "0006_add_request_as_referent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrequest",
            name="request_as_referent",
            field=models.BooleanField(
                default=False,
                help_text="Si vrai, l'utilisateur demande à être référent du site",
                verbose_name="Demande comme référent",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="Email envoyé"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Email envoyé le"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Bienvenue"),
                    ("validation_request", "Demande de validation"),
                    ("validation_approved", "Validation approuvée"),
                    ("validation_rejected", "Validation rejetée"),
                    ("user_associated_site", "Utilisateur associé à un site"),
                    ("user_associated_plan", "Utilisateur associé à un plan"),
                    ("user_removed_site", "Utilisateur retiré d'un site"),
                    ("user_removed_plan", "Utilisateur retiré d'un plan"),
                    ("account_deactivated", "Compte désactivé"),
                    ("account_activated", "Compte activé"),
                    ("site_orphaned", "Site sans utilisateurs"),
                    ("organisme_no_admin", "Organisme sans administrateur"),
                    ("system_alert", "Alerte système"),
                    ("info", "Information"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Basse"),
                    ("medium", "Moyenne"),
                    ("high", "Haute"),
                    ("critical", "Critique"),
                ],
                default="medium",
                max_length=10,
                verbose_name="Priorité",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                verbose_name="Organisme lié",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plans.plangestion",
                verbose_name="Plan lié",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.site",
                verbose_name="Site lié",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur lié",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_validation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.validationrequest",
                verbose_name="Demande liée",
            ),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="password_hash",
            field=models.CharField(
                help_text="Mot de passe hashé avec make_password",
                max_length=255,
                verbose_name="Mot de passe (hash)",
            ),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="prenom_role",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="requested_organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                verbose_name="Organisme demandé",
            ),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="requested_organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                verbose_name="Organisme demandé",
            ),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="requested_role_level",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Niveau de rôle demandé",
            ),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                    ("cancelled", "Annulé"),
                    ("expired", "Expiré"),
                ],
                db_index=True,
                default="pending",
                max_length=15,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validé le"),
        ),
    ]
