# Generated by Django 5.0.8 on 2026-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_add_site_org_unlink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Bienvenue"),
                    ("validation_request", "Demande de validation"),
                    ("validation_approved", "Validation approuvée"),
                    ("validation_rejected", "Validation rejetée"),
                    ("user_associated_site", "Utilisateur associé à un site"),
                    ("user_associated_plan", "Utilisateur associé à un plan"),
                    ("user_removed_site", "Utilisateur retiré d'un site"),
                    ("user_removed_plan", "Utilisateur retiré d'un plan"),
                    ("account_deactivated", "Compte désactivé"),
                    ("account_activated", "Compte activé"),
                    ("organisme_changed", "Organisme modifié"),
                    ("site_orphaned", "Site sans utilisateurs"),
                    ("organisme_no_admin", "Organisme sans administrateur"),
                    ("plan_needs_reassignment", "Plan à réassigner"),
                    ("system_alert", "Alerte système"),
                    ("info", "Information"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("user_registration", "Inscription utilisateur"),
                    ("site_creation", "Création de site"),
                    ("site_access", "Accès à un site"),
                    ("plan_access", "Accès à un plan de gestion"),
                    ("module_access", "Accès à un module"),
                    ("admin_deactivation", "Désactivation admin_og"),
                    ("admin_promotion", "Promotion admin_og"),
                    ("admin_demotion", "Rétrogradation admin_og"),
                    ("referent_validation", "Validation référent site"),
                    ("site_org_link", "Lien site-organisme"),
                    ("site_org_unlink", "Retrait site-organisme"),
                    ("invite_org_to_site", "Invitation organisme vers site"),
                    ("invite_user_to_site", "Invitation utilisateur vers site"),
                    ("plan_site_link", "Lien plan-site"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type de demande",
            ),
        ),
    ]
