# Generated by Django 5.0.8 on 2026-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_add_plan_site_link_request_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="identifiant",
            field=models.CharField(
                blank=True,
                help_text="Identifiant de connexion alternatif (en plus de l'email)",
                max_length=100,
                null=True,
                verbose_name="Identifiant",
            ),
        ),
    ]
