# Generated by Django 5.0.8 on 2026-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Bienvenue"),
                    ("validation_request", "Demande de validation"),
                    ("validation_approved", "Validation approuvée"),
                    ("validation_rejected", "Validation rejetée"),
                    ("user_associated_site", "Utilisateur associé à un site"),
                    ("user_associated_plan", "Utilisateur associé à un plan"),
                    ("user_removed_site", "Utilisateur retiré d'un site"),
                    ("user_removed_plan", "Utilisateur retiré d'un plan"),
                    ("account_deactivated", "Compte désactivé"),
                    ("account_activated", "Compte activé"),
                    ("organisme_changed", "Organisme modifié"),
                    ("site_orphaned", "Site sans utilisateurs"),
                    ("site_deleted", "Site supprimé"),
                    ("plan_deleted", "Plan de gestion supprimé"),
                    ("plans_orphaned_summary", "Récapitulatif des plans orphelins"),
                    ("organisme_no_admin", "Organisme sans administrateur"),
                    ("plan_needs_reassignment", "Plan à réassigner"),
                    ("plan_csrpn_transition", "Transition workflow CSRPN"),
                    ("system_alert", "Alerte système"),
                    ("info", "Information"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
