# Generated by Django 5.0.8 on 2026-06-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_add_plan_csrpn_transition_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationrequest",
            name="related_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_requests",
                to="notifications.validationrequest",
                verbose_name="Demande liée",
            ),
        ),
        migrations.AddField(
            model_name="validationrequest",
            name="requested_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Données soumises pour une demande de création (ex: organisme à créer)",
                verbose_name="Données proposées",
            ),
        ),
        migrations.AlterField(
            model_name="validationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("user_registration", "Inscription utilisateur"),
                    ("site_creation", "Création de site"),
                    ("site_access", "Accès à un site"),
                    ("plan_access", "Accès à un plan de gestion"),
                    ("module_access", "Accès à un module"),
                    ("admin_deactivation", "Désactivation admin_og"),
                    ("admin_promotion", "Promotion admin_og"),
                    ("admin_demotion", "Rétrogradation admin_og"),
                    ("referent_validation", "Validation référent site"),
                    ("site_org_link", "Lien site-organisme"),
                    ("site_org_unlink", "Retrait site-organisme"),
                    ("invite_org_to_site", "Invitation organisme vers site"),
                    ("invite_user_to_site", "Invitation utilisateur vers site"),
                    ("plan_site_link", "Lien plan-site"),
                    ("organisme_creation", "Création d'organisme"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Type de demande",
            ),
        ),
    ]
