# Generated by Django 5.0.8 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habitats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habrefcorresptaxon",
            name="cd_nom",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Code nom taxon"
            ),
        ),
        migrations.AlterField(
            model_name="typoref",
            name="auteur_jeu_donnees",
            field=models.TextField(blank=True, null=True, verbose_name="Auteur"),
        ),
        migrations.AlterField(
            model_name="typoref",
            name="date_creation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="typoref",
            name="date_mise_jour",
            field=models.TextField(
                blank=True, null=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="typoref",
            name="lb_typo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Libellé typologie"
            ),
        ),
        migrations.AlterField(
            model_name="typoref",
            name="nom_jeu_donnees",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nom du jeu de données"
            ),
        ),
        migrations.AlterField(
            model_name="typoref",
            name="territoire",
            field=models.TextField(blank=True, null=True, verbose_name="Territoire"),
        ),
    ]
