# Generated by Django 5.0.8 on 2025-11-21 10:24

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibOrganismes",
            fields=[
                ("id_organisme", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid_organisme",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "nom_organisme",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "adresse_organisme",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "cp_organisme",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Code postal"
                    ),
                ),
                (
                    "ville_organisme",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "tel_organisme",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "fax_organisme",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Fax"
                    ),
                ),
                (
                    "email_organisme",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "url_organisme",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                (
                    "url_logo",
                    models.URLField(blank=True, null=True, verbose_name="Logo"),
                ),
                (
                    "additional_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("meta_create_date", models.DateTimeField(auto_now_add=True)),
                ("meta_update_date", models.DateTimeField(auto_now=True)),
                (
                    "id_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.biborganismes",
                        verbose_name="Organisme parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisme",
                "verbose_name_plural": "Organismes",
                "db_table": "bib_organismes",
                "db_table_comment": "Table des organismes gestionnaires",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groupe",
                    models.BooleanField(default=False, verbose_name="Est un groupe"),
                ),
                ("id_role", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid_role",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nom_role",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "prenom_role",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Prénom"
                    ),
                ),
                (
                    "desc_role",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("pass_plus", models.TextField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Adresse email",
                    ),
                ),
                ("remarques", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "role_level",
                    models.CharField(
                        choices=[
                            ("utilisateur", "Utilisateur"),
                            ("referent", "Référent"),
                            ("admin_og", "Administrateur Organisme"),
                            ("super_admin", "Super Administrateur"),
                        ],
                        default="utilisateur",
                        max_length=20,
                        verbose_name="Niveau de rôle",
                    ),
                ),
                (
                    "champs_addi",
                    models.TextField(
                        blank=True, null=True, verbose_name="Champs additionnels"
                    ),
                ),
                ("date_insert", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "id_organisme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.biborganismes",
                        verbose_name="Organisme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "t_roles",
                "db_table_comment": "Table des utilisateurs et groupes",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id_site", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_local",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Identifiant local",
                    ),
                ),
                (
                    "id_inpn",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Identifiant INPN",
                    ),
                ),
                (
                    "date_crea",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "nom_site",
                    models.CharField(max_length=255, verbose_name="Nom du site"),
                ),
                (
                    "jonction_nom",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Jonction nom",
                    ),
                ),
                (
                    "surf_off",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Surface officielle (ha)"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Géométrie"
                    ),
                ),
                (
                    "geom_pt",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Point de référence",
                    ),
                ),
                (
                    "modif_adm",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Modification administrative",
                    ),
                ),
                (
                    "modif_geo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Modification géographique"
                    ),
                ),
                (
                    "marin",
                    models.BooleanField(default=False, verbose_name="Milieu marin"),
                ),
                (
                    "outre_mer",
                    models.BooleanField(default=False, verbose_name="Outre-mer"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "id_type_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.nomenclature",
                        verbose_name="Type de site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "db_table": "t_site",
                "db_table_comment": "Table des sites",
            },
        ),
        migrations.CreateModel(
            name="CorRoleSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referent",
                    models.BooleanField(default=False, verbose_name="Référent"),
                ),
                (
                    "referent_valid",
                    models.BooleanField(default=False, verbose_name="Référent validé"),
                ),
                (
                    "conservateur",
                    models.BooleanField(default=False, verbose_name="Conservateur"),
                ),
                (
                    "id_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur - Site",
                "verbose_name_plural": "Utilisateurs - Sites",
                "db_table": "cor_role_site",
                "db_table_comment": "Liaison utilisateurs - sites",
                "unique_together": {("id_site", "id_role")},
            },
        ),
        migrations.CreateModel(
            name="CorOgSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="Gestionnaire principal"
                    ),
                ),
                (
                    "uuid_og",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.biborganismes",
                        to_field="uuid_organisme",
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site - Organisme",
                "verbose_name_plural": "Sites - Organismes",
                "db_table": "cor_site_og",
                "db_table_comment": "Liaison sites - organismes gestionnaires",
                "unique_together": {("id_site", "uuid_og")},
            },
        ),
    ]
