# Generated by Django 5.0 on 2026-01-16
# Migration to add unique constraint on id_inpn field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id_inpn',
            field=models.CharField(
                verbose_name='Identifiant INPN',
                max_length=50,
                null=True,
                blank=True,
                unique=True,
            ),
        ),
    ]
