# Generated by Django 5.0.8 on 2026-01-05 14:36
# Migration to fix database column names (remove Django's automatic _id suffix)

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # Rename database columns for ForeignKeys to match db_column settings

        # For Role.id_organisme: rename id_organisme_id to id_organisme
        migrations.RunSQL(
            sql='ALTER TABLE t_roles RENAME COLUMN id_organisme_id TO id_organisme;',
            reverse_sql='ALTER TABLE t_roles RENAME COLUMN id_organisme TO id_organisme_id;',
        ),

        # For CorRoleSite.id_site: rename id_site_id to id_site
        migrations.RunSQL(
            sql='ALTER TABLE cor_role_site RENAME COLUMN id_site_id TO id_site;',
            reverse_sql='ALTER TABLE cor_role_site RENAME COLUMN id_site TO id_site_id;',
        ),

        # For CorRoleSite.id_role: rename id_role_id to id_role
        migrations.RunSQL(
            sql='ALTER TABLE cor_role_site RENAME COLUMN id_role_id TO id_role;',
            reverse_sql='ALTER TABLE cor_role_site RENAME COLUMN id_role TO id_role_id;',
        ),

        # For CorOgSite.id_site: rename id_site_id to id_site
        migrations.RunSQL(
            sql='ALTER TABLE cor_site_og RENAME COLUMN id_site_id TO id_site;',
            reverse_sql='ALTER TABLE cor_site_og RENAME COLUMN id_site TO id_site_id;',
        ),

        # For CorOgSite.uuid_og: rename uuid_og_id to uuid_organisme
        migrations.RunSQL(
            sql='ALTER TABLE cor_site_og RENAME COLUMN uuid_og_id TO uuid_organisme;',
            reverse_sql='ALTER TABLE cor_site_og RENAME COLUMN uuid_organisme TO uuid_og_id;',
        ),
    ]
