# Generated by Django 5.0.8 on 2025-11-18 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="role",
            managers=[],
        ),
    ]
