# Generated by Django 5.0.8 on 2025-11-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_role_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="role_level",
            field=models.CharField(
                choices=[
                    ("utilisateur", "Utilisateur"),
                    ("referent", "Référent"),
                    ("admin_og", "Administrateur Organisme"),
                    ("super_admin", "Super Administrateur"),
                ],
                default="utilisateur",
                max_length=20,
                verbose_name="Niveau de rôle",
            ),
        ),
    ]
