# Generated by Django 5.0.8 on 2026-01-05
# Migration to change Role.id_organisme from integer FK to UUID FK

from django.db import migrations


def migrate_id_to_uuid(apps, schema_editor):
    """
    Migrate id_organisme (integer) to uuid_organisme (UUID) in t_roles table.
    This requires looking up the UUID for each organisme ID.
    """
    cursor = schema_editor.connection.cursor()

    # Get all users with an organisme (save the mappings before changing schema)
    cursor.execute("""
        SELECT r.id_role, r.id_organisme, o.uuid_organisme
        FROM t_roles r
        INNER JOIN bib_organismes o ON r.id_organisme = o.id_organisme
        WHERE r.id_organisme IS NOT NULL
    """)
    mappings = cursor.fetchall()

    # Clear the old column values first (to avoid FK constraint issues)
    cursor.execute("UPDATE t_roles SET id_organisme = NULL WHERE id_organisme IS NOT NULL")

    # Drop the old FK constraint and column
    cursor.execute("""
        ALTER TABLE t_roles DROP COLUMN id_organisme
    """)

    # Add new UUID column with FK to uuid_organisme
    cursor.execute("""
        ALTER TABLE t_roles
        ADD COLUMN uuid_organisme UUID NULL
        REFERENCES bib_organismes(uuid_organisme) ON DELETE SET NULL
    """)

    # Populate the new column with UUIDs from our saved mappings
    for id_role, id_org, uuid_org in mappings:
        cursor.execute(
            "UPDATE t_roles SET uuid_organisme = %s WHERE id_role = %s",
            [uuid_org, id_role]
        )


def migrate_uuid_to_id(apps, schema_editor):
    """
    Reverse migration: convert uuid_organisme back to id_organisme.
    """
    cursor = schema_editor.connection.cursor()

    # Get all users with an organisme UUID (save the mappings)
    cursor.execute("""
        SELECT r.id_role, r.uuid_organisme, o.id_organisme
        FROM t_roles r
        INNER JOIN bib_organismes o ON r.uuid_organisme = o.uuid_organisme
        WHERE r.uuid_organisme IS NOT NULL
    """)
    mappings = cursor.fetchall()

    # Drop UUID column
    cursor.execute("ALTER TABLE t_roles DROP COLUMN uuid_organisme")

    # Add integer column back
    cursor.execute("""
        ALTER TABLE t_roles
        ADD COLUMN id_organisme INTEGER NULL
        REFERENCES bib_organismes(id_organisme) ON DELETE SET NULL
    """)

    # Populate with IDs from our saved mappings
    for id_role, uuid_org, id_org in mappings:
        cursor.execute(
            "UPDATE t_roles SET id_organisme = %s WHERE id_role = %s",
            [id_org, id_role]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_db_columns"),
    ]

    operations = [
        migrations.RunPython(migrate_id_to_uuid, migrate_uuid_to_id),
    ]
