# Generated by Django 5.0.8 on 2026-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_site_id_inpn_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="anonymized_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Anonymise le"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de demande de suppression du compte (RGPD)",
                null=True,
                verbose_name="Demande de suppression le",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_anonymized",
            field=models.BooleanField(
                default=False,
                help_text="Le compte a ete anonymise suite a une demande RGPD",
                verbose_name="Compte anonymise",
            ),
        ),
    ]
