# Generated by Django 5.0.8 on 2026-01-22 12:49
# Migration modifiée pour générer les slugs des sites existants

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Génère les slugs pour tous les sites existants."""
    Site = apps.get_model('users', 'Site')

    for site in Site.objects.all():
        if not site.slug:
            base_slug = slugify(site.nom_site, allow_unicode=False)
            if not base_slug:
                base_slug = f"site-{site.id_site}"

            slug = base_slug
            counter = 1

            # Chercher un slug unique
            while Site.objects.filter(slug=slug).exclude(pk=site.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            site.slug = slug
            site.save(update_fields=['slug'])


def reverse_slugs(apps, schema_editor):
    """Reverse migration - ne fait rien car on supprime le champ."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_rgpd_fields"),
    ]

    operations = [
        # 1. Ajouter le champ slug comme nullable, SANS index automatique
        migrations.AddField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                db_index=False,  # Désactiver l'index automatique
                help_text="Identifiant URL unique généré automatiquement à partir du nom",
                max_length=280,
                verbose_name="Slug",
            ),
        ),
        # 2. Générer les slugs pour les sites existants
        migrations.RunPython(generate_slugs, reverse_slugs),
        # 3. Rendre non-nullable, toujours sans index
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_index=False,  # Toujours pas d'index automatique
                help_text="Identifiant URL unique généré automatiquement à partir du nom",
                max_length=280,
                verbose_name="Slug",
            ),
        ),
        # 4. Créer la contrainte unique manuellement avec IF NOT EXISTS
        migrations.RunSQL(
            sql="""
            -- Supprimer les index s'ils existent (au cas où)
            DROP INDEX IF EXISTS "referentiels"."t_espace_protege_slug_e3fdf968_like";
            DROP INDEX IF EXISTS "referentiels"."t_espace_protege_slug_e3fdf968";
            DROP INDEX IF EXISTS "referentiels"."t_espace_protege_slug_key";

            -- Créer l'index unique
            CREATE UNIQUE INDEX "t_espace_protege_slug_e3fdf968"
            ON "referentiels"."t_espace_protege" ("slug");

            -- Créer l'index pour les opérations LIKE (varchar_pattern_ops)
            CREATE INDEX "t_espace_protege_slug_e3fdf968_like"
            ON "referentiels"."t_espace_protege" ("slug" varchar_pattern_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS "referentiels"."t_espace_protege_slug_e3fdf968_like";
            DROP INDEX IF EXISTS "referentiels"."t_espace_protege_slug_e3fdf968";
            """
        ),
        # 5. Mettre à jour l'état Django pour refléter que le champ est unique
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="site",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        help_text="Identifiant URL unique généré automatiquement à partir du nom",
                        max_length=280,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            database_operations=[],  # Déjà fait via RunSQL
        ),
    ]
