# Generated by Django 5.0.8 on 2026-01-08 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_migrate_role_to_uuid_organisme"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Desactive le"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deactivated_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Desactive par",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="deactivation_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motif de desactivation"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="pending_validation",
            field=models.BooleanField(
                default=False,
                help_text="Utilisateur inscrit mais en attente de validation",
                verbose_name="En attente de validation",
            ),
        ),
        # NOTE: AlterField operations removed because the database columns
        # already have the correct names (id_site, uuid_organisme, id_role).
        # Django was incorrectly detecting these as changes.
    ]
