# Generated by Django 5.0.8 on 2026-01-22 12:49
# Migration modifiée pour générer les slugs des sites existants

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Génère les slugs pour tous les sites existants."""
    Site = apps.get_model('users', 'Site')

    for site in Site.objects.all():
        if not site.slug:
            base_slug = slugify(site.nom_site, allow_unicode=False)
            if not base_slug:
                base_slug = f"site-{site.id_site}"

            slug = base_slug
            counter = 1

            # Chercher un slug unique
            while Site.objects.filter(slug=slug).exclude(pk=site.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            site.slug = slug
            site.save(update_fields=['slug'])


def reverse_slugs(apps, schema_editor):
    """Reverse migration - ne fait rien car on supprime le champ."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_rgpd_fields"),
    ]

    operations = [
        # 1. Ajouter le champ slug comme nullable d'abord
        migrations.AddField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                help_text="Identifiant URL unique généré automatiquement à partir du nom",
                max_length=280,
                verbose_name="Slug",
            ),
        ),
        # 2. Générer les slugs pour les sites existants
        migrations.RunPython(generate_slugs, reverse_slugs),
        # 3. Rendre le champ non-nullable et unique
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Identifiant URL unique généré automatiquement à partir du nom",
                max_length=280,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
