# Generated by Django 5.0.8 on 2026-01-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_slug_to_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkImportJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_sites",
                    models.IntegerField(default=0, verbose_name="Total sites"),
                ),
                (
                    "processed_sites",
                    models.IntegerField(default=0, verbose_name="Sites traités"),
                ),
                (
                    "created_sites",
                    models.IntegerField(default=0, verbose_name="Sites créés"),
                ),
                (
                    "failed_sites",
                    models.IntegerField(default=0, verbose_name="Sites échoués"),
                ),
                (
                    "validation_pending_sites",
                    models.IntegerField(
                        default=0, verbose_name="Sites en attente de validation"
                    ),
                ),
                (
                    "import_data",
                    models.JSONField(default=dict, verbose_name="Données d'import"),
                ),
                (
                    "result_data",
                    models.JSONField(default=dict, verbose_name="Données de résultat"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job d'import en masse",
                "verbose_name_plural": "Jobs d'import en masse",
                "db_table": '"ccd_commons"."t_bulk_import_jobs"',
                "ordering": ["-created_at"],
            },
        ),
    ]
