# Generated by Django 5.0.8 on 2026-02-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_bulk_import_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="type_site_precision",
            field=models.CharField(
                blank=True,
                help_text="Précision quand le type est 'Autre'",
                max_length=100,
                null=True,
                verbose_name="Précision du type de site",
            ),
        ),
    ]
