# Generated by Django 5.0.8 on 2026-01-14 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_referent_role_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corogsite",
            name="id_site",
            field=models.ForeignKey(
                db_column="id_site",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.site",
            ),
        ),
        migrations.AlterField(
            model_name="corogsite",
            name="uuid_og",
            field=models.ForeignKey(
                db_column="uuid_organisme",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.biborganismes",
                to_field="uuid_organisme",
            ),
        ),
        migrations.AlterField(
            model_name="corrolesite",
            name="id_role",
            field=models.ForeignKey(
                db_column="id_role",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="corrolesite",
            name="id_site",
            field=models.ForeignKey(
                db_column="id_site",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.site",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id_organisme",
            field=models.ForeignKey(
                blank=True,
                db_column="uuid_organisme",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.biborganismes",
                to_field="uuid_organisme",
                verbose_name="Organisme",
            ),
        ),
    ]
