# Generated by Django 5.0.8 on 2026-03-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("users", "0006_add_type_site_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="biborganismes",
            name="id_type_organisme",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type_organisme",
                help_text="CEN, RNF, DREAL, PNR, OFB, etc.",
                limit_choices_to={"id_type__mnemonique": "TYPE_ORGANISME"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organismes_type",
                to="core.nomenclature",
                verbose_name="Type d'organisme",
            ),
        ),
    ]
