# Generated by Django 5.0.8 on 2026-03-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_type_organisme"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorRedacteurSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_association",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'association"
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        db_column="id_site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organismes_redacteurs",
                        to="users.site",
                    ),
                ),
                (
                    "uuid_og",
                    models.ForeignKey(
                        db_column="uuid_organisme",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.biborganismes",
                        to_field="uuid_organisme",
                        verbose_name="Organisme rédacteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site - Organisme rédacteur",
                "verbose_name_plural": "Sites - Organismes rédacteurs",
                "db_table": '"referentiels"."cor_redacteur_site"',
                "db_table_comment": "Organismes rédacteurs des sites",
                "unique_together": {("id_site", "uuid_og")},
            },
        ),
    ]
