# Generated by Django 5.0.8 on 2026-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_add_redacteur_principal_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_level",
            field=models.CharField(
                choices=[
                    ("utilisateur", "Utilisateur"),
                    ("admin_og", "Administrateur Organisme"),
                    ("redacteur_principal", "Rédacteur Général"),
                    ("super_admin", "Super Administrateur"),
                ],
                default="utilisateur",
                max_length=20,
                verbose_name="Niveau de rôle",
            ),
        ),
    ]
