INSERT INTO referentiels.t_nomenclatures VALUES (381, 8, 'CDI de projet', 'Contrat à durée indéterminée de projet', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (382, 10, 'Fonds Propres', 'Fonds Propres', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (42, 1, 'RNN', 'Réserve Naturelle Nationale', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (50, 3, 'Autre', 'Autre', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (141, 14, 'Camping', 'Camping', NULL, NULL, NULL, '10.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (43, 1, 'RNR', 'Réserve Naturelle Régionale', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (44, 1, 'RNC', 'Réserve Naturelle de Corse', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (45, 2, 'Aucune', 'Aucune évaluation', NULL, NULL, NULL, '1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (46, 2, 'Finale', 'Évaluation finale', NULL, NULL, NULL, '3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (47, 2, 'Intermédiaire', 'Évaluation intermédiaire', NULL, NULL, NULL, '2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (48, 3, 'OG', 'Organisme Gestionnaire', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (49, 3, 'BE', 'Bureau d''études', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (51, 4, 'Oui', 'Oui', NULL, NULL, NULL, '1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (52, 4, 'Projet planifié', 'En projet et planifié sur le plan de gestion', NULL, NULL, NULL, '2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (53, 4, 'Projet non planifié', 'En projet mais non planifié sur le plan de gestion', NULL, NULL, NULL, '3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (54, 4, 'Non', 'Non', NULL, NULL, NULL, '4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (55, 5, 'PG', 'Plan de gestion', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (56, 5, 'PG simplifié', 'Plan de gestion simplifié', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (57, 5, 'Annexes', 'Annexes', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (58, 5, 'Eval', 'Évaluation', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (59, 5, 'Atlas carto', 'Atlas cartographique', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (60, 5, 'Fiches actions', 'Fiches Actions', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (61, 5, 'Autre', 'Autre document', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (62, 6, 'creation', 'Acte de création d''espace protégé', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (63, 6, 'modification', 'Acte de modification d''espace protégé', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (64, 6, 'abrogation', 'Acte d''abrogation d''espace protégé', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (65, 6, 'designation gestion', 'Acte de désignation d''organisme gestionnaire', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (66, 6, 'convention gestion', 'Convention de gestion', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (67, 7, 'Homme', 'Homme', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (68, 7, 'Femme', 'Femme', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (69, 8, 'CDD', 'Contrat à durée déterminée', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (70, 8, 'CDI', 'Contrat à durée indéterminée', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (71, 8, 'Apprenti', 'Contrat d''apprentissage', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (72, 8, 'Insertion', 'Contrat d''insertion', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (73, 8, 'Service civique', 'Service civique', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (74, 7, 'Autre', 'Autre', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (75, 9, 'police', 'Mission Police', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (76, 9, 'montagne', 'Milieu Montagne', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (77, 9, 'marin', 'Milieu Marin', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (78, 9, 'terrain', 'Mission terrain', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (79, 9, 'risque naturel', 'Risque Naturel', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (80, 9, 'risque technologique', 'Risque technologique', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (81, 10, 'europe', 'Fonds européens (FEDER, FEADER, LIFE, INTERREG..)', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (82, 10, 'France Relance', 'Plan France Relance', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (83, 10, 'Etat', 'Etat', '', NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (84, 10, 'Régions', 'Régions', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (85, 10, 'Fonds Verts', 'Fonds Verts', '', NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (86, 10, 'Fonds dédiés EDD', 'Fonds dédiés EDD', '', NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (87, 10, 'Départements', 'Départements', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (88, 10, 'Caisse des dépôts et consignations', 'Caisse des dépôts et consignations', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (89, 10, 'Communes', 'Communes', '', NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (90, 10, 'Etablissements publics', 'Etablissements publics', '', NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (91, 10, 'Mécénat', 'Mécénat', '', NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (92, 10, 'Dons', 'Dons', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (93, 1, 'PPRN', 'Périmètre de protection de réserve naturelle', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (94, 11, 'Périmètre de protection', 'Périmètre de protection', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (95, 12, 'Autorisé', 'Autorisé dans les conditions du droit commun', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (96, 12, 'Encadré', 'Encadré par l''acte de classement du site', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (97, 12, 'Interdit', 'Interdit par l''acte de classement du site (hors dérogation à visée scientifique ou de gestion)', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (98, 12, 'Doute', 'Doute sur l''interprétation du texte', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (99, 13, 'Présente', 'Activité présente', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (100, 13, 'Absente', 'Activité absente', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (101, 14, 'Circulation', 'Circulation des personnes', NULL, NULL, NULL, '1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (102, 14, 'Activités agricoles', 'Activités agricoles', NULL, NULL, NULL, '2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (103, 14, 'Maraîchage', 'Maraîchage', NULL, NULL, NULL, '2.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (104, 14, 'Cultures pérennes', 'Cultures pérennes : viticulture, arboriculture, oléiculture', NULL, NULL, NULL, '2.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (105, 14, 'Cultures céréalières ou oléoprotéagineuses', 'Cultures céréalières ou oléoprotéagineuses', NULL, NULL, NULL, '2.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (106, 14, 'Fauche de prairies semi-naturelles', 'Fauche de prairies semi-naturelles', NULL, NULL, NULL, '2.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (107, 14, 'Fauche de prairies cultivées', 'Fauche de prairies cultivées', NULL, NULL, NULL, '2.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (108, 14, 'Pâturage', 'Pâturage', NULL, NULL, NULL, '2.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (109, 14, 'Autres activités d''élevage (hors pâturage)', 'Autres activités d''élevage (hors pâturage)', NULL, NULL, NULL, '2.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (110, 14, 'Apiculture', 'Apiculture', NULL, NULL, NULL, '2.8', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (111, 14, 'Activités forestières', 'Activités forestières', NULL, NULL, NULL, '3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (112, 14, 'Sylviculture ', 'Sylviculture ', NULL, NULL, NULL, '3.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (113, 14, 'Plantation d''essences locales', 'Plantation d''essences locales', NULL, NULL, NULL, '3.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (114, 14, 'Plantation d''essences non locales', 'Plantation d''essences non locales', NULL, NULL, NULL, '3.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (115, 14, 'Activités aquacoles', 'Activités aquacoles', NULL, NULL, NULL, '4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (116, 14, 'Pisciculture', 'Pisciculture', NULL, NULL, NULL, '4.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (117, 14, 'Conchyliculture', 'Conchyliculture', NULL, NULL, NULL, '4.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (118, 14, 'Chasse', 'Chasse', NULL, NULL, NULL, '5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (119, 14, 'Chasse au gros gibier', 'Chasse au gros gibier', NULL, NULL, NULL, '5.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (120, 14, 'Chasse au petit gibier', 'Chasse au petit gibier', NULL, NULL, NULL, '5.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (121, 14, 'Chasse au gibier d''eau', 'Chasse au gibier d''eau', NULL, NULL, NULL, '5.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (122, 14, 'Battues administratives', 'Battues administratives', NULL, NULL, NULL, '5.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (123, 14, 'Pêche', 'Pêche', NULL, NULL, NULL, '6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (124, 14, 'Pêche professionnelle', 'Pêche professionnelle', NULL, NULL, NULL, '6.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (125, 14, 'Pêche de loisir', 'Pêche de loisir', NULL, NULL, NULL, '6.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (126, 14, 'Cueillettes', 'Cueillettes', NULL, NULL, NULL, '7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (127, 14, 'Cueillette de baies et fruits sauvages', 'Cueillette de baies et fruits sauvages', NULL, NULL, NULL, '7.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (128, 14, 'Cueillette de plantes', 'Cueillette de plantes', NULL, NULL, NULL, '7.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (129, 14, 'Cueillette de champignons', 'Cueillette de champignons', NULL, NULL, NULL, '7.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (130, 14, 'Ramassage d''escargots', 'Ramassage d''escargots', NULL, NULL, NULL, '7.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (131, 14, 'Activités sportives', 'Activités sportives', NULL, NULL, NULL, '8', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (132, 14, 'Activités sportives et récréatives terrestres non motorisées', 'Activités sportives et récréatives terrestres non motorisées', NULL, NULL, NULL, '8.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (133, 14, 'Activités sportives et récréatives aquatiques non motorisées', 'Activités sportives et récréatives aquatiques non motorisées', NULL, NULL, NULL, '8.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (134, 14, 'Activités sportives et récréatives aériennes non motorisées', 'Activités sportives et récréatives aériennes non motorisées', NULL, NULL, NULL, '8.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (135, 14, 'Activités sportives et récréatives motorisées', 'Activités sportives et récréatives motorisées', NULL, NULL, NULL, '8.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (136, 14, 'Activités de bien-être', 'Activités de bien-être', 'Les activités de bien-être ou de santé permettent à un individu de se sentir en harmonie avec soi-même, la société, et l''environnement afin de faire face au stress ou aux difficultés du quotidien. Elles intègrent des dimensions physiques, mentales et sociales (ex : yoga, bain de forêt, etc.)', NULL, NULL, '8.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (137, 14, 'Manifestations sportives et culturelles', 'Manifestations sportives et culturelles', NULL, NULL, NULL, '9', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (138, 14, 'Manifestations sportives', 'Manifestations sportives', NULL, NULL, NULL, '9.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (139, 14, 'Manifestations culturelles et artistiques', 'Manifestations culturelles et artistiques', NULL, NULL, NULL, '9.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (140, 14, 'Camping,Bivouac', 'Camping,Bivouac', NULL, NULL, NULL, '10', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (142, 14, 'Bivouac', 'Bivouac', NULL, NULL, NULL, '10.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (143, 15, 'Oui', 'Oui, tout le temps', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (144, 15, 'Oui, certaines saisons', 'Oui, mais à certaines saisons seulement', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (145, 15, 'Oui, mais encadré', 'Oui, mais seulement dans le cadre de sorties encadrées', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (146, 15, 'Non', 'Non', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (147, 16, 'Amplificateurs auditifs', 'Amplificateurs auditifs', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (148, 16, 'Fauteuils roulants/ joëlettes', 'Fauteuils roulants/ joëlettes', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (149, 16, 'Signalétiques adaptées (hauteur des panneaux, typologie adaptée..)', 'Signalétiques adaptées (hauteur des panneaux, typologie adaptée..)', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (150, 16, 'Plaques et matériels braille', 'Plaques et matériels braille', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (151, 16, 'Fils d''ariane', 'Fils d''ariane', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (152, 16, 'Observatoire adapté pour PMR', 'Observatoire adapté pour PMR', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (153, 16, 'Cheminements spécialisés pour PMR', 'Cheminements spécialisés pour PMR', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (154, 16, 'Parking PMR', 'Parking PMR', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (155, 17, 'Etude de fréquentation', 'Etude de fréquentation', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (156, 17, 'Plan de circulation', 'Plan de circulation', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (157, 17, 'Plan d''interprétation', 'Plan d''interprétation', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (158, 18, 'Maison de réserve/ point d''accueil', 'Maison de réserve/ point d''accueil', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (159, 18, 'Boutique', 'Boutique', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (160, 18, 'Kiosque/ carbet', 'Kiosque/ carbet', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (161, 18, 'Aire de stationnement', 'Aire de stationnement', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (162, 18, 'Refuge', 'Refuge', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (164, 18, 'Poste d''observation', 'Poste d''observation', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (167, 20, 'Pratique libre', 'Pratique libre', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (168, 20, 'Activité absente', 'Activité absente de l''espace protégé', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (169, 19, 'Activités sportives et récréatives terrestres non motorisées', 'Activités sportives et récréatives terrestres non motorisées', NULL, NULL, NULL, '1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (170, 19, 'Randonnée pédestre', 'Randonnée pédestre', NULL, NULL, NULL, '1.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (171, 19, 'Trail', 'Trail', NULL, NULL, NULL, '1.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (172, 19, 'Marche nordique', 'Marche nordique', NULL, NULL, NULL, '1.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (173, 19, 'Course d''orientation', 'Course d''orientation', NULL, NULL, NULL, '1.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (174, 19, 'Randonnée équestre', 'Randonnée équestre', NULL, NULL, NULL, '1.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (175, 19, 'Cyclisme (dont VTT) sans assistance électrique', 'Cyclisme (dont VTT) sans assistance électrique', NULL, NULL, NULL, '1.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (176, 19, 'Raquettes à neige', 'Raquettes à neige', NULL, NULL, NULL, '1.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (177, 19, 'Ski de randonnée', 'Ski de randonnée', NULL, NULL, NULL, '1.8', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (178, 19, 'Escalade, alpinisme', 'Escalade, alpinisme', NULL, NULL, NULL, '1.9', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (179, 19, 'Spéléologie, canyoning', 'Spéléologie, canyoning', NULL, NULL, NULL, '1.10', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (180, 19, 'Autres activités terrestres non motorisées', 'Autres activités terrestres non motorisées', NULL, NULL, NULL, '1.11', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (181, 19, 'Activités sportives et récréatives aquatiques non motorisées', 'Activités sportives et récréatives aquatiques non motorisées', NULL, NULL, NULL, '2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (182, 19, 'Baignade, natation', 'Baignade, natation', NULL, NULL, NULL, '2.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (183, 19, 'Canoë-kayak', 'Canoë-kayak', NULL, NULL, NULL, '2.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (184, 19, 'Rafting', 'Rafting', NULL, NULL, NULL, '2.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (185, 19, 'Aviron, pirogue à rame, barque, etc.', 'Aviron, pirogue à rame, barque, etc.', NULL, NULL, NULL, '2.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (186, 19, 'Surf, windsurf, kitesurf, planche à voile', 'Surf, windsurf, kitesurf, planche à voile', NULL, NULL, NULL, '2.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (187, 19, 'Plaisance non motorisée', 'Plaisance non motorisée', NULL, NULL, NULL, '2.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (188, 19, 'Canyoning, coastering', 'Canyoning, coastering', NULL, NULL, NULL, '2.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (189, 19, 'Plongée de loisir, masque et tuba, apnée, randonnée subaquatique', 'Plongée de loisir, masque et tuba, apnée, randonnée subaquatique', NULL, NULL, NULL, '2.8', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (190, 19, 'Autres activités aquatiques non motorisées', 'Autres activités aquatiques non motorisées', NULL, NULL, NULL, '2.9', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (191, 19, 'Activités sportives et récréatives motorisées', 'Activités sportives et récréatives motorisées', NULL, NULL, NULL, '3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (192, 19, 'Vélo (dont VTT) avec assistance électrique', 'Vélo (dont VTT) avec assistance électrique', NULL, NULL, NULL, '3.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (193, 19, 'Motocross', 'Motocross', NULL, NULL, NULL, '3.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (194, 19, 'Quad', 'Quad', NULL, NULL, NULL, '3.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (195, 19, 'Aviation légère, hélicoptère, ULM, paramoteur', 'Aviation légère, hélicoptère, ULM, paramoteur', NULL, NULL, NULL, '3.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (196, 19, 'Usage de drones', 'Usage de drones', NULL, NULL, NULL, '3.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (197, 19, 'Sports motonautiques (jetski, ski nautique, subwing, etc.)', 'Sports motonautiques (jetski, ski nautique, subwing, etc.)', NULL, NULL, NULL, '3.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (198, 19, 'Plaisance motorisée', 'Plaisance motorisée', NULL, NULL, NULL, '3.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (199, 19, 'Autres activités motorisées', 'Autres activités motorisées', NULL, NULL, NULL, '3.8', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (200, 19, 'Manifestations sportives', 'Manifestations sportives', NULL, NULL, NULL, '4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (201, 19, 'Trails, courses pédestres', 'Trails, courses pédestres', NULL, NULL, NULL, '4.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (202, 19, 'Courses cyclistes (dont VTT)', 'Courses cyclistes (dont VTT)', NULL, NULL, NULL, '4.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (203, 19, 'Courses équestres', 'Courses équestres', NULL, NULL, NULL, '4.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (204, 19, 'Courses de ski de randonnée', 'Courses de ski de randonnée', NULL, NULL, NULL, '4.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (205, 19, 'Événéments liés à des sports nautiques', 'Événéments liés à des sports nautiques', NULL, NULL, NULL, '4.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (206, 19, 'Événéments liés au vol libre', 'Événéments liés au vol libre', NULL, NULL, NULL, '4.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (207, 19, 'Autres manifestations sportives', 'Autres manifestations sportives', NULL, NULL, NULL, '4.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (208, 19, 'Manifestations culturelles et artistiques', 'Manifestations culturelles et artistiques', NULL, NULL, NULL, '5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (209, 19, 'Expositions', 'Expositions', NULL, NULL, NULL, '5.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (210, 19, 'Cinéma', 'Cinéma', NULL, NULL, NULL, '5.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (211, 19, 'Résidences d’artistes', 'Résidences d’artistes', NULL, NULL, NULL, '5.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (212, 19, 'Photographie', 'Photographie', NULL, NULL, NULL, '5.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (213, 19, 'Concerts, festivals, musiques', 'Concerts, festivals, musiques', NULL, NULL, NULL, '5.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (214, 19, 'Représentations théâtrales, spectacles', 'Représentations théâtrales, spectacles', NULL, NULL, NULL, '5.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (215, 19, 'Chantiers artistiques, ateliers artistiques  ', 'Chantiers artistiques, ateliers artistiques  ', NULL, NULL, NULL, '5.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (216, 19, 'Visites et randonnées à thème', 'Visites et randonnées à thème', NULL, NULL, NULL, '5.8', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (217, 19, 'Autres manifestations culturelles et artistiques', 'Autres manifestations culturelles et artistiques', NULL, NULL, NULL, '5.9', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (218, 19, 'Activités de bien-être', 'Activités de bien-être', NULL, NULL, NULL, '6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (219, 19, 'Yoga', 'Yoga', NULL, NULL, NULL, '6.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (220, 19, 'Méditation', 'Méditation', NULL, NULL, NULL, '6.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (221, 19, 'Sophrologie', 'Sophrologie', NULL, NULL, NULL, '6.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (222, 19, 'Bain de forêt', 'Bain de forêt', NULL, NULL, NULL, '6.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (223, 19, 'Parcours sensoriel', 'Parcours sensoriel', NULL, NULL, NULL, '6.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (224, 21, 'Bovins', 'Bovins', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (225, 21, 'Ovins', 'Ovins', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (226, 21, 'Caprins', 'Caprins', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (227, 21, 'Equins', 'Equins', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (228, 22, 'Equipe de gestion', 'Pâturage exercé directement par l''équipe de gestion', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (229, 22, 'Indépendant sous convention', 'Pâturage exercé par un éleveur indépendant dans le cadre d''une convention avec l''espace protégé', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (230, 22, 'Indépendant sans convention', 'Pâturage exercé par un éleveur indépendant sans convention avec l''espace protégé', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (231, 22, 'Pâturage absent ', 'Pâturage absent', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (165, 20, 'Encadré par la réserve', 'Activité organisée par la réserve', NULL, NULL, NULL, NULL, NULL, '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (166, 20, 'Encadré par des prestataires extérieurs', 'Activité pratiquée dans le cadre d''activité organisée par des prestataires extérieurs au gestionnaire', NULL, NULL, NULL, NULL, NULL, '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (446, 32, 'Non', 'Non', '', '', '', '3', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (447, 32, 'Oui', 'Oui', '', '', '', '1', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (448, 32, 'En cours', 'En cours', '', '', '', '2', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (449, 31, 'Oui', 'Oui', '', '', '', '1', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (450, 31, 'En cours', 'En cours', '', '', '', '2', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (451, 31, 'Non', 'Non', '', '', '', '3', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (452, 33, 'Oui, action ', 'Oui, c''est une action à part entière du plan de gestion', '', '', '', '1', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (453, 33, 'Non', 'Non', '', '', '', '3', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (454, 33, 'Oui, transversale', 'Oui, les éléments du plan d''adaptation sont intégrés de manière transversale au plan de gestion', '', '', '', '2', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (455, 17, 'Autre', 'Autre', '', '', '', '99', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (456, 18, 'Autre', 'Autre', '', '', '', '99', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (457, 16, 'Autre', 'Autre', '', '', '', '99', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (458, 18, 'aire_de_bivouac', 'Aire de bivouac', 'Espace aménagé pour le bivouac des visiteurs', 'ODASE', 'Validé', '10', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (459, 18, 'sentier_pedagogique_decouverte', 'Sentier pédagogique de découverte', 'Sentier aménagé pour la découverte et l''éducation à l''environnement', 'ODASE', 'Validé', '11', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (163, 18, 'Aménagement de repos', 'Aménagement de repos', NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO referentiels.t_nomenclatures VALUES (460, 34, 'AGENT_ACCUEIL', 'Agent·e d''accueil', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (461, 34, 'ANIMATEUR_EEDD', 'Animateur·rice EEDD', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (462, 34, 'CHARGE_COMMUNICATION', 'Chargé·e de communication', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (463, 34, 'RESPONSABLE_ANIMATION_EEDD', 'Responsable d''animation en EEDD', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (464, 34, 'RESPONSABLE_MAISON_RN', 'Responsable de maison de RN', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (465, 34, 'AGENT_TECHNIQUE', 'Agent·e technique', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (466, 34, 'CHARGE_ETUDES', 'Chargé·e d''études', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (467, 34, 'CHARGE_MISSION_SCIENTIFIQUE', 'Chargé·e de mission scientifique', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (468, 34, 'CONSERVATEUR', 'Conservateur·rice', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (469, 34, 'GARDE', 'Garde', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (470, 34, 'RESPONSABLE_GARDES', 'Responsable des gardes', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (471, 34, 'TECHNICIEN_GESTION', 'Technicien·ne de gestion', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (472, 34, 'DIRECTEUR', 'Directeur·rice', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (473, 34, 'GEOMATICIEN', 'Géomaticien·ne', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (474, 34, 'RESPONSABLE_ADMINISTRATIF_FINANCIER', 'Responsable administratif·ve et financier·ère', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (475, 34, 'ASSISTANT_ADMINISTRATIF_FINANCIER', 'Assistant·e administratif·ve et financier·ère', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (476, 34, 'AUTRE', 'Autre', NULL, NULL, NULL, NULL, NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (477, 35, 'EUROPE', 'Europe', NULL, NULL, NULL, '1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (478, 35, 'LIFE', 'LIFE', NULL, NULL, NULL, '1.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (479, 35, 'FEDER', 'FEDER', NULL, NULL, NULL, '1.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (480, 35, 'FEADER', 'FEADER', NULL, NULL, NULL, '1.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (481, 35, 'FEAMPA', 'FEAMPA', NULL, NULL, NULL, '1.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (482, 35, 'FSE_PLUS', 'FSE+', NULL, NULL, NULL, '1.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (483, 35, 'INTERREG', 'INTERREG', NULL, NULL, NULL, '1.6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (484, 35, 'EUROPE_AUTRE', 'Autre (Europe)', NULL, NULL, NULL, '1.7', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (485, 35, 'ETAT', 'État', NULL, NULL, NULL, '2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (486, 35, 'DOTATION_RN', 'Dotation réserve naturelle (BOP113)', NULL, NULL, NULL, '2.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (487, 35, 'PLAN_FRANCE_RELANCE', 'Plan France Relance', NULL, NULL, NULL, '2.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (488, 35, 'FONDS_DEDIES_EDD', 'Fonds dédiés EDD', NULL, NULL, NULL, '2.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (489, 35, 'FONDS_VERTS', 'Fonds Verts', NULL, NULL, NULL, '2.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (490, 35, 'ETAT_AUTRE', 'Autre (État)', NULL, NULL, NULL, '2.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (491, 35, 'OPERATEURS_ETAT', 'Opérateurs de l''État', NULL, NULL, NULL, '3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (492, 35, 'OFB', 'OFB', NULL, NULL, NULL, '3.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (493, 35, 'ONF', 'ONF', NULL, NULL, NULL, '3.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (494, 35, 'AGENCE_EAU', 'Agence de l''eau', NULL, NULL, NULL, '3.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (495, 35, 'CAISSE_DEPOTS', 'Caisse des dépôts et consignations', NULL, NULL, NULL, '3.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (496, 35, 'OPERATEURS_AUTRE', 'Autre (Opérateurs État)', NULL, NULL, NULL, '3.5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (497, 35, 'COLLECTIVITES', 'Collectivités territoriales', NULL, NULL, NULL, '4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (498, 35, 'REGIONS', 'Régions', NULL, NULL, NULL, '4.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (499, 35, 'DEPARTEMENTS', 'Départements', NULL, NULL, NULL, '4.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (500, 35, 'COMMUNAUTE_COMMUNES', 'Communauté de communes', NULL, NULL, NULL, '4.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (501, 35, 'COMMUNES', 'Communes', NULL, NULL, NULL, '4.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (502, 35, 'FONDS_PRIVES', 'Fonds privés', NULL, NULL, NULL, '5', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (503, 35, 'MECENAT', 'Mécénat', NULL, NULL, NULL, '5.1', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (504, 35, 'DONS', 'Dons', NULL, NULL, NULL, '5.2', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (505, 35, 'LEGS', 'Legs', NULL, NULL, NULL, '5.3', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (506, 35, 'FONDS_PROPRES', 'Fonds propres (association)', NULL, NULL, NULL, '5.4', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (507, 35, 'AUTRE', 'Autre', NULL, NULL, NULL, '6', NULL, NULL, true);
INSERT INTO referentiels.t_nomenclatures VALUES (508, 9, 'zoonose', 'Zoonose', NULL, 'ODASE', 'Validé', NULL, '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (509, 36, 'agricole', 'Agricole', NULL, 'ODASE', 'Validé', '1', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (510, 36, 'forestier', 'Forestier', NULL, 'ODASE', 'Validé', '2', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (511, 36, 'tourbeux', 'Tourbeux', NULL, 'ODASE', 'Validé', '3', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (512, 36, 'prairie', 'Prairie', NULL, 'ODASE', 'Validé', '4', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (513, 36, 'landes_broussaille', 'Landes-Broussaille', NULL, 'ODASE', 'Validé', '5', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
INSERT INTO referentiels.t_nomenclatures VALUES (514, 36, 'autres', 'Autres', NULL, 'ODASE', 'Validé', '99', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115', true);
