INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (1, 'Espace naturel', 'Type d''espace naturel', '', NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (2, 'Evaluation PG', 'Niveau d''évaluation des plans de gestion', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (3, 'Rédacteur type', 'Type de rédacteur d''un plan de gestion', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (4, 'Réalisation DAT', 'Niveau de réalisation d''un diagnostique d''ancrage territorial', '', NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (5, 'Type acte', 'Type de document juridique', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (6, 'Type doc PG', 'Type de document de plan de gestion', '', NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (7, 'Sexe', 'Sexe', '', NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (8, 'Contrat', 'Type de contrat', '', NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (9, 'Spécifications DUERP', 'Spécifications travail en réserve du DUERP', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (10, 'Sources budget', 'Sources de financement du budget de l''organisme gestionnaire', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (11, 'Lien EP', 'Type de lien entre espaces protégés', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (12, 'Règles', 'Règles d''activités', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (13, 'Présence', 'Présence de l''activité', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (14, 'Activités', 'Activités ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (15, 'Accueil public', 'Accueil du public', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (16, 'Aménagements adaptés', 'Aménagements adaptés pour personnes handicapées', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (17, 'Documents accueil public', 'Documents pour gérer l''accueil du public', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (18, 'Infrastructures d''accueil', 'Infrastructures d''accueil de public', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (19, 'Activités sportives et de loisirs', 'Activités sportives et de loisirs', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (20, 'Encadrement des activités', 'Encadrement des activités', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (21, 'Types de paturages', 'Types de paturages', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (22, 'Acteurs paturage', 'Acteurs paturage', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (31, 'Plan d''adaptation', 'Réalisation d''un plan d''adaptation aux changements climatiques', '', '', '', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (32, 'Diagnostic de vulnérabilité', 'Réalisation d''un diagnostic de vulnérabilité aux changements climatiques', '', '', '', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (33, 'Intégration PG de la démarche naturadapt', 'Intégration PG de la démarche naturadapt', '', '', '', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (34, 'CATEGORIE_EMPLOI', 'Catégorie de l''emploi', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (35, 'SOURCES_FINANCEMENT_HIERARCHISEES', 'Sources de financement hiérarchisées par catégorie', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (36, 'Milieux incendie', 'Milieux incendie', 'Milieux concernés lors d''un incendie', 'ODASE', 'Validé', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
-- Types pour Enjeux, FCR et Responsabilités (CICADA)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (40, 'TYPE_RESPONSABILITE', 'Type de responsabilité', 'Type de responsabilité du site (floristique, faunistique, etc.)', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (41, 'NIVEAU_RESPONSABILITE', 'Niveau de responsabilité', 'Niveau géographique de la responsabilité (local, régional, etc.)', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (42, 'CATEGORIE_ENJEU', 'Catégorie d''enjeu', 'Distinction entre Enjeu de conservation et Facteur Clé de Réussite', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (43, 'IMPORTANCE_ENJEU', 'Importance de l''enjeu', 'Niveau de priorité de l''enjeu (1, 2, 3)', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (44, 'CATEGORIE_FCR', 'Catégorie de FCR', 'Catégorie du Facteur Clé de Réussite', 'CICADA', 'Validé', NOW(), NOW());
-- Types pour Indicateurs, Métriques et Mesures (CICADA - Issues #45, #46)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (46, 'TYPE_INDICATEUR', 'Type d''indicateur', 'Type d''indicateur (état, pression, réponse)', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (48, 'TYPE_METRIQUE', 'Type de métrique', 'Type de métrique (numérique, qualitatif, booléen)', 'CICADA', 'Validé', NOW(), NOW());
-- Types pour Opérations (CICADA - Issue #48)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (50, 'PRIORITE_OPERATION', 'Priorité d''opération', 'Niveau de priorité de l''opération (1, 2, 3)', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (51, 'TYPE_ACTION', 'Type d''action', 'Type d''action (SE, CS, TU, PI, etc.)', 'CICADA', 'Validé', NOW(), NOW());
-- Types pour Programmation Opérations (CICADA - Refactoring JSON → tables relationnelles)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (52, 'OPERATEUR_TYPE', 'Type d''opérateur', 'Type d''opérateur (prestataire, agent, etc.)', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (53, 'CATEGORIE_FINANCE', 'Catégorie de financement', 'Catégorie de source de financement', 'CICADA', 'Validé', NOW(), NOW());
-- Type de document de plan de gestion (CICADA - cycle de vie des plans)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (55, 'Type document plan', 'Type de document d''un plan de gestion', 'Distingue plan initial, évaluation mi-parcours et plan révisé', 'CICADA', 'Validé', NOW(), NOW());
-- Types pour Suivis/Inventaires (CICADA)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (56, 'TYPE_SUIVI', 'Type de suivi/inventaire', 'Type de suivi ou inventaire', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (57, 'STATUT_SUIVI', 'Statut du suivi/inventaire', 'Statut d''avancement du suivi ou inventaire', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (58, 'OBJECTIF_SUIVI', 'Objectif du suivi/inventaire', 'Objectif visé par le suivi ou inventaire', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (59, 'CIBLE_SUIVI', 'Cible du suivi/inventaire', 'Cible thématique du suivi ou inventaire', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (60, 'PERIODE_SUIVI', 'Période de suivi', 'Mois de l''année pour la période de suivi', NULL, NULL, NULL, NULL);
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (61, 'FREQUENCE_EMBOITEMENT', 'Fréquence - emboîtements', 'Unités de fréquence pour les emboîtements temporels', NULL, NULL, NULL, NULL);
-- Types pour Bancarisation et stockage (CICADA)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (62, 'BANCARISATION_STOCKAGE', 'Bancarisation et stockage de la donnée', 'Comment la donnée est-elle stockée ou bancarisée', 'CICADA', 'Validé', NOW(), NOW());
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (63, 'OUTIL_SAISIE', 'Outil de saisie', 'Existence d''un outil de saisie pour le protocole', 'CICADA', 'Validé', NOW(), NOW());
-- Types pour Pressions (PressRef CARET V1)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (64, 'TYPE_PRESSION', 'Type de pression', 'Référentiel PressRef CARET V1 - Types de pressions sur les espaces protégés', 'CICADA/CARET', 'Validé', NOW(), NOW());
-- Type d'organisme (CICADA - Issue #118)
INSERT INTO ref_nomenclatures.bib_nomenclatures_types (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj) VALUES (65, 'TYPE_ORGANISME', 'Type d''organisme', 'Type de structure gestionnaire (CEN, RNF, DREAL, PNR, OFB, etc.)', 'CICADA', 'Validé', NOW(), NOW());
