INSERT INTO referentiels.bib_nomenclatures_types VALUES (1, 'Espace naturel', 'Type d''espace naturel', '', NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (2, 'Evaluation PG', 'Niveau d''évaluation des plans de gestion', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (3, 'Rédacteur type', 'Type de rédacteur d''un plan de gestion', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (4, 'Réalisation DAT', 'Niveau de réalisation d''un diagnostique d''ancrage territorial', '', NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (5, 'Type acte', 'Type de document juridique', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (6, 'Type doc PG', 'Type de document de plan de gestion', '', NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (7, 'Sexe', 'Sexe', '', NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (8, 'Contrat', 'Type de contrat', '', NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (9, 'Spécifications DUERP', 'Spécifications travail en réserve du DUERP', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (10, 'Sources budget', 'Sources de financement du budget de l''organisme gestionnaire', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (11, 'Lien EP', 'Type de lien entre espaces protégés', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (12, 'Règles', 'Règles d''activités', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (13, 'Présence', 'Présence de l''activité', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (14, 'Activités', 'Activités ', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (15, 'Accueil public', 'Accueil du public', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (16, 'Aménagements adaptés', 'Aménagements adaptés pour personnes handicapées', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (17, 'Documents accueil public', 'Documents pour gérer l''accueil du public', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (18, 'Infrastructures d''accueil', 'Infrastructures d''accueil de public', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (19, 'Activités sportives et de loisirs', 'Activités sportives et de loisirs', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (20, 'Encadrement des activités', 'Encadrement des activités', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (21, 'Types de paturages', 'Types de paturages', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (22, 'Acteurs paturage', 'Acteurs paturage', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (31, 'Plan d''adaptation', 'Réalisation d''un plan d''adaptation aux changements climatiques', '', '', '', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
INSERT INTO referentiels.bib_nomenclatures_types VALUES (32, 'Diagnostic de vulnérabilité', 'Réalisation d''un diagnostic de vulnérabilité aux changements climatiques', '', '', '', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
INSERT INTO referentiels.bib_nomenclatures_types VALUES (33, 'Intégration PG de la démarche naturadapt', 'Intégration PG de la démarche naturadapt', '', '', '', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
INSERT INTO referentiels.bib_nomenclatures_types VALUES (34, 'CATEGORIE_EMPLOI', 'Catégorie de l''emploi', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (35, 'SOURCES_FINANCEMENT_HIERARCHISEES', 'Sources de financement hiérarchisées par catégorie', NULL, NULL, NULL, NULL, NULL);
INSERT INTO referentiels.bib_nomenclatures_types VALUES (36, 'Milieux incendie', 'Milieux incendie', 'Milieux concernés lors d''un incendie', 'ODASE', 'Validé', '2025-10-30 16:18:49.465115', '2025-10-30 16:18:49.465115');
