# Generated by Django 5.0.8 on 2025-11-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeNomenclature",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mnemonique",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Mnémonique"
                    ),
                ),
                (
                    "label_default",
                    models.CharField(max_length=255, verbose_name="Label par défaut"),
                ),
                (
                    "definition_default",
                    models.TextField(
                        blank=True, null=True, verbose_name="Définition par défaut"
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Label français",
                    ),
                ),
                (
                    "definition_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Définition française"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Statut"
                    ),
                ),
                ("meta_create_date", models.DateTimeField(auto_now_add=True)),
                ("meta_update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de nomenclature",
                "verbose_name_plural": "Types de nomenclatures",
                "db_table": "bib_nomenclatures_types",
                "db_table_comment": "Types de nomenclatures",
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id_nomenclature",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "cd_nomenclature",
                    models.CharField(max_length=50, verbose_name="Code"),
                ),
                (
                    "mnemonique",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mnémonique"
                    ),
                ),
                (
                    "label_default",
                    models.CharField(max_length=255, verbose_name="Label par défaut"),
                ),
                (
                    "definition_default",
                    models.TextField(
                        blank=True, null=True, verbose_name="Définition par défaut"
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Label français",
                    ),
                ),
                (
                    "definition_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Définition française"
                    ),
                ),
                (
                    "hierarchy",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Hiérarchie"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                ("meta_create_date", models.DateTimeField(auto_now_add=True)),
                ("meta_update_date", models.DateTimeField(auto_now=True)),
                (
                    "id_broader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.nomenclature",
                        verbose_name="Nomenclature parente",
                    ),
                ),
                (
                    "id_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.typenomenclature",
                        verbose_name="Type de nomenclature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nomenclature",
                "verbose_name_plural": "Nomenclatures",
                "db_table": "t_nomenclatures",
                "db_table_comment": "Table des nomenclatures",
                "unique_together": {("id_type", "cd_nomenclature")},
            },
        ),
    ]
