# Generated by Django 5.0.8 on 2025-11-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeNomenclature",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mnemonique",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mnémonique"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "definition",
                    models.TextField(blank=True, null=True, verbose_name="Définition"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Statut"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de nomenclature",
                "verbose_name_plural": "Types de nomenclatures",
                "db_table": "bib_nomenclatures_types",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id_nomenclature",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "mnemonique",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mnémonique"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "definition",
                    models.TextField(blank=True, null=True, verbose_name="Définition"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Statut"
                    ),
                ),
                (
                    "hierarchy",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Hiérarchie"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "id_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.typenomenclature",
                        verbose_name="Type de nomenclature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nomenclature",
                "verbose_name_plural": "Nomenclatures",
                "db_table": "t_nomenclatures",
                "managed": True,
            },
        ),
    ]
