# Generated by Django 5.0.8 on 2026-01-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_create_schemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code technique unique du module (ex: plans, sites, zonages)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom affiche du module",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description du module",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fi-rr-apps",
                        help_text="Classe CSS de l'icone Flaticon (ex: fi-rr-document)",
                        max_length=100,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Primaire (bleu-vert)"),
                            ("salmon", "Saumon"),
                            ("terra-cotta", "Terra cotta"),
                            ("yellow", "Jaune"),
                            ("pale-green", "Vert pâle"),
                        ],
                        default="primary",
                        help_text="Couleur de la tuile sur la page d'accueil",
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        help_text="Route Angular du module (ex: /plans)",
                        max_length=100,
                        verbose_name="Route",
                    ),
                ),
                (
                    "requires_access",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, l'utilisateur doit demander l'acces a ce module",
                        verbose_name="Nécessite un accès",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Module visible et accessible",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage sur la page d'accueil (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": '"ccd_commons"."t_modules"',
                "db_table_comment": "Table des modules applicatifs",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TypeNomenclature",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mnemonique",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mnémonique"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "definition",
                    models.TextField(blank=True, null=True, verbose_name="Définition"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Statut"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de nomenclature",
                "verbose_name_plural": "Types de nomenclatures",
                "db_table": '"ref_nomenclatures"."bib_nomenclatures_types"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id_nomenclature",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "cd_nomenclature",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Code technique unique de la nomenclature (ex: RNN, RNR, PNR)",
                        max_length=50,
                        null=True,
                        verbose_name="Code nomenclature",
                    ),
                ),
                (
                    "mnemonique",
                    models.CharField(
                        blank=True,
                        help_text="Mnémonique métier pour retrouver facilement les éléments",
                        max_length=255,
                        null=True,
                        verbose_name="Mnémonique",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "definition",
                    models.TextField(blank=True, null=True, verbose_name="Définition"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Source"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Statut"
                    ),
                ),
                (
                    "hierarchy",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Hiérarchie"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "id_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.typenomenclature",
                        verbose_name="Type de nomenclature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nomenclature",
                "verbose_name_plural": "Nomenclatures",
                "db_table": '"ref_nomenclatures"."t_nomenclatures"',
                "managed": True,
            },
        ),
    ]
