# Generated by Django 5.0.8 on 2025-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="cd_nomenclature",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code technique unique de la nomenclature (ex: RNN, RNR, PNR)",
                max_length=50,
                null=True,
                verbose_name="Code nomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="date_maj",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de mise a jour"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="definition",
            field=models.TextField(blank=True, null=True, verbose_name="Definition"),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="hierarchy",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hierarchie"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="mnemonique",
            field=models.CharField(
                blank=True,
                help_text="Mnemonique metier pour retrouver facilement les elements",
                max_length=255,
                null=True,
                verbose_name="Mnemonique",
            ),
        ),
    ]
