# Generated by Django 5.0.8 on 2026-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_cd_nomenclature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code technique unique du module (ex: plans, sites, zonages)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom affiche du module",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description du module",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fi-rr-apps",
                        help_text="Classe CSS de l'icone Flaticon (ex: fi-rr-document)",
                        max_length=100,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Primaire (bleu-vert)"),
                            ("salmon", "Saumon"),
                            ("terra-cotta", "Terra cotta"),
                            ("yellow", "Jaune"),
                            ("pale-green", "Vert pâle"),
                        ],
                        default="primary",
                        help_text="Couleur de la tuile sur la page d'accueil",
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        help_text="Route Angular du module (ex: /plans)",
                        max_length=100,
                        verbose_name="Route",
                    ),
                ),
                (
                    "requires_access",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, l'utilisateur doit demander l'acces a ce module",
                        verbose_name="Nécessite un accès",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Module visible et accessible",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage sur la page d'accueil (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "t_modules",
                "db_table_comment": "Table des modules applicatifs",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="date_maj",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="definition",
            field=models.TextField(blank=True, null=True, verbose_name="Définition"),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="hierarchy",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hiérarchie"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="mnemonique",
            field=models.CharField(
                blank=True,
                help_text="Mnémonique métier pour retrouver facilement les éléments",
                max_length=255,
                null=True,
                verbose_name="Mnémonique",
            ),
        ),
    ]
