# Generated by Django 5.0.8 on 2026-01-19 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_seed_modules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                            ("CRITICAL", "Critique"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Niveau",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "logger_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Logger"
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UUID de correlation pour tracer les requetes",
                        max_length=36,
                        null=True,
                        verbose_name="ID de correlation",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Methode HTTP",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Type d'exception",
                    ),
                ),
                (
                    "stack_trace",
                    models.TextField(blank=True, null=True, verbose_name="Stack trace"),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Contexte additionnel"
                    ),
                ),
                (
                    "acknowledged",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Acquitte"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acquitte le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Date de creation",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_error_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acquitte par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'erreur",
                "verbose_name_plural": "Logs d'erreurs",
                "db_table": '"ccd_commons"."t_error_logs"',
                "ordering": ["-created_at"],
            },
        ),
    ]
