# Generated by Django 5.0.8 on 2026-01-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_errorlog"),
        ("plans", "0002_initial"),
        ("users", "0003_add_rgpd_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("plan", "Plan de gestion"),
                            ("user", "Utilisateur"),
                            ("organisme", "Organisme"),
                            ("validation", "Demande de validation"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type d'entité",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(db_index=True, verbose_name="ID de l'entité"),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Denormalise pour affichage meme apres suppression de l'entite",
                        max_length=255,
                        verbose_name="Nom de l'entité",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        help_text="Denormalise pour affichage meme apres suppression de l'acteur",
                        max_length=255,
                        verbose_name="Nom de l'acteur",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("add_member", "Ajout membre"),
                            ("remove_member", "Retrait membre"),
                            ("add_referent", "Ajout référent"),
                            ("remove_referent", "Retrait référent"),
                            ("status_change", "Changement statut"),
                            ("activate", "Activation"),
                            ("deactivate", "Désactivation"),
                            ("rgpd_request", "Demande RGPD"),
                            ("rgpd_cancelled", "Annulation RGPD"),
                            ("rgpd_anonymized", "Anonymisation RGPD"),
                            ("access_granted", "Accès accordé"),
                            ("access_revoked", "Accès révoqué"),
                            ("validation_approved", "Validation approuvée"),
                            ("validation_rejected", "Validation rejetée"),
                            ("file_upload", "Téléversement fichier"),
                            ("file_delete", "Suppression fichier"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description lisible de l'action",
                        verbose_name="Description",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Détail des modifications: {field: {old: value, new: value}}",
                        verbose_name="Changements",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contexte additionnel",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("admin", "Admin"),
                            ("system", "Système"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=10,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acteur",
                    ),
                ),
                (
                    "related_organisme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="users.biborganismes",
                        verbose_name="Organisme lié",
                    ),
                ),
                (
                    "related_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="plans.plangestion",
                        verbose_name="Plan lié",
                    ),
                ),
                (
                    "related_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="users.site",
                        verbose_name="Site lié",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs_about_me",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'activité",
                "verbose_name_plural": "Logs d'activité",
                "db_table": '"ccd_commons"."t_activity_logs"',
                "db_table_comment": "Table de l'historique d'activité",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "-created_at"],
                        name="t_activity__entity__75a3b0_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="t_activity__actor_i_baf588_idx",
                    ),
                    models.Index(
                        fields=["related_site", "-created_at"],
                        name="t_activity__related_e10dd2_idx",
                    ),
                    models.Index(
                        fields=["related_plan", "-created_at"],
                        name="t_activity__related_e2d863_idx",
                    ),
                    models.Index(
                        fields=["related_organisme", "-created_at"],
                        name="t_activity__related_8af1e2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="t_activity__action_1c11ef_idx",
                    ),
                    models.Index(
                        fields=["visibility", "-created_at"],
                        name="t_activity__visibil_e241b6_idx",
                    ),
                ],
            },
        ),
    ]
