# Generated by Django 5.0.8 on 2026-01-23 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_activitylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "homepage_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image affichée sur la page d'accueil pour les visiteurs non connectés",
                        null=True,
                        upload_to="settings/homepage/",
                        verbose_name="Image page d'accueil",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_config_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configuration du site",
                "db_table": '"ccd_commons"."t_site_configuration"',
            },
        ),
    ]
