# Generated by Django 5.0.8 on 2026-01-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_site_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="homepage_image_position",
            field=models.CharField(
                choices=[("top", "Haut"), ("center", "Centre"), ("bottom", "Bas")],
                default="center",
                help_text="Position verticale du point focal de l'image (haut, centre, bas)",
                max_length=10,
                verbose_name="Position de l'image",
            ),
        ),
    ]
