# Generated by Django 5.0.8 on 2026-06-23 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_nomenclature_non_realise"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="header_color",
            field=models.CharField(
                default="#025359",
                help_text="Couleur de fond du bandeau (header), au format hexadécimal #RRGGBB",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La couleur doit être au format hexadécimal (ex. #025359).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="Couleur du bandeau",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="structure_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo de la structure affiché en haut à gauche du bandeau",
                null=True,
                upload_to="settings/logo/",
                verbose_name="Logo de la structure",
            ),
        ),
    ]
