# Generated by Django 5.0.8 on 2026-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_header_color_default_white"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="enable_docgestion_fcen",
            field=models.BooleanField(
                default=False,
                help_text="Affiche le champ ID Doc'Gestion FCEN dans les formulaires de plan de gestion. À n'activer que sur l'instance de la FCEN.",
                verbose_name="Champ ID Doc'Gestion FCEN",
            ),
        ),
    ]
