# Generated by Django 5.0.8 on 2026-07-31 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_siteconfiguration_enable_docgestion_fcen"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="export_color",
            field=models.CharField(
                default="#025359",
                help_text="Couleur des bandeaux, titres et en-têtes des exports Excel et Word, au format hexadécimal #RRGGBB. Par défaut la couleur de CICADA.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La couleur doit être au format hexadécimal (ex. #025359).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="Couleur des exports",
            ),
        ),
    ]
