# Generated by Django 5.0.8 on 2026-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_export_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="federation_partage",
            field=models.BooleanField(
                default=False,
                help_text="Publie la structure des plans de gestion validés (enjeux, objectifs, indicateurs, actions) vers l'exploration nationale, et donne en retour accès aux plans des autres structures. Les données de budget, de ressources humaines et de suivi ne sont jamais transmises. Sans partage, l'exploration ne porte que sur les plans de cette instance.",
                verbose_name="Partage des plans avec l'exploration nationale",
            ),
        ),
    ]
