# Generated by Django 5.2.17 on 2026-09-29 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_siteconfiguration_api_publique_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Active la mesure d'audience Matomo (pages consultées et actions principales), sans cookie et sans identifiant utilisateur.",
                verbose_name="Mesure d'audience Matomo",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_site_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identifiant numérique du site dans Matomo (idSite)",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'identifiant du site Matomo est un nombre entier.",
                        regex="^[0-9]+$",
                    )
                ],
                verbose_name="Identifiant du site Matomo",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="matomo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Adresse du serveur Matomo, ex. https://matomo.example.org",
                verbose_name="URL du serveur Matomo",
            ),
        ),
    ]
