# Generated by Django 5.0.8 on 2026-01-14 16:26

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorPgFichier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(
                        help_text="Nom original du fichier uploadé",
                        max_length=255,
                        verbose_name="Nom du fichier",
                    ),
                ),
                (
                    "chemin_fichier",
                    models.CharField(
                        help_text="Chemin d'accès au fichier sur le serveur",
                        max_length=500,
                        verbose_name="Chemin du fichier",
                    ),
                ),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("document", "Document principal"),
                            ("annexe", "Annexe"),
                            ("carte", "Carte"),
                            ("photo", "Photographie"),
                            ("rapport", "Rapport d'étude"),
                            ("autre", "Autre"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Type de fichier",
                    ),
                ),
                (
                    "taille_fichier",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (bytes)"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Extension"
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        blank=True,
                        help_text="Titre descriptif du document",
                        max_length=255,
                        null=True,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "auteur",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Auteur"
                    ),
                ),
                (
                    "date_document",
                    models.DateField(
                        blank=True,
                        help_text="Date de création/rédaction du document",
                        null=True,
                        verbose_name="Date du document",
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Le fichier est-il accessible publiquement ?",
                        verbose_name="Fichier public",
                    ),
                ),
                (
                    "ordre_affichage",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'affichage dans la liste des fichiers",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier plan de gestion",
                "verbose_name_plural": "Fichiers plans de gestion",
                "db_table": '"fichiers"."t_fichiers"',
                "db_table_comment": "Fichiers associés aux plans de gestion",
                "ordering": ["ordre_affichage", "nom_fichier"],
            },
        ),
        migrations.CreateModel(
            name="CorSitePg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rang",
                    models.IntegerField(
                        blank=True,
                        help_text="Ordre d'importance du site dans le plan (1=principal)",
                        null=True,
                        verbose_name="Rang",
                    ),
                ),
                (
                    "date_association",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'association"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Précisions sur le lien entre ce site et le plan",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Espace protégé - Plan de gestion",
                "verbose_name_plural": "Espaces protégés - Plans de gestion",
                "db_table": '"general"."cor_ep_pg"',
                "db_table_comment": "Liaison entre espaces protégés et plans de gestion",
                "ordering": ["rang", "site__nom_site"],
            },
        ),
        migrations.CreateModel(
            name="PlanGestion",
            fields=[
                ("id_pg", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_cdr",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Identifiant CDR"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, verbose_name="Nom du plan de gestion"
                    ),
                ),
                (
                    "gestion_partagee",
                    models.BooleanField(
                        default=False,
                        help_text="Ce plan concerne-t-il plusieurs sites ?",
                        verbose_name="Gestion partagée",
                    ),
                ),
                (
                    "annee_debut",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Année de début",
                    ),
                ),
                (
                    "annee_fin",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Année de fin",
                    ),
                ),
                (
                    "ct88",
                    models.BooleanField(
                        default=False,
                        help_text="Plan soumis à la circulaire CT88",
                        verbose_name="Circulaire CT88",
                    ),
                ),
                (
                    "risque_incendie",
                    models.BooleanField(
                        default=False,
                        help_text="Le risque incendie est-il pris en compte dans le plan ?",
                        verbose_name="Risque incendie pris en compte",
                    ),
                ),
                (
                    "redacteur_nom",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la personne ou structure ayant rédigé le plan",
                        max_length=255,
                        null=True,
                        verbose_name="Nom du rédacteur",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("valide", "Validé"),
                            ("archive", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Version du plan (ex: 1.0, 1.1, 2.0...)",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Emprise géographique du plan (calculée automatiquement si vide)",
                        null=True,
                        srid=4326,
                        verbose_name="Géométrie du plan",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de gestion",
                "verbose_name_plural": "Plans de gestion",
                "db_table": '"general"."t_plan_gestion"',
                "db_table_comment": "Plans de gestion des espaces naturels",
                "ordering": ["-date_maj", "nom"],
            },
        ),
    ]
