# Generated by Django 5.0.8 on 2025-11-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
        ("users", "0003_role_role_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorSitePg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rang",
                    models.IntegerField(
                        blank=True,
                        help_text="Ordre d'importance du site dans le plan (1=principal)",
                        null=True,
                        verbose_name="Rang",
                    ),
                ),
                (
                    "date_association",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'association"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Précisions sur le lien entre ce site et le plan",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "plan_de_gestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site - Plan de gestion",
                "verbose_name_plural": "Sites - Plans de gestion",
                "db_table": "cor_site_pg",
                "db_table_comment": "Liaison entre sites et plans de gestion",
                "ordering": ["rang", "site__nom_site"],
                "unique_together": {("site", "plan_de_gestion")},
            },
        ),
        migrations.DeleteModel(
            name="CorEpPg",
        ),
    ]
