# Generated by Django 5.0.8 on 2026-01-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("plans", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="corpgfichier",
            name="id_utilisateur_upload",
            field=models.ForeignKey(
                help_text="Utilisateur ayant ajouté ce fichier",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur ayant uploadé",
            ),
        ),
        migrations.AddField(
            model_name="corsitepg",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.site",
                verbose_name="Site",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="id_evaluation",
            field=models.ForeignKey(
                blank=True,
                help_text="Type d'évaluation du plan (ex: évaluation intermédiaire, finale...)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_evaluation",
                to="core.nomenclature",
                verbose_name="Type d'évaluation",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="id_redacteur_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type de rédacteur (ex: bureau d'étude, gestionnaire, autre...)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_redacteur_type",
                to="core.nomenclature",
                verbose_name="Type de rédacteur",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="id_utilisateur_ajout",
            field=models.ForeignKey(
                help_text="Utilisateur ayant créé le plan",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créateur",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="id_utilisateur_maj",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur ayant effectué la dernière modification",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dernier modificateur",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="referents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Utilisateurs référents pour ce plan",
                related_name="plans_referents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Référents du plan",
            ),
        ),
        migrations.AddField(
            model_name="corsitepg",
            name="plan_de_gestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="plans.plangestion",
                verbose_name="Plan de gestion",
            ),
        ),
        migrations.AddField(
            model_name="corpgfichier",
            name="plan_de_gestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fichiers",
                to="plans.plangestion",
                verbose_name="Plan de gestion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="corsitepg",
            unique_together={("site", "plan_de_gestion")},
        ),
    ]
