# Generated by Django 5.0.8 on 2026-01-26 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangestion",
            name="date_validation_cspn",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de validation CSPN"
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="id_docgestion_fcen",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID Doc'Gestion FCEN",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="rang",
            field=models.IntegerField(
                default=1,
                help_text="Numéro du plan (1er, 2ème, 3ème...)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Rang du plan",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="redacteurs",
            field=models.TextField(blank=True, null=True, verbose_name="Rédacteurs"),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="relecteurs",
            field=models.TextField(blank=True, null=True, verbose_name="Relecteurs"),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="surface",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Surface en hectares",
                max_digits=12,
                null=True,
                verbose_name="Surface totale concernée",
            ),
        ),
        migrations.AlterField(
            model_name="plangestion",
            name="ct88",
            field=models.BooleanField(
                default=False,
                help_text="Plan rédigé selon la méthode CT88",
                verbose_name="Méthode de rédaction CT88",
            ),
        ),
    ]
