# Generated by Django 5.0.8 on 2026-01-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_add_creation_form_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorRolePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referent",
                    models.BooleanField(
                        default=False,
                        help_text="L'utilisateur est-il référent de ce plan ?",
                        verbose_name="Référent",
                    ),
                ),
                (
                    "date_association",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'association"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Précisions sur le rôle de l'utilisateur dans le plan",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "id_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_associations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "plan_de_gestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur - Plan de gestion",
                "verbose_name_plural": "Utilisateurs - Plans de gestion",
                "db_table": '"general"."cor_role_plan"',
                "db_table_comment": "Liaison entre utilisateurs et plans de gestion",
                "ordering": ["-referent", "id_role__nom_role"],
                "unique_together": {("id_role", "plan_de_gestion")},
            },
        ),
    ]
