# Generated by Django 5.0.8 on 2026-02-05 11:44

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0004_add_cor_role_plan"),
        ("users", "0006_add_type_site_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enjeu",
            fields=[
                ("id_enjeu", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de l'enjeu ou du FCR",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "intitule_court",
                    models.CharField(
                        blank=True,
                        help_text="Max 25 caractères pour affichage",
                        max_length=50,
                        null=True,
                        verbose_name="Intitulé court",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'enjeu ou du FCR",
                        null=True,
                        verbose_name="Détails/Commentaires",
                    ),
                ),
                (
                    "rang",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="Priorité de l'enjeu (1=haute, 2=moyenne, 3=basse)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "categorie_ecologique",
                    models.BooleanField(
                        default=True,
                        help_text="True=Écologique, False=Socio-économique",
                        null=True,
                        verbose_name="Catégorie écologique",
                    ),
                ),
                (
                    "habitat",
                    models.BooleanField(
                        default=False,
                        help_text="Enjeu lié à un/des habitats",
                        verbose_name="Habitat",
                    ),
                ),
                (
                    "espece",
                    models.BooleanField(
                        default=False,
                        help_text="Enjeu lié à une/des espèces",
                        verbose_name="Espèce",
                    ),
                ),
                (
                    "processus",
                    models.BooleanField(
                        default=False,
                        help_text="Enjeu lié à un processus écologique",
                        verbose_name="Processus",
                    ),
                ),
                (
                    "etat_enjeu",
                    models.TextField(
                        blank=True,
                        help_text="Précisions sur l'état de l'enjeu",
                        null=True,
                        verbose_name="État de l'enjeu",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Emprise géographique de l'enjeu",
                        null=True,
                        srid=4326,
                        verbose_name="Géométrie",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_categorie",
                    models.ForeignKey(
                        db_column="id_categorie",
                        help_text="Enjeu de conservation ou Facteur Clé de Réussite",
                        limit_choices_to={"id_type__mnemonique": "CATEGORIE_ENJEU"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enjeux_categorie",
                        to="core.nomenclature",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "id_categorie_fcr",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_categorie_fcr",
                        help_text="Connaissance, Ancrage territorial, Fonctionnement, Autre",
                        limit_choices_to={"id_type__mnemonique": "CATEGORIE_FCR"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enjeux_categorie_fcr",
                        to="core.nomenclature",
                        verbose_name="Catégorie de FCR",
                    ),
                ),
                (
                    "id_importance",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_importance",
                        limit_choices_to={"id_type__mnemonique": "IMPORTANCE_ENJEU"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enjeux_importance",
                        to="core.nomenclature",
                        verbose_name="Importance",
                    ),
                ),
                (
                    "id_pg",
                    models.ForeignKey(
                        db_column="id_pg",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enjeux",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enjeu / FCR",
                "verbose_name_plural": "Enjeux / FCR",
                "db_table": '"general"."t_enjeux"',
                "db_table_comment": "Enjeux et Facteurs Clés de Réussite des plans de gestion",
                "ordering": ["rang", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="Responsabilite",
            fields=[
                (
                    "id_responsabilite",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de la responsabilité",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_niveau_responsabilite",
                    models.ForeignKey(
                        db_column="id_niveau_responsabilite",
                        help_text="Local, Régional, National, International",
                        limit_choices_to={
                            "id_type__mnemonique": "NIVEAU_RESPONSABILITE"
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsabilites_niveau",
                        to="core.nomenclature",
                        verbose_name="Niveau de responsabilité",
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        db_column="id_site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilites",
                        to="users.site",
                        verbose_name="Site",
                    ),
                ),
                (
                    "id_type_responsabilite",
                    models.ForeignKey(
                        db_column="id_type_responsabilite",
                        help_text="Floristique, Faunistique, Habitat, Géologique, Paysager",
                        limit_choices_to={"id_type__mnemonique": "TYPE_RESPONSABILITE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsabilites_type",
                        to="core.nomenclature",
                        verbose_name="Type de responsabilité",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilité",
                "verbose_name_plural": "Responsabilités",
                "db_table": '"general"."t_responsabilites"',
                "db_table_comment": "Responsabilités des sites",
                "ordering": ["id_type_responsabilite", "id_niveau_responsabilite"],
            },
        ),
        migrations.CreateModel(
            name="CorEnjeuTaxon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cd_nom",
                    models.IntegerField(
                        help_text="Identifiant TaxRef du taxon", verbose_name="cd_nom"
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "nom_vern",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom vernaculaire",
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxons",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enjeu - Taxon",
                "verbose_name_plural": "Enjeux - Taxons",
                "db_table": '"general"."cor_enjeu_taxon"',
                "db_table_comment": "Liaison enjeux - taxons",
                "unique_together": {("id_enjeu", "cd_nom")},
            },
        ),
        migrations.CreateModel(
            name="CorEnjeuHabitat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cd_hab",
                    models.CharField(
                        help_text="Identifiant HabRef de l'habitat",
                        max_length=50,
                        verbose_name="cd_hab",
                    ),
                ),
                (
                    "lb_hab_fr",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Libellé habitat",
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitats",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enjeu - Habitat",
                "verbose_name_plural": "Enjeux - Habitats",
                "db_table": '"general"."cor_enjeu_habitat"',
                "db_table_comment": "Liaison enjeux - habitats",
                "unique_together": {("id_enjeu", "cd_hab")},
            },
        ),
        migrations.CreateModel(
            name="CorEnjeuGeologie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_inpg",
                    models.CharField(
                        help_text="Identifiant INPG de l'élément géologique",
                        max_length=50,
                        verbose_name="id_inpg",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geologies",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enjeu - Géologie",
                "verbose_name_plural": "Enjeux - Géologie",
                "db_table": '"general"."cor_enjeu_geologie"',
                "db_table_comment": "Liaison enjeux - géologie",
                "unique_together": {("id_enjeu", "id_inpg")},
            },
        ),
        migrations.CreateModel(
            name="CorResponsabiliteTaxon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cd_nom",
                    models.IntegerField(
                        help_text="Identifiant TaxRef du taxon", verbose_name="cd_nom"
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "nom_vern",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom vernaculaire",
                    ),
                ),
                (
                    "id_responsabilite",
                    models.ForeignKey(
                        db_column="id_responsabilite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxons",
                        to="plans.responsabilite",
                        verbose_name="Responsabilité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilité - Taxon",
                "verbose_name_plural": "Responsabilités - Taxons",
                "db_table": '"general"."cor_responsabilite_taxon"',
                "db_table_comment": "Liaison responsabilités - taxons",
                "unique_together": {("id_responsabilite", "cd_nom")},
            },
        ),
        migrations.CreateModel(
            name="CorResponsabiliteHabitat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cd_hab",
                    models.CharField(
                        help_text="Identifiant HabRef de l'habitat",
                        max_length=50,
                        verbose_name="cd_hab",
                    ),
                ),
                (
                    "lb_hab_fr",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Libellé habitat",
                    ),
                ),
                (
                    "id_responsabilite",
                    models.ForeignKey(
                        db_column="id_responsabilite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitats",
                        to="plans.responsabilite",
                        verbose_name="Responsabilité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilité - Habitat",
                "verbose_name_plural": "Responsabilités - Habitats",
                "db_table": '"general"."cor_responsabilite_habitat"',
                "db_table_comment": "Liaison responsabilités - habitats",
                "unique_together": {("id_responsabilite", "cd_hab")},
            },
        ),
        migrations.CreateModel(
            name="CorResponsabiliteGeologie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_inpg",
                    models.CharField(
                        help_text="Identifiant INPG de l'élément géologique",
                        max_length=50,
                        verbose_name="id_inpg",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "id_responsabilite",
                    models.ForeignKey(
                        db_column="id_responsabilite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geologies",
                        to="plans.responsabilite",
                        verbose_name="Responsabilité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilité - Géologie",
                "verbose_name_plural": "Responsabilités - Géologie",
                "db_table": '"general"."cor_responsabilite_geologie"',
                "db_table_comment": "Liaison responsabilités - géologie",
                "unique_together": {("id_responsabilite", "id_inpg")},
            },
        ),
        migrations.CreateModel(
            name="CorResponsabiliteEnjeu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilites_liees",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
                (
                    "id_responsabilite",
                    models.ForeignKey(
                        db_column="id_responsabilite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enjeux_lies",
                        to="plans.responsabilite",
                        verbose_name="Responsabilité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilité - Enjeu",
                "verbose_name_plural": "Responsabilités - Enjeux",
                "db_table": '"general"."cor_responsabilite_enjeu"',
                "db_table_comment": "Liaison responsabilités - enjeux",
                "unique_together": {("id_responsabilite", "id_enjeu")},
            },
        ),
    ]
