# Generated by Django 5.0.8 on 2026-02-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0005_enjeux_responsabilites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacteurInfluence",
            fields=[
                (
                    "id_facteur_influence",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé du facteur d'influence",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du facteur d'influence",
                        null=True,
                        verbose_name="Détails/Commentaires",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facteurs_influence",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur d'influence",
                "verbose_name_plural": "Facteurs d'influence",
                "db_table": '"general"."t_facteurs_influence"',
                "db_table_comment": "Facteurs d'influence des enjeux",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Pression",
            fields=[
                ("id_pression", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_pressref",
                    models.CharField(
                        blank=True,
                        help_text="Référence vers un référentiel de pressions (futur)",
                        max_length=100,
                        null=True,
                        verbose_name="Référence pression",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de la pression",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la pression",
                        null=True,
                        verbose_name="Détails/Commentaires",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_facteur_influence",
                    models.ForeignKey(
                        db_column="id_facteur_influence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pressions",
                        to="plans.facteurinfluence",
                        verbose_name="Facteur d'influence",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pression",
                "verbose_name_plural": "Pressions",
                "db_table": '"general"."t_pressions"',
                "db_table_comment": "Pressions sur les facteurs d'influence",
                "ordering": ["libelle"],
            },
        ),
    ]
