# Generated by Django 5.0.8 on 2026-02-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0006_facteurs_influence_pressions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtatActuel",
            fields=[
                ("id_etat_actuel", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de l'état actuel",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'état actuel",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etats_actuels",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "État actuel",
                "verbose_name_plural": "États actuels",
                "db_table": '"general"."t_etat_actuel"',
                "db_table_comment": "États actuels des enjeux",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="ObjectifLongTerme",
            fields=[
                ("id_olt", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de l'objectif à long terme",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'objectif à long terme",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_etat",
                    models.ForeignKey(
                        db_column="id_etat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs_long_terme",
                        to="plans.etatactuel",
                        verbose_name="État actuel",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif à long terme",
                "verbose_name_plural": "Objectifs à long terme",
                "db_table": '"general"."t_objectifs_long_terme"',
                "db_table_comment": "Objectifs à long terme des enjeux",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="NiveauExigence",
            fields=[
                ("id_ne", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé du niveau d'exigence",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du niveau d'exigence",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
                (
                    "id_olt",
                    models.ForeignKey(
                        db_column="id_olt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux_exigence",
                        to="plans.objectiflongterme",
                        verbose_name="Objectif à long terme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau d'exigence",
                "verbose_name_plural": "Niveaux d'exigence",
                "db_table": '"general"."t_niveaux_exigence"',
                "db_table_comment": "Niveaux d'exigence des objectifs à long terme",
                "ordering": ["libelle"],
            },
        ),
    ]
