# Generated by Django 5.0.8 on 2026-02-12 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0007_etat_actuel_olt_niveaux_exigence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicateur",
            fields=[
                ("id_indicateur", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_indicateur",
                    models.CharField(
                        help_text="Intitulé de l'indicateur",
                        max_length=500,
                        verbose_name="Nom de l'indicateur",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'indicateur",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "est_standardise",
                    models.BooleanField(
                        default=False,
                        help_text="L'indicateur est-il standardisé ?",
                        verbose_name="Indicateur standardisé",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_ne",
                    models.ForeignKey(
                        db_column="id_ne",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicateurs",
                        to="plans.niveauexigence",
                        verbose_name="Niveau d'exigence",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
                (
                    "type_indicateur",
                    models.ForeignKey(
                        blank=True,
                        db_column="type_indicateur",
                        help_text="État, Pression ou Réponse",
                        limit_choices_to={"id_type__mnemonique": "TYPE_INDICATEUR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicateurs_type",
                        to="core.nomenclature",
                        verbose_name="Type d'indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur",
                "verbose_name_plural": "Indicateurs",
                "db_table": '"general"."t_indicateurs"',
                "db_table_comment": "Indicateurs d'état des niveaux d'exigence",
                "ordering": ["nom_indicateur"],
            },
        ),
        migrations.CreateModel(
            name="Metrique",
            fields=[
                ("id_metrique", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_metrique",
                    models.CharField(
                        help_text="Intitulé de la métrique",
                        max_length=500,
                        verbose_name="Nom de la métrique",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la métrique",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        blank=True,
                        help_text="Unité de mesure (ex: %, m², individus)",
                        max_length=100,
                        null=True,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "ponderation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pondération de la métrique dans l'indicateur",
                        max_digits=5,
                        null=True,
                        verbose_name="Pondération",
                    ),
                ),
                (
                    "etat_reference",
                    models.TextField(
                        blank=True,
                        help_text="Description de l'état de référence",
                        null=True,
                        verbose_name="État de référence",
                    ),
                ),
                (
                    "score_1_inf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 1 - Borne inférieure",
                    ),
                ),
                (
                    "score_1_sup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 1 - Borne supérieure",
                    ),
                ),
                (
                    "score_2_inf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 2 - Borne inférieure",
                    ),
                ),
                (
                    "score_2_sup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 2 - Borne supérieure",
                    ),
                ),
                (
                    "score_3_inf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 3 - Borne inférieure",
                    ),
                ),
                (
                    "score_3_sup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 3 - Borne supérieure",
                    ),
                ),
                (
                    "score_4_inf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 4 - Borne inférieure",
                    ),
                ),
                (
                    "score_4_sup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 4 - Borne supérieure",
                    ),
                ),
                (
                    "score_5_inf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 5 - Borne inférieure",
                    ),
                ),
                (
                    "score_5_sup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Score 5 - Borne supérieure",
                    ),
                ),
                (
                    "score_1_label",
                    models.CharField(
                        blank=True,
                        help_text="Label qualitatif pour le score 1 (Très mauvais)",
                        max_length=255,
                        null=True,
                        verbose_name="Label score 1",
                    ),
                ),
                (
                    "score_2_label",
                    models.CharField(
                        blank=True,
                        help_text="Label qualitatif pour le score 2 (Mauvais)",
                        max_length=255,
                        null=True,
                        verbose_name="Label score 2",
                    ),
                ),
                (
                    "score_3_label",
                    models.CharField(
                        blank=True,
                        help_text="Label qualitatif pour le score 3 (Moyen)",
                        max_length=255,
                        null=True,
                        verbose_name="Label score 3",
                    ),
                ),
                (
                    "score_4_label",
                    models.CharField(
                        blank=True,
                        help_text="Label qualitatif pour le score 4 (Bon)",
                        max_length=255,
                        null=True,
                        verbose_name="Label score 4",
                    ),
                ),
                (
                    "score_5_label",
                    models.CharField(
                        blank=True,
                        help_text="Label qualitatif pour le score 5 (Très bon)",
                        max_length=255,
                        null=True,
                        verbose_name="Label score 5",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metriques",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
                (
                    "type_metrique",
                    models.ForeignKey(
                        blank=True,
                        db_column="type_metrique",
                        help_text="Numérique, Qualitatif ou Booléen",
                        limit_choices_to={"id_type__mnemonique": "TYPE_METRIQUE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metriques_type",
                        to="core.nomenclature",
                        verbose_name="Type de métrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrique",
                "verbose_name_plural": "Métriques",
                "db_table": '"general"."t_metriques"',
                "db_table_comment": "Métriques des indicateurs",
                "ordering": ["nom_metrique"],
            },
        ),
        migrations.CreateModel(
            name="Mesure",
            fields=[
                ("id_mesure", models.AutoField(primary_key=True, serialize=False)),
                (
                    "valeur",
                    models.CharField(
                        help_text="Valeur de la mesure (numérique ou qualitative)",
                        max_length=500,
                        verbose_name="Valeur",
                    ),
                ),
                (
                    "date_mesure",
                    models.DateField(
                        blank=True,
                        help_text="Date à laquelle la mesure a été effectuée",
                        null=True,
                        verbose_name="Date de mesure",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire sur la mesure",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
                (
                    "id_metrique",
                    models.ForeignKey(
                        db_column="id_metrique",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesures",
                        to="plans.metrique",
                        verbose_name="Métrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesure",
                "verbose_name_plural": "Mesures",
                "db_table": '"general"."t_mesures"',
                "db_table_comment": "Mesures des métriques",
                "ordering": ["-date_mesure", "-date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="CorIndicateurTaxon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cd_nom",
                    models.IntegerField(
                        help_text="Identifiant TaxRef du taxon", verbose_name="cd_nom"
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "nom_vern",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom vernaculaire",
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxons",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur - Taxon",
                "verbose_name_plural": "Indicateurs - Taxons",
                "db_table": '"general"."cor_indicateur_taxon"',
                "db_table_comment": "Liaison indicateurs - taxons",
                "unique_together": {("id_indicateur", "cd_nom")},
            },
        ),
        migrations.CreateModel(
            name="CorIndicateurHabitat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cd_hab",
                    models.CharField(
                        help_text="Identifiant HabRef de l'habitat",
                        max_length=50,
                        verbose_name="cd_hab",
                    ),
                ),
                (
                    "lb_hab_fr",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Libellé habitat",
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitats",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur - Habitat",
                "verbose_name_plural": "Indicateurs - Habitats",
                "db_table": '"general"."cor_indicateur_habitat"',
                "db_table_comment": "Liaison indicateurs - habitats",
                "unique_together": {("id_indicateur", "cd_hab")},
            },
        ),
        migrations.CreateModel(
            name="CorIndicateurGeologie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_inpg",
                    models.CharField(
                        help_text="Identifiant INPG de l'élément géologique",
                        max_length=50,
                        verbose_name="id_inpg",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geologies",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur - Géologie",
                "verbose_name_plural": "Indicateurs - Géologie",
                "db_table": '"general"."cor_indicateur_geologie"',
                "db_table_comment": "Liaison indicateurs - géologie",
                "unique_together": {("id_indicateur", "id_inpg")},
            },
        ),
    ]
