# Generated by Django 5.0.8 on 2026-02-16 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0009_restructure_etat_olt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorOperationIndicateur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération - Indicateur",
                "verbose_name_plural": "Opérations - Indicateurs",
                "db_table": '"general"."cor_operation_indicateur"',
                "db_table_comment": "Liaison opérations - indicateurs",
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("id_operation", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de l'opération",
                        max_length=500,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "id_referentiel_operations",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant dans le référentiel d'opérations",
                        max_length=100,
                        null=True,
                        verbose_name="Référentiel opérations",
                    ),
                ),
                (
                    "code_operation",
                    models.CharField(
                        blank=True,
                        help_text="Code de l'opération",
                        max_length=100,
                        null=True,
                        verbose_name="Code opération",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'opération",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "annee_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Année de début de l'opération",
                        null=True,
                        verbose_name="Année min",
                    ),
                ),
                (
                    "annee_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Année de fin de l'opération",
                        null=True,
                        verbose_name="Année max",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_priorite",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_priorite",
                        help_text="Niveau de priorité de l'opération",
                        limit_choices_to={"id_type__mnemonique": "PRIORITE_OPERATION"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_priorite",
                        to="core.nomenclature",
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
                (
                    "indicateurs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operations",
                        through="plans.CorOperationIndicateur",
                        to="plans.indicateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération",
                "verbose_name_plural": "Opérations",
                "db_table": '"general"."t_operations"',
                "db_table_comment": "Opérations (actions) des plans de gestion",
                "ordering": ["libelle"],
            },
        ),
        migrations.AddField(
            model_name="coroperationindicateur",
            name="id_operation",
            field=models.ForeignKey(
                db_column="id_operation",
                on_delete=django.db.models.deletion.CASCADE,
                to="plans.operation",
                verbose_name="Opération",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coroperationindicateur",
            unique_together={("id_operation", "id_indicateur")},
        ),
    ]
