# Generated by Django 5.0.8 on 2026-02-16 15:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0010_operations"),
        ("users", "0006_add_type_site_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="financeurs",
            field=models.TextField(
                blank=True,
                help_text="Financeurs de l'action",
                null=True,
                verbose_name="Financeurs",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="frequence_nombre",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre de répétitions",
                null=True,
                verbose_name="Fréquence (nombre)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="frequence_unite",
            field=models.CharField(
                blank=True,
                help_text="Unité de fréquence (jour, semaine, mois, an)",
                max_length=50,
                null=True,
                verbose_name="Fréquence (unité)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                help_text="Emprise géographique de l'opération",
                null=True,
                srid=4326,
                verbose_name="Emprise spatiale",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="id_type_action",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type_action",
                help_text="Type d'action (SE, CS, TU, PI, etc.)",
                limit_choices_to={"id_type__mnemonique": "TYPE_ACTION"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_type_action",
                to="core.nomenclature",
                verbose_name="Type d'action",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="operateurs",
            field=models.TextField(
                blank=True,
                help_text="Opérateurs de l'action",
                null=True,
                verbose_name="Opérateurs",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="partenaires",
            field=models.TextField(
                blank=True,
                help_text="Partenaires de l'action",
                null=True,
                verbose_name="Partenaires",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="programmation_annuelle",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Format: {"2024": true, "2025": false, ...}',
                verbose_name="Programmation annuelle",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="programmation_mensuelle",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Format: {"2024": {"1": true, "2": false, ...}}',
                verbose_name="Programmation mensuelle",
            ),
        ),
        migrations.CreateModel(
            name="CorOperationMetrique",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_metrique",
                    models.ForeignKey(
                        db_column="id_metrique",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.metrique",
                        verbose_name="Métrique",
                    ),
                ),
                (
                    "id_operation",
                    models.ForeignKey(
                        db_column="id_operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.operation",
                        verbose_name="Opération",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération - Métrique",
                "verbose_name_plural": "Opérations - Métriques",
                "db_table": '"general"."cor_operation_metrique"',
                "db_table_comment": "Liaison opérations - métriques",
                "unique_together": {("id_operation", "id_metrique")},
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="metriques",
            field=models.ManyToManyField(
                blank=True,
                related_name="operations",
                through="plans.CorOperationMetrique",
                to="plans.metrique",
            ),
        ),
        migrations.CreateModel(
            name="CorOperationSite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_operation",
                    models.ForeignKey(
                        db_column="id_operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.operation",
                        verbose_name="Opération",
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        db_column="id_site",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération - Site",
                "verbose_name_plural": "Opérations - Sites",
                "db_table": '"general"."cor_operation_site"',
                "db_table_comment": "Liaison opérations - sites",
                "unique_together": {("id_operation", "id_site")},
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="sites",
            field=models.ManyToManyField(
                blank=True,
                related_name="operations",
                through="plans.CorOperationSite",
                to="users.site",
            ),
        ),
    ]
