# Generated by Django 5.0.8 on 2026-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0011_operation_financeurs_operation_frequence_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="annee_lancement_suivi",
            field=models.IntegerField(
                blank=True,
                help_text="Année de lancement du suivi (à renseigner)",
                null=True,
                verbose_name="Année de lancement du suivi",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="cout_communication",
            field=models.CharField(
                blank=True,
                help_text="Coût de communication",
                max_length=255,
                null=True,
                verbose_name="Coût de communication",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="cout_force",
            field=models.CharField(
                blank=True,
                help_text="Est-il un coût de force ?",
                max_length=255,
                null=True,
                verbose_name="Coût de force",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="differences_protocole",
            field=models.TextField(
                blank=True,
                help_text="Quelques différences avec le protocole ?",
                null=True,
                verbose_name="Différences avec le protocole",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="frequence_prescrite",
            field=models.CharField(
                blank=True,
                help_text="Fréquence prescrite",
                max_length=100,
                null=True,
                verbose_name="Fréquence prescrite",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="justification_non_respect",
            field=models.TextField(
                blank=True,
                help_text="Pourquoi ne respectez-vous pas le protocole ?",
                null=True,
                verbose_name="Justification non-respect",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="objectif_principal",
            field=models.TextField(
                blank=True,
                help_text="Objectif principal de l'action",
                null=True,
                verbose_name="Objectif principal",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="protocole_campanule_nom",
            field=models.CharField(
                blank=True,
                help_text="Nom du protocole dans Campanule",
                max_length=255,
                null=True,
                verbose_name="Protocole (Campanule)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="protocole_dans_campanule",
            field=models.BooleanField(
                blank=True,
                help_text="Le protocole est-il répertorié dans Campanule ?",
                null=True,
                verbose_name="Protocole répertorié dans Campanule",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="respect_protocole",
            field=models.BooleanField(
                blank=True,
                help_text="Respectez-vous strictement le protocole ?",
                null=True,
                verbose_name="Respect strict du protocole",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="terme_toison",
            field=models.CharField(
                blank=True,
                help_text="Terme - Toison",
                max_length=100,
                null=True,
                verbose_name="Terme - Toison",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="transmission_donnee",
            field=models.BooleanField(
                blank=True,
                help_text="Transmission de la donnée à l'organisme porteur ?",
                null=True,
                verbose_name="Transmission de la donnée",
            ),
        ),
    ]
