# Generated by Django 5.0.8 on 2026-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0012_operation_annee_lancement_suivi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="cout_communication",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="cout_force",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="frequence_prescrite",
        ),
        migrations.RemoveField(
            model_name="operation",
            name="terme_toison",
        ),
        migrations.AddField(
            model_name="operation",
            name="cibles_principales",
            field=models.CharField(
                blank=True,
                help_text="Cible(s) principale(s) (Flore, Faune, Habitat, etc.)",
                max_length=255,
                null=True,
                verbose_name="Cible(s) principale(s)",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="outil_bancarisation",
            field=models.CharField(
                blank=True,
                help_text="Outil de bancarisation utilisé",
                max_length=255,
                null=True,
                verbose_name="Outil de bancarisation",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="outil_saisie",
            field=models.CharField(
                blank=True,
                help_text="Existe t-il un outil de saisie ?",
                max_length=255,
                null=True,
                verbose_name="Outil de saisie",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="taxon_taxref",
            field=models.CharField(
                blank=True,
                help_text="Référence taxon dans Taxref",
                max_length=255,
                null=True,
                verbose_name="Taxon - Taxref",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="annee_lancement_suivi",
            field=models.IntegerField(
                blank=True,
                help_text="Année de lancement du suivi (si antérieur)",
                null=True,
                verbose_name="Année de lancement du suivi",
            ),
        ),
    ]
