# Generated by Django 5.0.8 on 2026-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0014_operationannee_financeoperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="programmation_mensuelle_defaut",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Template mensuel appliqué identiquement à toutes les années. Format: {"1": true, "2": false, ..., "12": true}',
                verbose_name="Programmation mensuelle par défaut",
            ),
        ),
    ]
