# Generated by Django 5.0.8 on 2026-02-18 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0018_suivi_inventaire_standalone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="indicateur",
            table_comment="Indicateurs des niveaux d'exigence et résultats attendus",
        ),
        migrations.AlterField(
            model_name="indicateur",
            name="id_ne",
            field=models.ForeignKey(
                blank=True,
                db_column="id_ne",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicateurs",
                to="plans.niveauexigence",
                verbose_name="Niveau d'exigence",
            ),
        ),
        migrations.CreateModel(
            name="ObjectifOperationnel",
            fields=[
                ("id_oo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé de l'objectif opérationnel",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'objectif opérationnel",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs_operationnels",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
                (
                    "id_facteur_influence",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_facteur_influence",
                        help_text="Facteur d'influence géré par cet objectif opérationnel",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectifs_operationnels",
                        to="plans.facteurinfluence",
                        verbose_name="Facteur d'influence",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif opérationnel",
                "verbose_name_plural": "Objectifs opérationnels",
                "db_table": '"general"."t_objectifs_operationnels"',
                "db_table_comment": "Objectifs opérationnels des enjeux",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="ResultatAttendu",
            fields=[
                ("id_ra", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        help_text="Intitulé du résultat attendu",
                        max_length=500,
                        verbose_name="Intitulé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du résultat attendu",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_oo",
                    models.ForeignKey(
                        db_column="id_oo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats_attendus",
                        to="plans.objectifoperationnel",
                        verbose_name="Objectif opérationnel",
                    ),
                ),
                (
                    "id_utilisateur_ajout",
                    models.ForeignKey(
                        db_column="id_utilisateur_ajout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat attendu",
                "verbose_name_plural": "Résultats attendus",
                "db_table": '"general"."t_resultats_attendus"',
                "db_table_comment": "Résultats attendus des objectifs opérationnels",
                "ordering": ["libelle"],
            },
        ),
        migrations.AddField(
            model_name="indicateur",
            name="id_resultat_attendu",
            field=models.ForeignKey(
                blank=True,
                db_column="id_resultat_attendu",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicateurs",
                to="plans.resultatattendu",
                verbose_name="Résultat attendu",
            ),
        ),
    ]
