# Generated by Django 5.0.8 on 2026-03-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0020_plangestion_slug_enjeu_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangestion",
            name="id_type_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan initial, évaluation mi-parcours, plan révisé...",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans_type_document",
                to="core.nomenclature",
                verbose_name="Type de document",
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="plan_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan dont celui-ci est dérivé",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="plans.plangestion",
                verbose_name="Plan parent",
            ),
        ),
    ]
