# Generated by Django 5.0.8 on 2026-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0021_add_plan_parent_and_type_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="enjeu",
            name="autre_ecologique",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu écologique de type autre",
                verbose_name="Autre (écologique)",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="autre_socioeco",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu socio-économique de type autre",
                verbose_name="Autre (socio-économique)",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="developpement_durable",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié au développement durable des ressources",
                verbose_name="Développement durable des ressources",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="fonctionnalite_ecosysteme",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié à une/des fonctionnalités des écosystèmes",
                verbose_name="Fonctionnalité des écosystèmes",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="patrimoine_culturel",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié au maintien du patrimoine culturel",
                verbose_name="Patrimoine culturel",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="patrimoine_geologique",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié au patrimoine géologique",
                verbose_name="Patrimoine géologique",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="usages",
            field=models.BooleanField(
                default=False, help_text="Enjeu lié aux usages", verbose_name="Usages"
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="valeur_ajoutee",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié à une/des valeurs ajoutées sociale, économique, scientifique ou éducative",
                verbose_name="Valeur ajoutée",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="valeur_paysagere",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié à la valeur paysagère",
                verbose_name="Valeur paysagère",
            ),
        ),
        migrations.AlterField(
            model_name="enjeu",
            name="processus",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu lié à un processus écologique (legacy)",
                verbose_name="Processus",
            ),
        ),
    ]
