# Generated by Django 5.0.8 on 2026-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0022_add_enjeu_type_checkboxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="enjeu",
            name="geo_ex_situ",
            field=models.BooleanField(
                default=False,
                help_text="Patrimoine géologique de type ex-situ (collections, musées)",
                verbose_name="Patrimoine géologique ex-situ",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="geo_in_situ",
            field=models.BooleanField(
                default=False,
                help_text="Patrimoine géologique de type in-situ (sites géologiques)",
                verbose_name="Patrimoine géologique in-situ",
            ),
        ),
    ]
