# Generated by Django 5.0.8 on 2026-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0023_add_enjeu_geo_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="enjeu",
            name="autre_ecologique_precision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Précision sur le type 'Autre' écologique",
                max_length=255,
                verbose_name="Précision autre (écologique)",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="autre_socioeco_precision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Précision sur le type 'Autre' socio-économique",
                max_length=255,
                verbose_name="Précision autre (socio-économique)",
            ),
        ),
    ]
