# Generated by Django 5.0.8 on 2026-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0024_add_autre_precision_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocole",
            name="cd_protocole_campanule",
            field=models.IntegerField(
                blank=True,
                help_text="Code du protocole dans le référentiel CAMPanule",
                null=True,
                verbose_name="Code protocole Campanule",
            ),
        ),
        migrations.AddField(
            model_name="protocole",
            name="nb_etp_cycle",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nombre d'ETP nécessaire par cycle de collecte",
                max_digits=8,
                null=True,
                verbose_name="Nombre d'ETP par cycle",
            ),
        ),
    ]
