# Generated by Django 5.0.8 on 2026-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0025_add_protocole_campanule_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviinventaire",
            name="objectif_secondaire",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Objectif secondaire optionnel (mnémonique nomenclature OBJECTIF_SUIVI)",
                max_length=255,
                verbose_name="Objectif secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="suiviinventaire",
            name="cibles_principales",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cible principale (mnémonique nomenclature CIBLE_SUIVI)",
                max_length=255,
                verbose_name="Cible principale",
            ),
        ),
        migrations.AlterField(
            model_name="suiviinventaire",
            name="objectif_principal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Objectif principal de la collecte de données (mnémonique nomenclature OBJECTIF_SUIVI)",
                max_length=255,
                verbose_name="Objectif principal",
            ),
        ),
    ]
