# Generated by Django 5.0.8 on 2026-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0026_add_objectif_secondaire_update_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviinventaire",
            name="suit_indicateur",
            field=models.BooleanField(
                blank=True,
                help_text="Le suivi/inventaire permet-il de suivre un indicateur ?",
                null=True,
                verbose_name="Suit un indicateur",
            ),
        ),
        migrations.AddField(
            model_name="suiviinventaire",
            name="type_indicateur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type d'indicateur (mnémonique nomenclature TYPE_INDICATEUR : ETAT, PRESSION, REPONSE)",
                max_length=50,
                verbose_name="Type d'indicateur",
            ),
        ),
    ]
