# Generated by Django 5.0.8 on 2026-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0027_add_suit_indicateur_type_indicateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suiviinventaire",
            name="annee_lancement_suivi",
        ),
        migrations.AddField(
            model_name="protocole",
            name="documentation_disponible",
            field=models.BooleanField(
                blank=True,
                help_text="Une documentation décrivant le protocole est-elle disponible ?",
                null=True,
                verbose_name="Documentation disponible",
            ),
        ),
        migrations.AddField(
            model_name="protocole",
            name="periode_suivi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mois de suivi (mnémonique nomenclature PERIODE_SUIVI)",
                max_length=50,
                verbose_name="Période de suivi",
            ),
        ),
        migrations.AddField(
            model_name="protocole",
            name="url_documentation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL de la documentation du protocole",
                max_length=500,
                verbose_name="URL de la documentation",
            ),
        ),
        migrations.AddField(
            model_name="suiviinventaire",
            name="date_lancement_suivi",
            field=models.DateField(
                blank=True,
                help_text="Date de lancement du suivi",
                null=True,
                verbose_name="Date de lancement du suivi",
            ),
        ),
        migrations.AddField(
            model_name="suiviinventaire",
            name="frequence_unite_precision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Précision si fréquence 'Autre'",
                max_length=255,
                verbose_name="Précision fréquence (autre)",
            ),
        ),
    ]
