# Generated by Django 5.0.8 on 2026-03-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0036_remove_etat_actuel"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="objectiflongterme",
            table_comment="Objectifs à long terme des enjeux",
        ),
        migrations.AlterModelTableComment(
            name="objectifoperationnel",
            table_comment="Objectifs opérationnels des pressions",
        ),
        migrations.AddField(
            model_name="suiviinventaire",
            name="id_type_action",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type_action",
                help_text="Code d'action CS associé (ex: CS8 = Inventaire de la faune)",
                limit_choices_to={"id_type__mnemonique": "TYPE_ACTION"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suivis_type_action",
                to="core.nomenclature",
                verbose_name="Type d'action",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="id_type_action",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type_action",
                help_text="Type d'action (IP1, CS2, CI2, SP1, etc.)",
                limit_choices_to={"id_type__mnemonique": "TYPE_ACTION"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_type_action",
                to="core.nomenclature",
                verbose_name="Type d'action",
            ),
        ),
    ]
