# Generated by Django 5.0.8 on 2026-03-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0037_add_type_action_to_suivi_inventaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="pression",
            name="id_type_pression",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type_pression",
                help_text="Référence PressRef CARET V1",
                limit_choices_to={"id_type__mnemonique": "TYPE_PRESSION"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pressions_type",
                to="core.nomenclature",
                verbose_name="Type de pression (PressRef)",
            ),
        ),
    ]
