# Generated by Django 5.0.8 on 2026-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0038_add_type_pression_to_pression"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationannee",
            name="id_operateur",
        ),
    ]
