# Generated by Django 5.0.8 on 2026-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0039_remove_operationannee_id_operateur"),
    ]

    operations = [
        # 1) Renommer NUMERIQUE → "Intervalle numérique"
        # 2) Ajouter CHIFFRE et TEXTE
        # 3) Migrer les métriques existantes QUALITATIF/BOOLEEN → TEXTE
        # 4) Supprimer QUALITATIF et BOOLEEN
        migrations.RunSQL(
            sql="""
            -- Renommer NUMERIQUE
            UPDATE ref_nomenclatures.t_nomenclatures
            SET label = 'Intervalle numérique',
                definition = 'Métrique de type intervalle numérique (min-max)',
                date_maj = NOW()
            WHERE id_nomenclature = 760;

            -- Ajouter CHIFFRE et TEXTE
            INSERT INTO ref_nomenclatures.t_nomenclatures
                (id_nomenclature, id_type, cd_nomenclature, mnemonique, label, definition, source, statut, hierarchy, date_ajout, date_maj, actif)
            VALUES
                (1351, 48, 'CHIFFRE', 'CHIFFRE', 'Chiffre', 'Métrique de type chiffre (valeur unique)', 'CICADA', 'Validé', '2', NOW(), NOW(), true),
                (1352, 48, 'TEXTE', 'TEXTE', 'Texte', 'Métrique de type texte (description libre)', 'CICADA', 'Validé', '3', NOW(), NOW(), true)
            ON CONFLICT (id_nomenclature) DO UPDATE SET
                label = EXCLUDED.label,
                definition = EXCLUDED.definition,
                hierarchy = EXCLUDED.hierarchy,
                date_maj = NOW();

            -- Migrer les métriques QUALITATIF (761) et BOOLEEN (762) → TEXTE (1352)
            UPDATE "general"."t_metriques"
            SET type_metrique = 1352
            WHERE type_metrique IN (761, 762);

            -- Supprimer QUALITATIF et BOOLEEN
            DELETE FROM ref_nomenclatures.t_nomenclatures
            WHERE id_nomenclature IN (761, 762);
            """,
            reverse_sql="""
            -- Restaurer QUALITATIF et BOOLEEN
            INSERT INTO ref_nomenclatures.t_nomenclatures
                (id_nomenclature, id_type, cd_nomenclature, mnemonique, label, definition, source, statut, hierarchy, date_ajout, date_maj, actif)
            VALUES
                (761, 48, 'QUALITATIF', 'QUALITATIF', 'Qualitatif', 'Métrique de type qualitatif', 'CICADA', 'Validé', '2', NOW(), NOW(), true),
                (762, 48, 'BOOLEEN', 'BOOLEEN', 'Booléen', 'Métrique de type booléen (oui/non)', 'CICADA', 'Validé', '3', NOW(), NOW(), true)
            ON CONFLICT (id_nomenclature) DO NOTHING;
            -- Restaurer nom NUMERIQUE
            UPDATE ref_nomenclatures.t_nomenclatures
            SET label = 'Numérique', definition = 'Métrique de type numérique', date_maj = NOW()
            WHERE id_nomenclature = 760;
            -- Supprimer CHIFFRE et TEXTE
            DELETE FROM ref_nomenclatures.t_nomenclatures
            WHERE id_nomenclature IN (1351, 1352);
            """,
        ),
        migrations.AddField(
            model_name="metrique",
            name="score_1_val",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Score 1 - Valeur",
            ),
        ),
        migrations.AddField(
            model_name="metrique",
            name="score_2_val",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Score 2 - Valeur",
            ),
        ),
        migrations.AddField(
            model_name="metrique",
            name="score_3_val",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Score 3 - Valeur",
            ),
        ),
        migrations.AddField(
            model_name="metrique",
            name="score_4_val",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Score 4 - Valeur",
            ),
        ),
        migrations.AddField(
            model_name="metrique",
            name="score_5_val",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Score 5 - Valeur",
            ),
        ),
    ]
