# Generated by Django 5.0.8 on 2026-03-27 16:15

from django.db import migrations, models


def truncate_intitule_court(apps, schema_editor):
    """Tronquer les intitulés courts existants qui dépassent 25 caractères."""
    Enjeu = apps.get_model("plans", "Enjeu")
    for enjeu in Enjeu.objects.filter(intitule_court__isnull=False):
        if len(enjeu.intitule_court) > 25:
            enjeu.intitule_court = enjeu.intitule_court[:25]
            enjeu.save(update_fields=["intitule_court"])


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0040_add_metrique_score_val_fields"),
    ]

    operations = [
        migrations.RunPython(truncate_intitule_court, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="enjeu",
            name="intitule_court",
            field=models.CharField(
                blank=True,
                help_text="Max 25 caractères pour affichage",
                max_length=25,
                null=True,
                verbose_name="Intitulé court",
            ),
        ),
    ]
