# Generated by Django 5.0.8 on 2026-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0041_alter_enjeu_intitule_court_max25"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangestion",
            name="autres_contributeurs",
            field=models.TextField(
                blank=True,
                help_text="Autres contributeurs au plan de gestion",
                null=True,
                verbose_name="Autres contributeurs",
            ),
        ),
    ]
