# Generated by Django 5.0.8 on 2026-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0042_add_autres_contributeurs"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationannee",
            name="budget_fonctionnement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Utilisé en mode ventilation par type de budget (sans organismes)",
                max_digits=12,
                null=True,
                verbose_name="Budget fonctionnement (€)",
            ),
        ),
        migrations.AddField(
            model_name="operationannee",
            name="budget_investissement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Utilisé en mode ventilation par type de budget (sans organismes)",
                max_digits=12,
                null=True,
                verbose_name="Budget investissement (€)",
            ),
        ),
    ]
