# Generated by Django 5.0.8 on 2026-03-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0043_add_budget_type_to_operation_annee"),
        ("users", "0008_add_cor_redacteur_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorRedacteurPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_association",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'association"
                    ),
                ),
                (
                    "plan_de_gestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organismes_redacteurs",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
                (
                    "uuid_og",
                    models.ForeignKey(
                        db_column="uuid_og",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.biborganismes",
                        to_field="uuid_organisme",
                        verbose_name="Organisme rédacteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisme rédacteur - Plan",
                "verbose_name_plural": "Organismes rédacteurs - Plans",
                "db_table": '"general"."cor_redacteur_plan"',
                "db_table_comment": "Organismes rédacteurs des plans de gestion",
                "unique_together": {("plan_de_gestion", "uuid_og")},
            },
        ),
    ]
