# Generated by Django 5.0.8 on 2026-03-30 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0044_add_cor_redacteur_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suiviinventaire",
            name="id_type_suivi",
        ),
    ]
