# Generated by Django 5.0.8 on 2026-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0046_operation_m2m_metrique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facteurinfluence",
            options={
                "ordering": ["id_facteur_influence"],
                "verbose_name": "Facteur d'influence",
                "verbose_name_plural": "Facteurs d'influence",
            },
        ),
        migrations.AlterModelOptions(
            name="pression",
            options={
                "ordering": ["id_pression"],
                "verbose_name": "Pression",
                "verbose_name_plural": "Pressions",
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="ventilation_mode",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("by_org", "Par organisme"),
                    ("by_type", "Par type de budget"),
                    ("by_org_type", "Par organisme et type de budget"),
                ],
                default="none",
                help_text="Mode de ventilation du budget (aucune, par organisme, par type, les deux)",
                max_length=20,
                verbose_name="Mode de ventilation",
            ),
        ),
    ]
