# Generated by Django 5.0.8 on 2026-04-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0051_oo_remove_fk_pression"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enjeu",
            options={
                "ordering": ["id_enjeu"],
                "verbose_name": "Enjeu / FCR",
                "verbose_name_plural": "Enjeux / FCR",
            },
        ),
        migrations.AlterModelOptions(
            name="indicateur",
            options={
                "ordering": ["id_indicateur"],
                "verbose_name": "Indicateur",
                "verbose_name_plural": "Indicateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="metrique",
            options={
                "ordering": ["id_metrique"],
                "verbose_name": "Métrique",
                "verbose_name_plural": "Métriques",
            },
        ),
        migrations.AlterModelOptions(
            name="niveauexigence",
            options={
                "ordering": ["id_ne"],
                "verbose_name": "Niveau d'exigence",
                "verbose_name_plural": "Niveaux d'exigence",
            },
        ),
        migrations.AlterModelOptions(
            name="objectiflongterme",
            options={
                "ordering": ["id_olt"],
                "verbose_name": "Objectif à long terme",
                "verbose_name_plural": "Objectifs à long terme",
            },
        ),
        migrations.AlterModelOptions(
            name="objectifoperationnel",
            options={
                "ordering": ["id_oo"],
                "verbose_name": "Objectif opérationnel",
                "verbose_name_plural": "Objectifs opérationnels",
            },
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["id_operation"],
                "verbose_name": "Opération",
                "verbose_name_plural": "Opérations",
            },
        ),
        migrations.AlterModelOptions(
            name="resultatattendu",
            options={
                "ordering": ["id_ra"],
                "verbose_name": "Résultat attendu",
                "verbose_name_plural": "Résultats attendus",
            },
        ),
        migrations.AlterField(
            model_name="coroopression",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
