# Generated by Django 5.0.8 on 2026-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0052_alter_enjeu_options_alter_indicateur_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocole",
            name="periode_suivi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mois de suivi (mnémoniques nomenclature PERIODE_SUIVI séparés par virgule, ex: 'JANVIER,FEVRIER,MARS')",
                max_length=200,
                verbose_name="Période de suivi",
            ),
        ),
    ]
