# Generated by Django 5.0.8 on 2026-05-07 14:41

from django.db import migrations, models


def backfill_socio_economique(apps, schema_editor):
    """
    Pour les enjeux existants où categorie_ecologique=False (= socio-éco
    dans l'ancien modèle ternaire), bascule categorie_socio_economique=True
    pour préserver leur classification.
    """
    Enjeu = apps.get_model("plans", "Enjeu")
    Enjeu.objects.filter(categorie_ecologique=False).update(
        categorie_socio_economique=True
    )


def reverse_noop(apps, schema_editor):
    """Pas de rollback nécessaire — la suppression du champ supprime déjà la donnée."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0053_alter_protocole_periode_suivi"),
    ]

    operations = [
        migrations.AddField(
            model_name="enjeu",
            name="categorie_socio_economique",
            field=models.BooleanField(
                default=False,
                help_text="True si l'enjeu relève de la dimension socio-économique",
                verbose_name="Catégorie socio-économique",
            ),
        ),
        migrations.AlterField(
            model_name="enjeu",
            name="categorie_ecologique",
            field=models.BooleanField(
                default=True,
                help_text="True si l'enjeu relève de la dimension écologique",
                null=True,
                verbose_name="Catégorie écologique",
            ),
        ),
        migrations.RunPython(backfill_socio_economique, reverse_noop),
    ]
