# Generated by Django 5.0.8 on 2026-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0054_enjeu_categorie_socio_economique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enjeu",
            name="autre_ecologique",
            field=models.BooleanField(
                default=False,
                help_text="Enjeu de conservation du patrimoine naturel de type autre",
                verbose_name="Autre (conservation du patrimoine naturel)",
            ),
        ),
        migrations.AlterField(
            model_name="enjeu",
            name="autre_ecologique_precision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Précision sur le type 'Autre' conservation du patrimoine naturel",
                max_length=255,
                verbose_name="Précision autre (conservation du patrimoine naturel)",
            ),
        ),
        migrations.AlterField(
            model_name="enjeu",
            name="categorie_ecologique",
            field=models.BooleanField(
                default=True,
                help_text="True si l'enjeu relève de la conservation du patrimoine naturel",
                null=True,
                verbose_name="Catégorie conservation du patrimoine naturel",
            ),
        ),
    ]
