# Generated by Django 5.0.8 on 2026-05-11 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0055_rename_categorie_ecologique_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangestion",
            name="annees_extension",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nombre d'années ajoutées au plan (statut 'étendu'). 0, 1 ou 2.",
                validators=[django.core.validators.MaxValueValidator(2)],
                verbose_name="Années d'extension",
            ),
        ),
        migrations.AlterField(
            model_name="plangestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("valide", "Validé"),
                    ("etendu", "Étendu"),
                    ("archive", "Archivé"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
