# Generated by Django 5.0.8 on 2026-05-11 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0056_plan_extension_etendu"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetriqueIntervalleExtra",
            fields=[
                (
                    "id_intervalle_extra",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "score_level",
                    models.PositiveSmallIntegerField(
                        help_text="Palier auquel l'intervalle est rattaché (1=TM, 2=Mauv, 3=Moy, 4=Bon, 5=TB)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Niveau de score",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Ordre de cet extra parmi les intervalles complémentaires du même palier (1=premier extra)",
                        verbose_name="Position",
                    ),
                ),
                (
                    "inf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Borne inférieure",
                    ),
                ),
                (
                    "sup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Borne supérieure",
                    ),
                ),
                (
                    "inf_inclusive",
                    models.BooleanField(
                        default=True,
                        help_text="True: x ≥ inf, False: x > inf",
                        verbose_name="Borne inf inclusive",
                    ),
                ),
                (
                    "sup_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="True: x ≤ sup, False: x < sup",
                        verbose_name="Borne sup inclusive",
                    ),
                ),
                (
                    "logical_op",
                    models.CharField(
                        choices=[("OR", "OU"), ("AND", "ET")],
                        default="OR",
                        help_text="Comment combiner cet intervalle avec l'intervalle qui précède (principal ou extra précédent)",
                        max_length=4,
                        verbose_name="Opérateur logique",
                    ),
                ),
                (
                    "id_metrique",
                    models.ForeignKey(
                        db_column="id_metrique",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervalles_extra",
                        to="plans.metrique",
                        verbose_name="Métrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervalle complémentaire",
                "verbose_name_plural": "Intervalles complémentaires",
                "db_table": '"general"."t_metrique_intervalles_extra"',
                "db_table_comment": "Intervalles complémentaires des métriques numériques (#247)",
                "ordering": ["id_metrique", "score_level", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="metriqueintervalleextra",
            constraint=models.UniqueConstraint(
                fields=("id_metrique", "score_level", "position"),
                name="uniq_metrique_intervalle_extra_position",
            ),
        ),
    ]
