# Generated by Django 5.0.8 on 2026-05-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0057_add_metrique_intervalles_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetriqueScoreBlock",
            fields=[
                ("id_score_block", models.AutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Ordre du bloc complémentaire (1=premier après le principal)",
                        verbose_name="Position",
                    ),
                ),
                (
                    "logical_op",
                    models.CharField(
                        choices=[("OR", "OU"), ("AND", "ET")],
                        default="OR",
                        help_text="Comment combiner ce bloc avec le bloc qui précède (principal ou complémentaire précédent)",
                        max_length=4,
                        verbose_name="Opérateur logique",
                    ),
                ),
                (
                    "group_open",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nombre de '(' à ouvrir avant ce bloc (gestion de la précédence ET/OU)",
                        verbose_name="Parenthèses ouvrantes",
                    ),
                ),
                (
                    "group_close",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nombre de ')' à fermer après ce bloc",
                        verbose_name="Parenthèses fermantes",
                    ),
                ),
                (
                    "sens_variation",
                    models.CharField(
                        choices=[
                            ("CROISSANT", "Croissant"),
                            ("DECROISSANT", "Décroissant"),
                        ],
                        default="CROISSANT",
                        max_length=20,
                        verbose_name="Sens de variation",
                    ),
                ),
                (
                    "score_1_inf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_1_sup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_2_inf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_2_sup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_3_inf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_3_sup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_4_inf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_4_sup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_5_inf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "score_5_sup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("score_1_sup_inclusive", models.BooleanField(default=True)),
                ("score_2_sup_inclusive", models.BooleanField(default=True)),
                ("score_3_sup_inclusive", models.BooleanField(default=True)),
                ("score_4_sup_inclusive", models.BooleanField(default=True)),
                ("has_borne_score1", models.BooleanField(default=False)),
                ("has_borne_score5", models.BooleanField(default=False)),
                (
                    "id_metrique",
                    models.ForeignKey(
                        db_column="id_metrique",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_blocks",
                        to="plans.metrique",
                        verbose_name="Métrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloc de scoring complémentaire",
                "verbose_name_plural": "Blocs de scoring complémentaires",
                "db_table": '"general"."t_metrique_score_blocks"',
                "db_table_comment": "Blocs de scoring complémentaires des métriques numériques (#247)",
                "ordering": ["id_metrique", "position"],
            },
        ),
        migrations.DeleteModel(
            name="MetriqueIntervalleExtra",
        ),
        migrations.AddConstraint(
            model_name="metriquescoreblock",
            constraint=models.UniqueConstraint(
                fields=("id_metrique", "position"),
                name="uniq_metrique_score_block_position",
            ),
        ),
    ]
