# Generated by Django 5.0.8 on 2026-05-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0058_switch_to_metrique_score_blocks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metrique",
            options={
                "ordering": ["ordre", "id_metrique"],
                "verbose_name": "Métrique",
                "verbose_name_plural": "Métriques",
            },
        ),
        migrations.AddField(
            model_name="metrique",
            name="ordre",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordre d'affichage parmi les métriques d'un indicateur (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
    ]
