# Generated by Django 5.0.8 on 2026-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0059_add_metrique_ordre"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrique",
            name="inactive_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste d'entiers 1..5 marquant les paliers non utilisés.",
                verbose_name="Niveaux inactifs",
            ),
        ),
        migrations.AddField(
            model_name="metriquescoreblock",
            name="inactive_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste d'entiers 1..5 marquant les paliers non utilisés.",
                verbose_name="Niveaux inactifs",
            ),
        ),
    ]
