# Generated by Django 5.0.8 on 2026-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0060_add_metrique_inactive_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrique",
            name="group_close",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nombre de ')' à fermer après le bloc principal.",
                verbose_name="Parenthèses fermantes",
            ),
        ),
        migrations.AddField(
            model_name="metrique",
            name="group_open",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Nombre de '(' à ouvrir avant le bloc principal.",
                verbose_name="Parenthèses ouvrantes",
            ),
        ),
    ]
