# Generated by Django 5.0.8 on 2026-05-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0061_add_metrique_principal_group_parens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enjeu",
            options={
                "ordering": ["ordre", "id_enjeu"],
                "verbose_name": "Enjeu / FCR",
                "verbose_name_plural": "Enjeux / FCR",
            },
        ),
        migrations.AlterModelOptions(
            name="facteurinfluence",
            options={
                "ordering": ["ordre", "id_facteur_influence"],
                "verbose_name": "Facteur d'influence",
                "verbose_name_plural": "Facteurs d'influence",
            },
        ),
        migrations.AlterModelOptions(
            name="indicateur",
            options={
                "ordering": ["ordre", "id_indicateur"],
                "verbose_name": "Indicateur",
                "verbose_name_plural": "Indicateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="niveauexigence",
            options={
                "ordering": ["ordre", "id_ne"],
                "verbose_name": "Niveau d'exigence",
                "verbose_name_plural": "Niveaux d'exigence",
            },
        ),
        migrations.AlterModelOptions(
            name="objectiflongterme",
            options={
                "ordering": ["ordre", "id_olt"],
                "verbose_name": "Objectif à long terme",
                "verbose_name_plural": "Objectifs à long terme",
            },
        ),
        migrations.AlterModelOptions(
            name="objectifoperationnel",
            options={
                "ordering": ["ordre", "id_oo"],
                "verbose_name": "Objectif opérationnel",
                "verbose_name_plural": "Objectifs opérationnels",
            },
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["ordre", "id_operation"],
                "verbose_name": "Opération",
                "verbose_name_plural": "Opérations",
            },
        ),
        migrations.AlterModelOptions(
            name="pression",
            options={
                "ordering": ["ordre", "id_pression"],
                "verbose_name": "Pression",
                "verbose_name_plural": "Pressions",
            },
        ),
        migrations.AlterModelOptions(
            name="resultatattendu",
            options={
                "ordering": ["ordre", "id_ra"],
                "verbose_name": "Résultat attendu",
                "verbose_name_plural": "Résultats attendus",
            },
        ),
        migrations.AddField(
            model_name="enjeu",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="facteurinfluence",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="indicateur",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="niveauexigence",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="objectiflongterme",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="objectifoperationnel",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les opérations d'une métrique (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="pression",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="resultatattendu",
            name="ordre",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Ordre d'affichage parmi les éléments d'un même parent (0 = haut)",
                verbose_name="Ordre",
            ),
        ),
    ]
