# Generated by Django 5.0.8 on 2026-05-12 07:39

import django.db.models.deletion
from django.db import migrations, models


def insert_categorie_action_reserve(apps, schema_editor):
    """
    Insère le type de nomenclature `CATEGORIE_ACTION_RESERVE` (id_type=66)
    + les 9 entrées de domaines d'activité réserve CT88 (codes 2 lettres).
    Idempotent via ON CONFLICT.
    """
    from django.db import connection
    with connection.cursor() as cur:
        cur.execute(
            """
            INSERT INTO ref_nomenclatures.bib_nomenclatures_types
                (id_type, mnemonique, label, definition, source, statut, date_ajout, date_maj)
            VALUES (66, 'CATEGORIE_ACTION_RESERVE',
                    'Catégorie d''action réserve',
                    'DOMAINES D''ACTIVITÉ réserve CT88',
                    'CICADA/CT88', 'Validé', NOW(), NOW())
            ON CONFLICT (id_type) DO UPDATE SET
                mnemonique = EXCLUDED.mnemonique,
                label = EXCLUDED.label,
                definition = EXCLUDED.definition;
            """
        )
        entries = [
            (1400, 'SP', "Surveillance du territoire et police de l'environnement", '1'),
            (1401, 'CS', "Connaissance et suivi continu du patrimoine naturel", '2'),
            (1402, 'EI', "Prestations de conseil, études et ingénierie", '3'),
            (1403, 'IP', "Interventions sur le patrimoine naturel", '4'),
            (1404, 'CI', "Création et maintenance d'infrastructures d'accueil", '5'),
            (1405, 'MS', "Management et Soutien", '6'),
            (1406, 'PR', "Participation à la recherche", '7'),
            (1407, 'PA', "Prestations d'accueil et d'animation", '8'),
            (1408, 'CC', "Création de supports de communication et de pédagogie", '9'),
        ]
        for id_n, code, label, hierarchy in entries:
            cur.execute(
                """
                INSERT INTO ref_nomenclatures.t_nomenclatures
                    (id_nomenclature, id_type, cd_nomenclature, mnemonique,
                     label, definition, source, statut, hierarchy,
                     date_ajout, date_maj, actif)
                VALUES (%s, 66, %s, %s, %s, %s,
                        'CICADA/CT88', 'Validé', %s, NOW(), NOW(), true)
                ON CONFLICT (id_nomenclature) DO UPDATE SET
                    cd_nomenclature = EXCLUDED.cd_nomenclature,
                    mnemonique = EXCLUDED.mnemonique,
                    label = EXCLUDED.label,
                    definition = EXCLUDED.definition,
                    hierarchy = EXCLUDED.hierarchy,
                    actif = true;
                """,
                [id_n, code, code, label, label, hierarchy],
            )


def remove_categorie_action_reserve(apps, schema_editor):
    """Reverse : on retire les nomenclatures et le type."""
    from django.db import connection
    with connection.cursor() as cur:
        cur.execute("DELETE FROM ref_nomenclatures.t_nomenclatures WHERE id_type = 66;")
        cur.execute("DELETE FROM ref_nomenclatures.bib_nomenclatures_types WHERE id_type = 66;")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0062_add_ordre_field_dnd"),
    ]

    operations = [
        migrations.RunPython(
            insert_categorie_action_reserve,
            reverse_code=remove_categorie_action_reserve,
        ),
        migrations.AddField(
            model_name="operation",
            name="id_categorie_action_reserve",
            field=models.ForeignKey(
                blank=True,
                db_column="id_categorie_action_reserve",
                help_text="DOMAINES D'ACTIVITÉ réserve CT88",
                limit_choices_to={"id_type__mnemonique": "CATEGORIE_ACTION_RESERVE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_categorie_reserve",
                to="core.nomenclature",
                verbose_name="Catégorie d'action réserve",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="id_type_action",
            field=models.ForeignKey(
                blank=True,
                db_column="id_type_action",
                help_text="Type d'action (IP1, CS2, CI2, SP1, etc.). On utilise le référentiel d'Eden 62 en attendant l'élaboration du nouveau référentiel Gestref.",
                limit_choices_to={"id_type__mnemonique": "TYPE_ACTION"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_type_action",
                to="core.nomenclature",
                verbose_name="Type d'action",
            ),
        ),
    ]
