# Generated by Django 5.0.8 on 2026-05-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0067_add_modifie_mi_parcours_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="statut",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("valide", "Validé")],
                db_index=True,
                default="draft",
                help_text="Brouillon tant que l'action n'a pas été validée explicitement",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
