# Generated by Django 5.0.8 on 2026-05-26 09:45
"""
Refactor #277 — Extraction du workflow CSRPN dans `validation_step`.

Les anciens statuts `avis_csrpn`, `comite_consultatif`, `arrete_pref` deviennent
des valeurs de l'attribut orthogonal `validation_step`. Le plan reste à
`statut='draft'` durant le workflow CSRPN.

Ordre des opérations :
1. Ajout du champ `validation_step` (nullable).
2. RunPython : pour chaque plan dont `statut` ∈ {avis_csrpn, comite_consultatif,
   arrete_pref} → `validation_step = statut`, `statut = 'draft'`.
3. AlterField sur `statut` → réduction des choices à {draft, valide, modifie, archive}.
"""

from django.db import migrations, models


_CSRPN_STEPS = ('avis_csrpn', 'comite_consultatif', 'arrete_pref')


def migrate_csrpn_to_validation_step(apps, schema_editor):
    PlanGestion = apps.get_model('plans', 'PlanGestion')
    PlanGestion.objects.filter(statut__in=_CSRPN_STEPS).update(
        validation_step=models.F('statut'),
        statut='draft',
    )


def revert_validation_step_to_statut(apps, schema_editor):
    PlanGestion = apps.get_model('plans', 'PlanGestion')
    for step in _CSRPN_STEPS:
        PlanGestion.objects.filter(validation_step=step).update(
            statut=step,
            validation_step=None,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0074_renumber_versions_per_rang"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangestion",
            name="validation_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("avis_csrpn", "Avis CSRPN demandé"),
                    ("comite_consultatif", "Validation comité consultatif"),
                    ("arrete_pref", "Arrêté préfectoral"),
                ],
                help_text="Étape du workflow CSRPN en cours (avis CSRPN, comité consultatif, arrêté préfectoral).",
                max_length=30,
                null=True,
                verbose_name="Étape de validation CSRPN",
            ),
        ),
        migrations.RunPython(
            migrate_csrpn_to_validation_step,
            reverse_code=revert_validation_step_to_statut,
        ),
        migrations.AlterField(
            model_name="plangestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("valide", "Validé"),
                    ("modifie", "Modifié"),
                    ("archive", "Archivé"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
