# Generated by Django 5.0.8 on 2026-05-27 12:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0075_plangestion_validation_step_alter_plangestion_statut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RealisationOperationAnnee",
            fields=[
                (
                    "id_realisation_operation_annee",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "periodicite_realisee",
                    models.BooleanField(
                        default=False, verbose_name="Périodicité réalisée"
                    ),
                ),
                (
                    "periodicite_mensuelle_realisee",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Format: {"1": true, "2": false, ..., "12": true}',
                        verbose_name="Périodicité mensuelle réalisée",
                    ),
                ),
                (
                    "commentaires",
                    models.TextField(
                        blank=True, null=True, verbose_name="Détails / commentaires"
                    ),
                ),
                (
                    "geom_realisee",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Emprise spatiale réalisée",
                    ),
                ),
                (
                    "budget_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Utilisé quand ventilation_mode = 'none'",
                        max_digits=12,
                        null=True,
                        verbose_name="Budget réalisé (€)",
                    ),
                ),
                (
                    "budget_fonctionnement_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Utilisé quand ventilation_mode = 'by_type' (sans organisme)",
                        max_digits=12,
                        null=True,
                        verbose_name="Budget fonctionnement réalisé (€)",
                    ),
                ),
                (
                    "budget_investissement_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Utilisé quand ventilation_mode = 'by_type' (sans organisme)",
                        max_digits=12,
                        null=True,
                        verbose_name="Budget investissement réalisé (€)",
                    ),
                ),
                (
                    "etp_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Utilisé quand ventilation_mode ne porte pas sur les organismes",
                        max_digits=8,
                        null=True,
                        verbose_name="Travail réalisé (jours)",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_niveau_realisation",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_niveau_realisation",
                        limit_choices_to={"id_type__mnemonique": "NIVEAU_REALISATION"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="realisations_niveau",
                        to="core.nomenclature",
                        verbose_name="Niveau de réalisation",
                    ),
                ),
                (
                    "id_operation_annee",
                    models.OneToOneField(
                        db_column="id_operation_annee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realisation",
                        to="plans.operationannee",
                        verbose_name="Année d'opération",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réalisation annuelle d'opération",
                "verbose_name_plural": "Réalisations annuelles d'opération",
                "db_table": '"general"."t_realisation_operation_annees"',
                "db_table_comment": "Suivi de réalisation annuel d'une opération",
                "ordering": ["id_operation_annee__annee"],
            },
        ),
        migrations.CreateModel(
            name="RealisationOperationAnneeOrganisme",
            fields=[
                (
                    "id_realisation_op_annee_organisme",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "budget_fonctionnement_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget fonctionnement réalisé (€)",
                    ),
                ),
                (
                    "budget_investissement_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget investissement réalisé (€)",
                    ),
                ),
                (
                    "etp_realise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Travail réalisé (jours)",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_operation_annee_organisme",
                    models.OneToOneField(
                        db_column="id_operation_annee_organisme",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realisation",
                        to="plans.operationanneeorganisme",
                        verbose_name="Organisme - Année d'opération",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réalisation par organisme - Année d'opération",
                "verbose_name_plural": "Réalisations par organisme - Années d'opération",
                "db_table": '"general"."t_realisation_operation_annee_organismes"',
                "db_table_comment": "Ventilation par organisme du suivi de réalisation annuel",
            },
        ),
    ]
