# Generated by Django 5.0.8 on 2026-05-28 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0076_realisationoperationannee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicateurMesure",
            fields=[
                (
                    "id_indicateur_mesure",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "score_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Score 1-5 saisi manuellement, écrase le calcul automatique.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Score saisi manuellement",
                    ),
                ),
                (
                    "commentaire_override",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Raisons de la saisie manuelle",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_mesures",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesure d'indicateur",
                "verbose_name_plural": "Mesures d'indicateurs",
                "db_table": '"general"."t_indicateur_mesures"',
                "db_table_comment": "Saisie annuelle au niveau indicateur (override manuel du score)",
                "ordering": ["-annee"],
                "unique_together": {("id_indicateur", "annee")},
            },
        ),
    ]
