# Generated by Django 5.0.8 on 2026-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0077_indicateurmesure"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviinventaire",
            name="habitats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste d'habitats HabRef : [{cd_hab, lb_hab_fr}, ...]",
                verbose_name="Habitats (structurés)",
            ),
        ),
        migrations.AlterField(
            model_name="suiviinventaire",
            name="habitat_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Référentiel habitat associé (noms, conservé pour l'affichage hérité)",
                max_length=500,
                verbose_name="Référentiel habitat",
            ),
        ),
    ]
