# Generated by Django 5.0.8 on 2026-06-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0079_add_categorie_fcr_surveillance"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="id_indicateur",
            field=models.ForeignKey(
                blank=True,
                db_column="id_indicateur",
                help_text="Indicateur (état ou pression) auquel l'action est rattachée, sans passer par une métrique",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="plans.indicateur",
                verbose_name="Indicateur",
            ),
        ),
    ]
