# Generated by Django 5.0.8 on 2026-06-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0080_operation_id_indicateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectifoperationnel",
            name="id_enjeu",
            field=models.ForeignKey(
                blank=True,
                db_column="id_enjeu",
                help_text="Rattachement direct à un enjeu/FCR sans passer par une pression (#337)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectifs_operationnels_directs",
                to="plans.enjeu",
                verbose_name="Enjeu (rattachement direct)",
            ),
        ),
    ]
