# Generated by Django 5.0.8 on 2026-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0081_objectifoperationnel_id_enjeu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corenjeuhabitat",
            name="cd_hab",
            field=models.CharField(
                blank=True,
                help_text="Identifiant HabRef de l'habitat (vide pour un habitat saisi librement, #368)",
                max_length=50,
                null=True,
                verbose_name="cd_hab",
            ),
        ),
    ]
