# Generated by Django 5.0.8 on 2026-06-17 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_homepage_image_position"),
        ("plans", "0082_alter_corenjeuhabitat_cd_hab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationRealisationGlobale",
            fields=[
                (
                    "id_operation_realisation_globale",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "commentaire_override",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaire de surcharge"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_niveau_realisation",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_niveau_realisation",
                        limit_choices_to={"id_type__mnemonique": "NIVEAU_REALISATION"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="realisations_globales_niveau",
                        to="core.nomenclature",
                        verbose_name="Niveau de réalisation global (surcharge)",
                    ),
                ),
                (
                    "id_operation",
                    models.OneToOneField(
                        db_column="id_operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realisation_globale",
                        to="plans.operation",
                        verbose_name="Opération",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réalisation globale d'opération",
                "verbose_name_plural": "Réalisations globales d'opération",
                "db_table": '"general"."t_operation_realisation_globale"',
                "db_table_comment": "Surcharge manuelle du niveau de réalisation global d'une action (#355)",
            },
        ),
    ]
