# Generated by Django 5.0.8 on 2026-06-18 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0083_operationrealisationglobale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicateurRealisationGlobale",
            fields=[
                (
                    "id_indicateur_realisation_globale",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "score_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Icône d'évaluation attribuée manuellement (5=++, 1=−−), prime sur le calcul automatique pour l'affichage.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Évaluation forcée (score 1-5)",
                    ),
                ),
                (
                    "commentaire_override",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaire global"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_indicateur",
                    models.OneToOneField(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realisation_globale",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
                (
                    "id_utilisateur_maj",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_maj",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernier modificateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation globale d'indicateur",
                "verbose_name_plural": "Évaluations globales d'indicateur",
                "db_table": '"general"."t_indicateur_realisation_globale"',
                "db_table_comment": "Surcharge manuelle de l'évaluation globale d'un indicateur (#356)",
            },
        ),
    ]
