# Generated by Django 5.0.8 on 2026-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0084_indicateurrealisationglobale"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrique",
            name="bloc_intitule",
            field=models.CharField(
                blank=True,
                help_text="Intitulé du bloc principal quand la métrique combine plusieurs blocs (ex: hauteur)",
                max_length=500,
                null=True,
                verbose_name="Intitulé du bloc principal",
            ),
        ),
        migrations.AddField(
            model_name="metriquescoreblock",
            name="intitule",
            field=models.CharField(
                blank=True,
                help_text="Intitulé du bloc (ex: recouvrement)",
                max_length=500,
                null=True,
                verbose_name="Intitulé",
            ),
        ),
        migrations.AddField(
            model_name="metriquescoreblock",
            name="unite",
            field=models.CharField(
                blank=True,
                help_text="Unité de mesure du bloc (optionnelle, ex: %, m)",
                max_length=100,
                null=True,
                verbose_name="Unité",
            ),
        ),
    ]
