# Generated by Django 5.0.8 on 2026-06-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0085_metrique_bloc_intitule_metriquescoreblock_intitule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enjeu",
            name="geo_autre",
            field=models.BooleanField(
                default=False,
                help_text="Patrimoine géologique de type autre",
                verbose_name="Patrimoine géologique - autre",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="geo_autre_precision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Précision sur le patrimoine géologique de type 'Autre'",
                max_length=255,
                verbose_name="Précision patrimoine géologique - autre",
            ),
        ),
        migrations.AddField(
            model_name="enjeu",
            name="geo_documents",
            field=models.BooleanField(
                default=False,
                help_text="Patrimoine géologique de type documentaire (archives numériques ou papier)",
                verbose_name="Patrimoine géologique - documents",
            ),
        ),
        migrations.CreateModel(
            name="CorEnjeuObjetGeologique",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Code de l'objet géologique dans la typologie",
                        max_length=50,
                        verbose_name="Code",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Libellé"
                    ),
                ),
                (
                    "precision",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Précision"
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objets_geologiques",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enjeu - Objet géologique",
                "verbose_name_plural": "Enjeux - Objets géologiques",
                "db_table": '"general"."cor_enjeu_objet_geologique"',
                "db_table_comment": "Liaison enjeux - objets géologiques (#237)",
                "unique_together": {("id_enjeu", "code")},
            },
        ),
    ]
