# Generated by Django 5.0.8 on 2026-06-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0086_enjeu_geo_autre_enjeu_geo_autre_precision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorEnjeuFichier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "support",
                    models.CharField(
                        choices=[("numerique", "Numérique"), ("papier", "Papier")],
                        default="numerique",
                        max_length=10,
                        verbose_name="Support",
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nom du fichier",
                    ),
                ),
                (
                    "chemin_fichier",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Chemin du fichier",
                    ),
                ),
                (
                    "taille_fichier",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (bytes)"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Extension"
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titre du document numérique ou référence du document papier",
                        max_length=255,
                        verbose_name="Titre / référence",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "ordre_affichage",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichiers",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
                (
                    "id_utilisateur_upload",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_utilisateur_upload",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur ayant ajouté",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enjeu - Document",
                "verbose_name_plural": "Enjeux - Documents",
                "db_table": '"fichiers"."t_enjeu_fichiers"',
                "db_table_comment": "Documents rattachés aux enjeux géologiques (#237)",
                "ordering": ["ordre_affichage", "nom_fichier"],
            },
        ),
    ]
