# Generated by Django 5.0.8 on 2026-06-23 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0088_corenjeuobjetgeologique_nomenclature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enjeu",
            name="rang",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Priorité de l'enjeu (1=haute, 2=moyenne, 3=basse). Null = priorité non définie (#441).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Priorité",
            ),
        ),
    ]
