# Generated by Django 5.0.8 on 2026-06-30 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0090_metrique_format_metrique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicateurmesure",
            name="score_override",
            field=models.IntegerField(
                blank=True,
                help_text="Score saisi manuellement, écrase le calcul automatique : 1-5, ou 0 pour forcer l'état « indéterminé » (sans donnée). #519",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Score saisi manuellement",
            ),
        ),
    ]
