# Generated by Django 5.0.8 on 2026-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0091_alter_indicateurmesure_score_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesure",
            name="valeurs_blocs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Valeurs des blocs complémentaires, indexées par position de bloc.",
                verbose_name="Valeurs par bloc",
            ),
        ),
        migrations.AlterField(
            model_name="mesure",
            name="valeur",
            field=models.CharField(
                help_text="Valeur de la mesure (numérique ou qualitative). Pour une métrique multi-blocs, valeur du bloc principal.",
                max_length=500,
                verbose_name="Valeur",
            ),
        ),
    ]
