# Generated by Django 5.0.8 on 2026-07-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0096_operation_numero_manuel"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrique",
            name="score_5_sup_inclusive",
            field=models.BooleanField(
                default=True,
                help_text="Utilisé en sens décroissant (frontière très bon / bon).",
                verbose_name="Borne sup score 5 inclusive",
            ),
        ),
        migrations.AddField(
            model_name="metriquescoreblock",
            name="score_5_sup_inclusive",
            field=models.BooleanField(default=True),
        ),
    ]
