# Generated by Django 5.0.8 on 2026-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0097_metrique_score_5_sup_inclusive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realisationoperationannee",
            name="financeurs_realises",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Financeur(s) et type de financement réellement mobilisés cette année",
                verbose_name="Financeur(s) réalisé(s)",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationannee",
            name="operateurs_realises",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Opérateur(s) ayant réellement conduit l'action cette année",
                verbose_name="Opérateur(s) réalisé(s)",
            ),
        ),
    ]
