# Generated by Django 5.0.8 on 2026-07-13 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0098_realisationoperationannee_financeurs_realises_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fonction",
            fields=[
                ("id_fonction", models.AutoField(primary_key=True, serialize=False)),
                (
                    "libelle",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Libellé"
                    ),
                ),
                (
                    "finance_par_defaut",
                    models.BooleanField(
                        default=True,
                        help_text="Valeur par défaut du caractère financé pour cette fonction (surchargeable à chaque saisie de temps)",
                        verbose_name="Financé par défaut",
                    ),
                ),
                (
                    "is_socle",
                    models.BooleanField(
                        default=False,
                        help_text="Fonction issue du socle de référence (protégée en suppression)",
                        verbose_name="Fonction du socle",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonction",
                "verbose_name_plural": "Fonctions",
                "db_table": '"general"."t_fonctions"',
                "db_table_comment": "Référentiel global des fonctions/postes (#560)",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="PersonnePlan",
            fields=[
                (
                    "id_personne_plan",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "date_arrivee",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'arrivée"
                    ),
                ),
                (
                    "date_depart",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de départ"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_pg",
                    models.ForeignKey(
                        db_column="id_pg",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnes",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
                (
                    "id_role",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_role",
                        help_text="Compte CICADA associé quand la personne en possède un",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personnes_plan",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personne du plan",
                "verbose_name_plural": "Personnes du plan",
                "db_table": '"general"."t_personnes_plan"',
                "db_table_comment": "Personnes rattachées à un plan de gestion (#560)",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="OperationAnneeRH",
            fields=[
                (
                    "id_operation_annee_rh",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "jours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Nombre de jours",
                    ),
                ),
                ("finance", models.BooleanField(default=True, verbose_name="Financé")),
                (
                    "id_fonction",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_fonction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_lignes_prev",
                        to="plans.fonction",
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "id_operation_annee",
                    models.ForeignKey(
                        db_column="id_operation_annee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_lignes",
                        to="plans.operationannee",
                        verbose_name="Année d'opération",
                    ),
                ),
                (
                    "id_personne_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_personne_plan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_lignes_prev",
                        to="plans.personneplan",
                        verbose_name="Personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne RH prévisionnelle",
                "verbose_name_plural": "Lignes RH prévisionnelles",
                "db_table": '"general"."t_operation_annee_rh"',
                "db_table_comment": "Lignes RH prévisionnelles par année d'opération (#560)",
                "ordering": ["id_operation_annee_rh"],
            },
        ),
        migrations.CreateModel(
            name="RealisationOperationAnneeRH",
            fields=[
                (
                    "id_realisation_operation_annee_rh",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "jours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Nombre de jours réalisés",
                    ),
                ),
                ("finance", models.BooleanField(default=True, verbose_name="Financé")),
                (
                    "id_fonction",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_fonction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_lignes_reel",
                        to="plans.fonction",
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "id_personne_plan",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_personne_plan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_lignes_reel",
                        to="plans.personneplan",
                        verbose_name="Personne",
                    ),
                ),
                (
                    "id_realisation_operation_annee",
                    models.ForeignKey(
                        db_column="id_realisation_operation_annee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_lignes",
                        to="plans.realisationoperationannee",
                        verbose_name="Réalisation annuelle d'opération",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne RH réalisée",
                "verbose_name_plural": "Lignes RH réalisées",
                "db_table": '"general"."t_realisation_operation_annee_rh"',
                "db_table_comment": "Lignes RH réalisées par année d'opération (#560)",
                "ordering": ["id_realisation_operation_annee_rh"],
            },
        ),
        migrations.CreateModel(
            name="PersonneFonction",
            fields=[
                (
                    "id_personne_fonction",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Part de temps sur cette fonction (0 à 100), facultative",
                        max_digits=5,
                        null=True,
                        verbose_name="Quotité (%)",
                    ),
                ),
                (
                    "id_fonction",
                    models.ForeignKey(
                        db_column="id_fonction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnes",
                        to="plans.fonction",
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "id_personne_plan",
                    models.ForeignKey(
                        db_column="id_personne_plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fonctions",
                        to="plans.personneplan",
                        verbose_name="Personne du plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonction d'une personne",
                "verbose_name_plural": "Fonctions d'une personne",
                "db_table": '"general"."cor_personne_fonction"',
                "db_table_comment": "Fonctions occupées par une personne du PG (#560)",
                "ordering": ["id_fonction__libelle"],
                "unique_together": {("id_personne_plan", "id_fonction")},
            },
        ),
    ]
