# Generated by Django 5.0.8 on 2026-07-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0101_facteur_influence_partage_enjeux"),
    ]

    operations = [
        migrations.AddField(
            model_name="realisationoperationanneerh",
            name="id_operation_annee_rh",
            field=models.ForeignKey(
                blank=True,
                db_column="id_operation_annee_rh",
                help_text="Ligne RH prévisionnelle que cette saisie réalise. Conserve le lien prévu ↔ réel même quand la personne (ou la fonction) ayant réellement conduit l'action diffère de celle prévue. NULL pour un temps réalisé qui n'était pas prévu.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="realisations",
                to="plans.operationanneerh",
                verbose_name="Ligne prévisionnelle réalisée",
            ),
        ),
    ]
