"""
#560 — Les personnes d'un PG sont remplacées par des POSTES.

Motivation RGPD : on ne stocke plus aucune donnée nominative. Un poste décrit
un type d'emploi (via ses fonctions), en `nombre` exemplaires, pour une
enveloppe de `etp` ETP au total, rattaché à un organisme. Ni nom, ni dates
d'arrivée/départ, ni lien vers un compte utilisateur.

Les lignes RH ne ciblent plus (personne | fonction) mais (poste | organisme),
selon le nouveau mode d'affichage des actions (Operation.declinaison_par_poste).

/!\ Migration DESTRUCTIVE et volontairement SANS reprise des données :
PersonnePlan/PersonneFonction sont supprimees, et les lignes RH qui pointaient
sur une personne perdent leur cible (les jours, eux, sont conserves — elles
deviennent du « temps non affecte »). C'est assume : #560 n'a jamais ete livre
en production, ces donnees n'existent qu'en developpement et sont recreees par
`seed_testdata`. Convertir les personnes en postes n'aurait rien preserve
d'utile : le nom — seule information reellement portee — est precisement ce que
le RGPD impose d'abandonner.
"""
# Generated by Django 5.0.8 on 2026-07-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0103_backfill_lien_rh_prevu_reel"),
        ("users", "0010_change_redacteur_general_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personneplan",
            name="id_pg",
        ),
        migrations.RemoveField(
            model_name="personneplan",
            name="id_role",
        ),
        migrations.RemoveField(
            model_name="operationanneerh",
            name="id_personne_plan",
        ),
        migrations.RemoveField(
            model_name="realisationoperationanneerh",
            name="id_personne_plan",
        ),
        migrations.RemoveField(
            model_name="operationanneerh",
            name="id_fonction",
        ),
        migrations.RemoveField(
            model_name="realisationoperationanneerh",
            name="id_fonction",
        ),
        migrations.AddField(
            model_name="operation",
            name="declinaison_par_poste",
            field=models.BooleanField(
                default=False,
                help_text="Détaille le temps de travail poste par poste (#560). Sinon le temps est saisi par organisme quand le budget est ventilé par organisme, et reste facultatif autrement.",
                verbose_name="Déclinaison par poste",
            ),
        ),
        migrations.AddField(
            model_name="operationanneerh",
            name="id_organisme",
            field=models.ForeignKey(
                blank=True,
                db_column="id_organisme",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rh_lignes_prev",
                to="users.biborganismes",
                verbose_name="Organisme",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneerh",
            name="id_organisme",
            field=models.ForeignKey(
                blank=True,
                db_column="id_organisme",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rh_lignes_reel",
                to="users.biborganismes",
                verbose_name="Organisme",
            ),
        ),
        migrations.AlterField(
            model_name="realisationoperationanneerh",
            name="id_operation_annee_rh",
            field=models.ForeignKey(
                blank=True,
                db_column="id_operation_annee_rh",
                help_text="Ligne RH prévisionnelle que cette saisie réalise. Conserve le lien prévu ↔ réel même quand le poste (ou l'organisme) ayant réellement conduit l'action diffère de celui prévu. NULL pour un temps réalisé qui n'était pas prévu.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="realisations",
                to="plans.operationanneerh",
                verbose_name="Ligne prévisionnelle réalisée",
            ),
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                ("id_poste", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Combien de postes de ce type (ex. 3 stagiaires)",
                        verbose_name="Nombre de postes",
                    ),
                ),
                (
                    "etp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nombre d'ETP pour ce poste, TOTAL sur les `nombre` postes",
                        max_digits=6,
                        null=True,
                        verbose_name="ETP total",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id_organisme",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_organisme",
                        help_text="Organisme employeur / porteur du poste",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postes",
                        to="users.biborganismes",
                        verbose_name="Organisme",
                    ),
                ),
                (
                    "id_pg",
                    models.ForeignKey(
                        db_column="id_pg",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postes",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste du plan",
                "verbose_name_plural": "Postes du plan",
                "db_table": '"general"."t_postes"',
                "db_table_comment": "Postes d'un plan de gestion, sans nominatif (#560)",
                "ordering": ["id_poste"],
            },
        ),
        migrations.AddField(
            model_name="operationanneerh",
            name="id_poste",
            field=models.ForeignKey(
                blank=True,
                db_column="id_poste",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rh_lignes_prev",
                to="plans.poste",
                verbose_name="Poste",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneerh",
            name="id_poste",
            field=models.ForeignKey(
                blank=True,
                db_column="id_poste",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rh_lignes_reel",
                to="plans.poste",
                verbose_name="Poste",
            ),
        ),
        migrations.CreateModel(
            name="PosteFonction",
            fields=[
                (
                    "id_poste_fonction",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Part de temps sur cette fonction (0 à 100). Laisser vide pour un poste qui cumule les fonctions sur tout son temps.",
                        max_digits=5,
                        null=True,
                        verbose_name="Quotité (%)",
                    ),
                ),
                (
                    "id_fonction",
                    models.ForeignKey(
                        db_column="id_fonction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postes",
                        to="plans.fonction",
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "id_poste",
                    models.ForeignKey(
                        db_column="id_poste",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fonctions",
                        to="plans.poste",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonction d'un poste",
                "verbose_name_plural": "Fonctions d'un poste",
                "db_table": '"general"."cor_poste_fonction"',
                "db_table_comment": "Fonctions portées par un poste du PG (#560)",
                "ordering": ["id_fonction__libelle"],
                "unique_together": {("id_poste", "id_fonction")},
            },
        ),
        migrations.DeleteModel(
            name="PersonneFonction",
        ),
        migrations.DeleteModel(
            name="PersonnePlan",
        ),
    ]
