# Generated by Django 5.0.8 on 2026-07-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0104_postes_remplacent_personnes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorOoEnjeu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ordre d'affichage de l'OO parmi ceux de cet enjeu (0 = haut)",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "id_enjeu",
                    models.ForeignKey(
                        db_column="id_enjeu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_oos",
                        to="plans.enjeu",
                        verbose_name="Enjeu",
                    ),
                ),
                (
                    "id_oo",
                    models.ForeignKey(
                        db_column="id_oo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_enjeux",
                        to="plans.objectifoperationnel",
                        verbose_name="Objectif opérationnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre OO-Enjeu",
                "verbose_name_plural": "Ordres OO-Enjeu",
                "db_table": '"general"."cor_oo_enjeu"',
                "db_table_comment": "Ordre d'affichage des OO propre à chaque enjeu (#552)",
                "ordering": ["ordre", "id"],
                "unique_together": {("id_oo", "id_enjeu")},
            },
        ),
    ]
