# Generated by Django 5.0.8 on 2026-07-17 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0105_corooenjeu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CorIndicateurHabitat",
        ),
        migrations.DeleteModel(
            name="CorIndicateurTaxon",
        ),
    ]
