# Generated by Django 5.0.8 on 2026-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0105_corooenjeu"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangestion",
            name="import_ia_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de l'import IA"
            ),
        ),
        migrations.AddField(
            model_name="plangestion",
            name="import_ia_en_attente",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Plan pré-rempli par l'IA, en attente de relecture.",
                verbose_name="Import IA en attente de relecture",
            ),
        ),
    ]
