# Generated by Django 5.0.8 on 2026-07-20 12:23
# #252 — un suivi peut porter plusieurs protocoles : FK id_protocole → M2M protocoles

from django.db import migrations, models


def forwards_copy_protocoles(apps, schema_editor):
    """Reprend la FK existante dans la table de liaison (un suivi → liste à 1 élément)."""
    SuiviInventaire = apps.get_model("plans", "SuiviInventaire")
    for suivi in SuiviInventaire.objects.filter(id_protocole__isnull=False).iterator():
        suivi.protocoles.add(suivi.id_protocole_id)


def backwards_restore_fk(apps, schema_editor):
    """Restaure le premier protocole de la liste dans la FK (les autres sont perdus)."""
    SuiviInventaire = apps.get_model("plans", "SuiviInventaire")
    for suivi in SuiviInventaire.objects.prefetch_related("protocoles").iterator():
        premier = suivi.protocoles.first()
        if premier is not None:
            suivi.id_protocole_id = premier.pk
            suivi.save(update_fields=["id_protocole"])


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0106_alter_corindicateurtaxon_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviinventaire",
            name="protocoles",
            field=models.ManyToManyField(
                blank=True,
                db_table='"general"."cor_suivi_protocole"',
                help_text="Protocoles associés au suivi/inventaire",
                related_name="suivis",
                to="plans.protocole",
                verbose_name="Protocoles",
            ),
        ),
        migrations.RunPython(forwards_copy_protocoles, backwards_restore_fk),
        migrations.RemoveField(
            model_name="suiviinventaire",
            name="id_protocole",
        ),
    ]
