# Generated by Django 5.0.8 on 2026-07-20 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0107_suivi_protocoles_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesure",
            name="niveau",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Palier 1-5 explicitement sélectionné dans une grille Texte/Chiffre. Vide = le score est déduit de la valeur.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Niveau de grille choisi",
            ),
        ),
    ]
