# Generated by Django 5.0.8 on 2026-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0108_mesure_niveau"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plangestion",
            name="statut",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("valide", "Validé"),
                    ("modifie", "Modifié"),
                    ("archive", "Terminé"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
