# Generated by Django 5.0.8 on 2026-07-23 09:33

from django.db import migrations, models


def backfill_type_poste(apps, schema_editor):
    """Type les fonctions existantes d'après leur libellé (#596).

    Défaut = salarié (déjà posé par la valeur par défaut du champ). On ne
    reclasse que les cas évidents ; les gestionnaires ajusteront le reste.
    """
    Fonction = apps.get_model("plans", "Fonction")
    rules = [
        ("prestataire", ["prestataire", "presta"]),
        ("stagiaire", ["stagiaire", "stage"]),
        ("benevole", ["bénévole", "benevole", "écovolontaire", "ecovolontaire", "bénévolat"]),
    ]
    for type_poste, needles in rules:
        for f in Fonction.objects.all():
            libelle = (f.libelle or "").lower()
            if any(n in libelle for n in needles) and f.type_poste == "salarie":
                f.type_poste = type_poste
                f.save(update_fields=["type_poste"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0109_alter_plangestion_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="fonction",
            name="type_poste",
            field=models.CharField(
                choices=[
                    ("salarie", "Salarié"),
                    ("stagiaire", "Stagiaire"),
                    ("prestataire", "Prestataire"),
                    ("benevole", "Bénévole"),
                ],
                default="salarie",
                help_text="Catégorie de la fonction. Conditionne la saisie du coût jour : pas de coût jour pour un prestataire, 0 par défaut pour un bénévole.",
                max_length=20,
                verbose_name="Type de poste",
            ),
        ),
        migrations.AddField(
            model_name="poste",
            name="cout_jour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coût journalier du poste (€), utilisé pour le calcul du coût salarial. Vide pour un prestataire (coût forfaitaire), 0 pour un bénévole.",
                max_digits=10,
                null=True,
                verbose_name="Coût jour (€)",
            ),
        ),
        migrations.RunPython(backfill_type_poste, noop),
    ]
