# Generated by Django 5.0.8 on 2026-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0110_fonction_type_poste_poste_cout_jour"),
    ]

    operations = [
        migrations.AddField(
            model_name="poste",
            name="organisme_libre",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom d'organisme saisi librement, hors référentiel — notamment pour un prestataire (ex. « presta1 »). Facultatif.",
                max_length=150,
                verbose_name="Organisme (saisi)",
            ),
        ),
    ]
