# Generated by Django 5.0.8 on 2026-07-23 09:47

from django.db import migrations, models


def backfill_categorie(apps, schema_editor):
    """Dérive la catégorie de dépense du booléen `finance` existant (#597).

    Financé → Fonctionnement (l'Investissement se choisit ensuite à la main) ;
    non financé → Bénévolat partenariat.
    """
    for model_name in ("OperationAnneeRH", "RealisationOperationAnneeRH"):
        Model = apps.get_model("plans", model_name)
        Model.objects.filter(finance=True).update(categorie_depense="fonctionnement")
        Model.objects.filter(finance=False).update(categorie_depense="benevolat_partenariat")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0111_poste_organisme_libre"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationanneerh",
            name="categorie_depense",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fonctionnement", "Fonctionnement"),
                    ("investissement", "Investissement"),
                    ("benevolat_partenariat", "Bénévolat partenariat"),
                ],
                default="",
                help_text="Catégorie budgétaire de la ligne. « Bénévolat partenariat » correspond au temps non financé.",
                max_length=30,
                verbose_name="Catégorie de dépense",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneerh",
            name="categorie_depense",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fonctionnement", "Fonctionnement"),
                    ("investissement", "Investissement"),
                    ("benevolat_partenariat", "Bénévolat partenariat"),
                ],
                default="",
                help_text="Catégorie budgétaire de la ligne. « Bénévolat partenariat » correspond au temps non financé.",
                max_length=30,
                verbose_name="Catégorie de dépense",
            ),
        ),
        migrations.RunPython(backfill_categorie, noop),
    ]
