# Generated by Django 5.0.8 on 2026-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0112_operationanneerh_categorie_depense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="autre_cout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Autre coût (€)",
            ),
        ),
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="autre_cout_commentaire",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Commentaire autre coût",
            ),
        ),
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="cout_prestataire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût prestataire (€)",
            ),
        ),
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="cout_stage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût stage (€)",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="ventilation_mode",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("by_org", "Par organisme"),
                    ("by_type", "Par type de budget"),
                    ("by_org_type", "Par organisme et type de budget"),
                    ("by_type_poste", "Par type de budget et type de poste"),
                    (
                        "by_org_type_poste",
                        "Par organisme, type de budget et type de poste",
                    ),
                ],
                default="none",
                help_text="Mode de ventilation du budget (aucune, par organisme, par type, les deux)",
                max_length=30,
                verbose_name="Mode de ventilation",
            ),
        ),
    ]
