# Generated by Django 5.0.8 on 2026-07-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0113_operationanneeorganisme_autre_cout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="autre_cout_invest",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Autre coût — investissement (€)",
            ),
        ),
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="autre_cout_invest_commentaire",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Commentaire autre coût — investissement",
            ),
        ),
        migrations.AddField(
            model_name="operationanneeorganisme",
            name="cout_prestataire_invest",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût prestataire — investissement (€)",
            ),
        ),
        migrations.AlterField(
            model_name="fonction",
            name="type_poste",
            field=models.CharField(
                choices=[
                    ("salarie", "Salarié"),
                    ("stagiaire", "Stagiaire"),
                    ("prestataire", "Prestataire"),
                    ("benevole", "Bénévole"),
                    ("partenaire", "Partenaire"),
                ],
                default="salarie",
                help_text="Catégorie de la fonction. Conditionne la saisie du coût jour : pas de coût jour pour un prestataire, 0 par défaut pour un bénévole.",
                max_length=20,
                verbose_name="Type de poste",
            ),
        ),
        migrations.AlterField(
            model_name="operationanneeorganisme",
            name="autre_cout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Autre coût — fonctionnement (€)",
            ),
        ),
        migrations.AlterField(
            model_name="operationanneeorganisme",
            name="autre_cout_commentaire",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Commentaire autre coût — fonctionnement",
            ),
        ),
        migrations.AlterField(
            model_name="operationanneeorganisme",
            name="cout_prestataire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût prestataire — fonctionnement (€)",
            ),
        ),
    ]
