# Generated by Django 5.0.8 on 2026-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0114_operationanneeorganisme_autre_cout_invest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="autre_cout_commentaire_realise",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Commentaire autre coût réalisé — fonctionnement",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="autre_cout_invest_commentaire_realise",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Commentaire autre coût réalisé — investissement",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="autre_cout_invest_realise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Autre coût réalisé — investissement (€)",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="autre_cout_realise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Autre coût réalisé — fonctionnement (€)",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="cout_prestataire_invest_realise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût prestataire réalisé — investissement (€)",
            ),
        ),
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="cout_prestataire_realise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût prestataire réalisé — fonctionnement (€)",
            ),
        ),
    ]
