# Generated by Django 5.0.8 on 2026-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0116_backfill_partenaire_type_poste"),
    ]

    operations = [
        migrations.AddField(
            model_name="realisationoperationanneeorganisme",
            name="cout_stage_realise",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût stage réalisé (€)",
            ),
        ),
    ]
