# Generated by Django 5.0.8 on 2026-07-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0120_fonction_portee_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="poste",
            name="commentaire",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Précisions libres sur le poste (#632). Aucune donnée nominative : ni nom ni prénom (RGPD).",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="poste",
            name="nom_local",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom donné au poste dans la réserve (#632). S'il est saisi, c'est lui qui s'affiche partout — fiches actions et suivis compris — à la place du libellé dérivé des fonctions. Jamais un nom de personne (RGPD).",
                max_length=150,
                verbose_name="Nom local",
            ),
        ),
    ]
