# Generated by Django 5.0.8 on 2026-07-31 11:25

import django.db.models.deletion
from django.db import migrations, models


def amorcer_liens_porteurs(apps, schema_editor):
    """
    Une ligne de liaison par résultat attendu existant (#585).

    L'invariant du modèle est que l'objectif **porteur** figure toujours dans
    `cor_ra_oo` : les listes construites sur la liaison doivent voir les RA
    d'avant le partage exactement comme avant.
    """
    ResultatAttendu = apps.get_model("plans", "ResultatAttendu")
    CorRaOo = apps.get_model("plans", "CorRaOo")
    CorRaOo.objects.bulk_create(
        [
            CorRaOo(id_ra_id=id_ra, id_oo_id=id_oo, ordre=ordre)
            for id_ra, id_oo, ordre in ResultatAttendu.objects.values_list(
                "id_ra", "id_oo", "ordre"
            )
        ],
        batch_size=500,
        ignore_conflicts=True,
    )


def supprimer_liens(apps, schema_editor):
    apps.get_model("plans", "CorRaOo").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0123_fonction_type_poste_nomenclature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultatattendu",
            name="id_oo",
            field=models.ForeignKey(
                db_column="id_oo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultats_attendus",
                to="plans.objectifoperationnel",
                verbose_name="Objectif opérationnel porteur",
            ),
        ),
        migrations.CreateModel(
            name="CorRaOo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ordre d'affichage du RA parmi ceux de cet objectif (0 = haut)",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "id_oo",
                    models.ForeignKey(
                        db_column="id_oo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_resultats_attendus",
                        to="plans.objectifoperationnel",
                        verbose_name="Objectif opérationnel",
                    ),
                ),
                (
                    "id_ra",
                    models.ForeignKey(
                        db_column="id_ra",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_objectifs",
                        to="plans.resultatattendu",
                        verbose_name="Résultat attendu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Résultat attendu-OO",
                "verbose_name_plural": "Liens Résultat attendu-OO",
                "db_table": '"general"."cor_ra_oo"',
                "db_table_comment": "Liaison partagée résultats attendus ↔ objectifs opérationnels (#585)",
                "ordering": ["ordre", "id"],
                "unique_together": {("id_ra", "id_oo")},
            },
        ),
        migrations.AddField(
            model_name="resultatattendu",
            name="objectifs_operationnels",
            field=models.ManyToManyField(
                help_text="Objectifs opérationnels sous lesquels ce résultat attendu apparaît (partagé, #585). Contient toujours l'objectif porteur `id_oo`.",
                related_name="resultats_attendus_partages",
                through="plans.CorRaOo",
                to="plans.objectifoperationnel",
                verbose_name="Objectifs opérationnels",
            ),
        ),
        migrations.RunPython(amorcer_liens_porteurs, supprimer_liens),
    ]
