# Generated by Django 5.0.8 on 2026-08-07 08:28

import django.db.models.deletion
from django.db import migrations, models


def amorcer_liens_porteurs(apps, schema_editor):
    """
    Une ligne de liaison par indicateur existant (#585).

    L'invariant du modèle est que le parent **porteur** figure toujours dans sa
    table de liaison : les listes construites sur la liaison doivent voir les
    indicateurs d'avant le partage exactement comme avant. Un indicateur n'a
    qu'un seul parent (état → niveau d'exigence, pression → résultat attendu),
    d'où les deux passes filtrées sur la FK non nulle.
    """
    Indicateur = apps.get_model("plans", "Indicateur")
    CorIndicateurNe = apps.get_model("plans", "CorIndicateurNe")
    CorIndicateurRa = apps.get_model("plans", "CorIndicateurRa")

    CorIndicateurNe.objects.bulk_create(
        [
            CorIndicateurNe(id_indicateur_id=id_ind, id_ne_id=id_ne, ordre=ordre)
            for id_ind, id_ne, ordre in Indicateur.objects.filter(
                id_ne__isnull=False
            ).values_list("id_indicateur", "id_ne", "ordre")
        ],
        batch_size=500,
        ignore_conflicts=True,
    )
    CorIndicateurRa.objects.bulk_create(
        [
            CorIndicateurRa(id_indicateur_id=id_ind, id_resultat_attendu_id=id_ra, ordre=ordre)
            for id_ind, id_ra, ordre in Indicateur.objects.filter(
                id_resultat_attendu__isnull=False
            ).values_list("id_indicateur", "id_resultat_attendu", "ordre")
        ],
        batch_size=500,
        ignore_conflicts=True,
    )


def supprimer_liens(apps, schema_editor):
    apps.get_model("plans", "CorIndicateurNe").objects.all().delete()
    apps.get_model("plans", "CorIndicateurRa").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0125_operation_declinaison_par_type_cout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicateur",
            name="id_ne",
            field=models.ForeignKey(
                blank=True,
                db_column="id_ne",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicateurs",
                to="plans.niveauexigence",
                verbose_name="Niveau d'exigence porteur",
            ),
        ),
        migrations.AlterField(
            model_name="indicateur",
            name="id_resultat_attendu",
            field=models.ForeignKey(
                blank=True,
                db_column="id_resultat_attendu",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicateurs",
                to="plans.resultatattendu",
                verbose_name="Résultat attendu porteur",
            ),
        ),
        migrations.CreateModel(
            name="CorIndicateurNe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ordre d'affichage de l'indicateur parmi ceux de ce niveau (0 = haut)",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_niveaux_exigence",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
                (
                    "id_ne",
                    models.ForeignKey(
                        db_column="id_ne",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_indicateurs",
                        to="plans.niveauexigence",
                        verbose_name="Niveau d'exigence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Indicateur-Niveau d'exigence",
                "verbose_name_plural": "Liens Indicateur-Niveau d'exigence",
                "db_table": '"general"."cor_indicateur_ne"',
                "db_table_comment": "Liaison partagée indicateurs d'état ↔ niveaux d'exigence (#585)",
                "ordering": ["ordre", "id"],
                "unique_together": {("id_indicateur", "id_ne")},
            },
        ),
        migrations.AddField(
            model_name="indicateur",
            name="niveaux_exigence",
            field=models.ManyToManyField(
                help_text="Niveaux d'exigence sous lesquels cet indicateur d'état apparaît (partagé, #585). Contient toujours le niveau porteur `id_ne`.",
                related_name="indicateurs_partages",
                through="plans.CorIndicateurNe",
                to="plans.niveauexigence",
                verbose_name="Niveaux d'exigence",
            ),
        ),
        migrations.CreateModel(
            name="CorIndicateurRa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ordre d'affichage de l'indicateur parmi ceux de ce résultat attendu (0 = haut)",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "id_indicateur",
                    models.ForeignKey(
                        db_column="id_indicateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_resultats_attendus",
                        to="plans.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
                (
                    "id_resultat_attendu",
                    models.ForeignKey(
                        db_column="id_resultat_attendu",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cor_indicateurs",
                        to="plans.resultatattendu",
                        verbose_name="Résultat attendu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Indicateur-Résultat attendu",
                "verbose_name_plural": "Liens Indicateur-Résultat attendu",
                "db_table": '"general"."cor_indicateur_ra"',
                "db_table_comment": "Liaison partagée indicateurs de pression ↔ résultats attendus (#585)",
                "ordering": ["ordre", "id"],
                "unique_together": {("id_indicateur", "id_resultat_attendu")},
            },
        ),
        migrations.AddField(
            model_name="indicateur",
            name="resultats_attendus",
            field=models.ManyToManyField(
                help_text="Résultats attendus sous lesquels cet indicateur de pression apparaît (partagé, #585). Contient toujours le résultat attendu porteur `id_resultat_attendu`.",
                related_name="indicateurs_partages",
                through="plans.CorIndicateurRa",
                to="plans.resultatattendu",
                verbose_name="Résultats attendus",
            ),
        ),
        migrations.RunPython(amorcer_liens_porteurs, supprimer_liens),
    ]
