# Generated by Django 5.2.17 on 2026-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0127_plangestion_uuid_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="action_restauration",
            field=models.BooleanField(
                blank=True,
                help_text="Le gestionnaire considère-t-il cette action comme de nature restaurative ?",
                null=True,
                verbose_name="Action de restauration",
            ),
        ),
    ]
