# Generated by Django 5.0.8 on 2026-01-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Debut de session"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de session"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raison optionnelle de l'impersonation",
                        verbose_name="Motif",
                    ),
                ),
                (
                    "impersonated_user",
                    models.ForeignKey(
                        help_text="L'utilisateur dont le compte est visualise",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_logs_as_target",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur cible",
                    ),
                ),
                (
                    "impersonator",
                    models.ForeignKey(
                        help_text="L'administrateur qui effectue l'impersonation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_logs_as_admin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Super Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'impersonation",
                "verbose_name_plural": "Logs d'impersonation",
                "db_table": "auth_impersonation_log",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["impersonator", "started_at"],
                        name="auth_impers_imperso_4ce673_idx",
                    ),
                    models.Index(
                        fields=["impersonated_user", "started_at"],
                        name="auth_impers_imperso_e21157_idx",
                    ),
                ],
            },
        ),
    ]
