# Generated by Django 5.0.8 on 2026-01-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="impersonationlog",
            name="impersonated_user",
            field=models.ForeignKey(
                help_text="L'utilisateur dont le compte est visualise",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impersonation_logs_as_target",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur cible",
            ),
        ),
        migrations.AddField(
            model_name="impersonationlog",
            name="impersonator",
            field=models.ForeignKey(
                help_text="L'administrateur qui effectue l'impersonation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impersonation_logs_as_admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Super Admin",
            ),
        ),
        migrations.AddIndex(
            model_name="impersonationlog",
            index=models.Index(
                fields=["impersonator", "started_at"],
                name="t_impersona_imperso_1f6247_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="impersonationlog",
            index=models.Index(
                fields=["impersonated_user", "started_at"],
                name="t_impersona_imperso_6d1b48_idx",
            ),
        ),
    ]
