# Generated by Django 5.2.17 on 2026-09-30 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('structure_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rgpd_consent', models.BooleanField(default=False)),
                ('rgpd_consent_date', models.DateTimeField(blank=True, null=True)),
                ('rgpd_withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracking_instances',
                'indexes': [models.Index(fields=['version'], name='tracking_in_version_636793_idx'), models.Index(fields=['last_heartbeat'], name='tracking_in_last_he_32c308_idx'), models.Index(fields=['is_active'], name='tracking_in_is_acti_06a108_idx')],
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='instances.instance')),
            ],
            options={
                'db_table': 'tracking_heartbeats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instance', '-timestamp'], name='tracking_he_instanc_e511c8_idx')],
            },
        ),
    ]
