# Generated by Django 5.2.17 on 2026-10-07 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesionHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id_demande', models.CharField(db_index=True, max_length=50, verbose_name='identifiant demandé')),
                ('libelle', models.CharField(max_length=200, verbose_name='nom de la structure')),
                ('url_publique', models.CharField(blank=True, max_length=500, verbose_name='URL publique')),
                ('empreinte_depot', models.CharField(max_length=64, verbose_name='empreinte du jeton de dépôt')),
                ('empreinte_lecture', models.CharField(max_length=64, verbose_name='empreinte du jeton de lecture')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], db_index=True, default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif du refus')),
                ('hub_url', models.CharField(blank=True, max_length=500, verbose_name='URL du hub')),
                ('demandee_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='demandée le')),
                ('traitee_le', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('traitee_par', models.CharField(blank=True, max_length=150, verbose_name='traitée par')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adhesion_hub', to='instances.instance')),
            ],
            options={
                'verbose_name': 'adhésion au hub',
                'verbose_name_plural': 'adhésions au hub',
                'db_table': 'tracking_adhesions_hub',
                'ordering': ['-demandee_le'],
            },
        ),
    ]
