# Generated by Django 5.0.8 on 2026-08-17 11:16

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_create_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuIndexe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_index=True, max_length=64, verbose_name="Instance d'origine")),
                ('type_contenu', models.CharField(choices=[('enjeu', 'Enjeu'), ('facteur', "Facteur d'influence"), ('pression', 'Pression'), ('objectif_lt', 'Objectif à long terme'), ('objectif_op', 'Objectif opérationnel'), ('indicateur', 'Indicateur'), ('action', 'Action')], max_length=20, verbose_name='Type de contenu')),
                ('id_objet', models.IntegerField(help_text="Clé primaire chez l'émetteur — séquence locale.", verbose_name="Identifiant de l'objet")),
                ('index_version', models.PositiveSmallIntegerField(db_index=True, default=0, help_text="Version des extracteurs de l'instance émettrice qui a produit la ligne. Permet de repérer les instances en retard d'une version sans les interroger.", verbose_name='Version des extracteurs')),
                ('titre', models.CharField(max_length=500, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('rattachements', models.TextField(blank=True, default='', help_text="Espèces, habitats, éléments géologiques, protocoles standardisés, références PressRef et catégories d'action. Interrogé dans les DEUX modes de recherche.", verbose_name='Objets rattachés')),
                ('contexte', models.TextField(blank=True, default='', help_text='Libellés des objets ancêtres. Interrogé uniquement en mode élargi.', verbose_name='Contexte')),
                ('parent_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type du parent')),
                ('parent_libelle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Libellé du parent')),
                ('sous_type', models.CharField(blank=True, help_text="Code de la facette propre au type : `ecologique`/`socioeco` pour un enjeu, `ETAT`/`PRESSION`/`REPONSE` pour un indicateur, code de catégorie d'action pour une action.", max_length=50, null=True, verbose_name='Sous-type')),
                ('sous_type_libelle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Libellé du sous-type')),
                ('statut_pg', models.CharField(max_length=20, verbose_name='Statut du plan')),
                ('annee_debut', models.IntegerField(blank=True, null=True, verbose_name='Année de début')),
                ('annee_fin', models.IntegerField(blank=True, null=True, verbose_name='Année de fin')),
                ('type_site_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None, verbose_name="Types d'aires protégées")),
                ('area_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='Zones géographiques')),
                ('organisme_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='Organismes gestionnaires')),
                ('search_titre', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('titre', config='public.french_unaccent', weight='A'), '||', django.contrib.postgres.search.SearchVector('rattachements', config='public.french_unaccent', weight='B'), django.contrib.postgres.search.SearchConfig('public.french_unaccent')), output_field=django.contrib.postgres.search.SearchVectorField(), verbose_name='Vecteur — libellé et objets rattachés')),
                ('search_full', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('titre', config='public.french_unaccent', weight='A'), '||', django.contrib.postgres.search.SearchVector('rattachements', config='public.french_unaccent', weight='B'), django.contrib.postgres.search.SearchConfig('public.french_unaccent')), '||', django.contrib.postgres.search.SearchVector('description', config='public.french_unaccent', weight='B'), django.contrib.postgres.search.SearchConfig('public.french_unaccent')), '||', django.contrib.postgres.search.SearchVector('contexte', config='public.french_unaccent', weight='C'), django.contrib.postgres.search.SearchConfig('public.french_unaccent')), output_field=django.contrib.postgres.search.SearchVectorField(), verbose_name='Vecteur — texte complet')),
                ('date_indexation', models.DateTimeField(auto_now=True, verbose_name='Indexé le')),
            ],
            options={
                'verbose_name': 'Contenu indexé',
                'verbose_name_plural': 'Contenus indexés',
                'db_table': '"ccd_search"."t_recherche_contenu"',
            },
        ),
        migrations.CreateModel(
            name='PlanIndexe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_index=True, help_text='Déploiement CICADA qui a publié ce plan.', max_length=64, verbose_name="Instance d'origine")),
                ('id_pg', models.IntegerField(help_text="Séquence locale de l'instance émettrice : n'a de sens que couplée à `instance_id`.", verbose_name="Identifiant du plan chez l'émetteur")),
                ('slug', models.SlugField(help_text="Slug du plan chez l'émetteur. Non unique ici : deux instances peuvent produire le même slug pour deux plans différents.", max_length=255, verbose_name='Slug')),
                ('url_instance', models.URLField(blank=True, default='', help_text="Racine de l'instance émettrice, pour renvoyer l'utilisateur vers le plan chez lui quand c'est pertinent (édition, pièces jointes, données que le hub ne porte pas).", verbose_name="URL publique de l'instance")),
                ('nom', models.CharField(max_length=500, verbose_name='Nom du plan')),
                ('statut', models.CharField(max_length=20, verbose_name='Statut')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='Rang')),
                ('annee_debut', models.IntegerField(blank=True, null=True, verbose_name='Année de début')),
                ('annee_fin', models.IntegerField(blank=True, null=True, verbose_name='Année de fin')),
                ('type_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de document')),
                ('gestionnaire_principal', models.CharField(blank=True, help_text="Nom de l'organisme, en clair. Faute d'identité nationale des organismes, seul le libellé voyage — il s'affiche, il ne filtre pas.", max_length=255, null=True, verbose_name='Gestionnaire principal')),
                ('sites', models.JSONField(blank=True, default=list, help_text="Sites du plan tels qu'affichés sur une tuile : nom, slug et code INPN quand il existe.", verbose_name='Sites')),
                ('site_inpn_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Stockés tels quels, et non traduits en identifiants locaux comme dans CICADA : le hub n'héberge aucun site, il n'a rien à quoi les apparier. C'est aussi ce qui permettra de dédoublonner un site co-géré par deux instances.", size=None, verbose_name='Codes INPN des sites')),
                ('type_site_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None, verbose_name="Types d'aires protégées")),
                ('area_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text="Identifiants ref_geo **locaux au hub**, résolus à l'ingestion depuis les codes INSEE publiés.", size=None, verbose_name='Zones géographiques')),
                ('organisme_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text="Vide tant que l'identité nationale des organismes n'est pas tranchée (SIRET ? annuaire RNF ?). La colonne existe pour que le filtre ait sa place le jour où la décision tombe : recopier un identifiant local ferait matcher le mauvais organisme, une corruption silencieuse, là où un tableau vide produit une absence visible.", size=None, verbose_name='Organismes gestionnaires')),
                ('fiche', models.JSONField(blank=True, default=dict, help_text="Arbre rendu par les sérialiseurs de fiche de l'instance émettrice, stocké tel quel et resservi tel quel.", verbose_name='Fiche publique')),
                ('format_version', models.PositiveSmallIntegerField(default=0, help_text='Version du contrat avec laquelle ce plan a été reçu. Les instances sont mises à jour indépendamment : deux plans du même hub peuvent venir de deux versions du format.', verbose_name="Version du format d'échange")),
                ('date_publication', models.DateTimeField(auto_now=True, verbose_name='Publié le')),
            ],
            options={
                'verbose_name': 'Plan indexé',
                'verbose_name_plural': 'Plans indexés',
                'db_table': '"ccd_search"."t_plan_indexe"',
                'indexes': [models.Index(fields=['instance_id', 'slug'], name='idx_plan_instance_slug'), models.Index(fields=['statut'], name='idx_plan_statut'), django.contrib.postgres.indexes.GinIndex(fields=['area_ids'], name='idx_plan_areas'), django.contrib.postgres.indexes.GinIndex(fields=['type_site_codes'], name='idx_plan_types_site'), django.contrib.postgres.indexes.GinIndex(fields=['site_inpn_codes'], name='idx_plan_sites_inpn')],
            },
        ),
        migrations.AddConstraint(
            model_name='planindexe',
            constraint=models.UniqueConstraint(fields=('instance_id', 'id_pg'), name='uq_plan_indexe_origine'),
        ),
        migrations.AddField(
            model_name='contenuindexe',
            name='plan',
            field=models.ForeignKey(db_column='id_plan_indexe', on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='index.planindexe', verbose_name='Plan indexé'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_titre'], name='idx_recherche_titre_gin'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_full'], name='idx_recherche_full_gin'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['titre'], name='idx_recherche_titre_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['rattachements'], name='idx_recherche_ratt_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['type_site_codes'], name='idx_recherche_types_site'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['area_ids'], name='idx_recherche_areas'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['organisme_codes'], name='idx_recherche_organismes'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=models.Index(fields=['type_contenu'], name='idx_recherche_type'),
        ),
        migrations.AddIndex(
            model_name='contenuindexe',
            index=models.Index(fields=['statut_pg'], name='idx_recherche_statut'),
        ),
        migrations.AddConstraint(
            model_name='contenuindexe',
            constraint=models.UniqueConstraint(fields=('instance_id', 'type_contenu', 'id_objet'), name='uq_recherche_contenu_objet'),
        ),
    ]
