# Generated by Django 5.0.8 on 2026-08-17 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_index=True, help_text='Déduite du jeton, jamais du corps de la requête.', max_length=64, verbose_name='Instance émettrice')),
                ('etat', models.CharField(choices=[('ouvert', 'Ouvert'), ('bascule', 'Basculé')], default='ouvert', max_length=10, verbose_name='État')),
                ('format_version', models.PositiveSmallIntegerField(default=0, verbose_name="Version du format d'échange")),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name='Ouvert le')),
                ('date_bascule', models.DateTimeField(blank=True, null=True, verbose_name='Basculé le')),
                ('plans_recus', models.IntegerField(default=0, verbose_name='Plans reçus')),
                ('contenus_recus', models.IntegerField(default=0, verbose_name='Contenus reçus')),
                ('plans_purges', models.IntegerField(default=0, help_text='Plans de cette instance absents du lot, donc dépubliés.', verbose_name='Plans purgés à la bascule')),
            ],
            options={
                'verbose_name': 'Lot de publication',
                'verbose_name_plural': 'Lots de publication',
                'db_table': '"ccd_search"."t_lot_publication"',
                'indexes': [models.Index(fields=['instance_id', 'etat'], name='idx_lot_instance_etat')],
            },
        ),
        migrations.AddField(
            model_name='planindexe',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='id_lot', help_text="Dernier lot dans lequel ce plan a été vu. C'est ce qui permet à la bascule de retirer les plans absents du lot sans avoir besoin d'un message de retrait. Un plan sans lot n'a été revu par aucune publication : il sera purgé à la prochaine bascule de son instance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='index.lotpublication', verbose_name='Lot de publication'),
        ),
    ]
