# Generated by Django 5.0.8 on 2026-08-17 11:54

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_lotpublication_planindexe_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='planindexe',
            name='sites_noms',
            field=models.TextField(blank=True, default='', help_text="Noms des sites concaténés, pour la recherche par nom de site du mode « plan de gestion ». Dérivé de `sites` à l'ingestion : chercher dans un tableau JSON supposerait de le convertir en texte à chaque requête, sans pouvoir l'indexer.", verbose_name='Noms des sites'),
        ),
        migrations.AddIndex(
            model_name='planindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='idx_plan_nom_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='planindexe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sites_noms'], name='idx_plan_sites_noms_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
