# Generated by Django 5.0.8 on 2026-08-25 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_planindexe_sites_noms_planindexe_idx_plan_nom_trgm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.CharField(help_text="Immuable : il est écrit dans chaque ligne d'index publiée.", max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]{0,63}$', message="L'identifiant d'instance doit être en minuscules : lettres, chiffres et tirets, en commençant par une lettre ou un chiffre.")], verbose_name='Identifiant')),
                ('libelle', models.CharField(blank=True, default='', help_text="Nom de la structure, pour les écrans d'administration.", max_length=200, verbose_name='Nom affiché')),
                ('url_publique', models.URLField(blank=True, default='', help_text="Renseignée par l'instance à chaque publication.", verbose_name='URL publique')),
                ('empreinte_depot', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Empreinte du jeton de dépôt')),
                ('empreinte_lecture', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Empreinte du jeton de lecture')),
                ('active', models.BooleanField(default=True, help_text="Désactiver refuse les jetons sans rien effacer : l'index publié reste servi. Pour le retirer, c'est à l'instance de dépublier.", verbose_name='Active')),
                ('date_enrolement', models.DateTimeField(auto_now_add=True, verbose_name='Enrôlée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Instance fédérée',
                'verbose_name_plural': 'Instances fédérées',
                'db_table': '"ccd_search"."t_instance"',
                'ordering': ['instance_id'],
            },
        ),
    ]
