# Generated by Django 5.0.8 on 2026-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotpublication',
            name='libelle_declare',
            field=models.CharField(blank=True, default='', help_text="Nom que l'instance se donne, transmis à l'ouverture du lot. Sert à nommer la provenance d'un résultat pour une instance qui n'a pas encore de ligne au registre : un identifiant technique ne dit pas à un gestionnaire de quelle structure vient le plan qu'il lit.", max_length=200, verbose_name="Nom déclaré par l'instance"),
        ),
        migrations.AddField(
            model_name='lotpublication',
            name='url_publique_declaree',
            field=models.URLField(blank=True, default='', verbose_name='URL publique déclarée'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='url_publique',
            field=models.URLField(blank=True, default='', help_text="Renseignée à l'enrôlement. À défaut, celle que l'instance déclare en publiant fait office (cf. `identites`).", verbose_name='URL publique'),
        ),
    ]
