# Generated by Django 5.0.8 on 2026-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_lotpublication_libelle_declare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenuindexe',
            name='annees_extension',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Années d'extension"),
        ),
        migrations.AddField(
            model_name='planindexe',
            name='annees_extension',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Années d'extension"),
        ),
    ]
