# Generated by Django 5.2.17 on 2026-10-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_ascendance_portees'),
    ]

    operations = [
        migrations.AddField(
            model_name='planindexe',
            name='ecrans',
            field=models.JSONField(blank=True, default=dict, help_text="Réponses d'API des écrans réels du plan (page, arborescence, fiches action), élaguées des données sensibles par l'instance émettrice (#683). Stockées telles quelles, resservies telles quelles : le hub n'en lit rien.", verbose_name='Écrans réels publiés'),
        ),
    ]
