# Generated by Django 5.0.8 on 2026-07-27 13:46

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_create_schemas"),
        ("plans", "0119_retire_fonction_prestataire"),
    ]

    operations = [
        # Le schéma, les extensions et la configuration de recherche doivent
        # exister AVANT la table : ses deux colonnes générées appellent
        # `to_tsvector('public.french_unaccent', …)`.
        migrations.RunSQL(
            sql=[
                "CREATE SCHEMA IF NOT EXISTS ccd_search;",
                "COMMENT ON SCHEMA ccd_search IS "
                "'Schéma pour l''index de recherche Cicada (exploration des données)';",
                "CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA public;",
                "CREATE EXTENSION IF NOT EXISTS unaccent SCHEMA public;",
            ],
            reverse_sql=["DROP SCHEMA IF EXISTS ccd_search CASCADE;"],
        ),
        # Configuration plein texte française insensible aux accents : le
        # dictionnaire `french` radicalise (limicoles → limicol) mais ne retire
        # pas les accents, si bien que « foret » ne trouverait pas « forêt ».
        # On chaîne donc `unaccent` avant `french_stem`.
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_ts_config c
                    JOIN pg_namespace n ON n.oid = c.cfgnamespace
                    WHERE c.cfgname = 'french_unaccent' AND n.nspname = 'public'
                ) THEN
                    CREATE TEXT SEARCH CONFIGURATION public.french_unaccent
                        ( COPY = pg_catalog.french );
                    ALTER TEXT SEARCH CONFIGURATION public.french_unaccent
                        ALTER MAPPING FOR hword, hword_part, word
                        WITH unaccent, french_stem;
                END IF;
            END
            $$;
            """,
            reverse_sql=(
                "DROP TEXT SEARCH CONFIGURATION IF EXISTS public.french_unaccent;"
            ),
        ),
        migrations.CreateModel(
            name="ContenuIndexe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type_contenu",
                    models.CharField(
                        choices=[
                            ("enjeu", "Enjeu"),
                            ("facteur", "Facteur d'influence"),
                            ("pression", "Pression"),
                            ("objectif_lt", "Objectif à long terme"),
                            ("objectif_op", "Objectif opérationnel"),
                            ("indicateur", "Indicateur"),
                            ("action", "Action"),
                        ],
                        max_length=20,
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "id_objet",
                    models.IntegerField(
                        help_text="Clé primaire dans la table métier correspondante.",
                        verbose_name="Identifiant de l'objet",
                    ),
                ),
                ("titre", models.CharField(max_length=500, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "contexte",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Libellés des ancêtres et des taxons/habitats rattachés. Interrogé uniquement en mode élargi.",
                        verbose_name="Contexte",
                    ),
                ),
                (
                    "parent_type",
                    models.CharField(
                        blank=True,
                        help_text="Code du type de l'objet parent. Volontairement libre : le parent d'une action peut être un suivi/inventaire, qui n'est pas lui-même un type explorable.",
                        max_length=20,
                        null=True,
                        verbose_name="Type du parent",
                    ),
                ),
                (
                    "parent_libelle",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Libellé du parent",
                    ),
                ),
                (
                    "sous_type",
                    models.CharField(
                        blank=True,
                        help_text="Code de la facette propre au type : `ecologique`/`socioeco` pour un enjeu, `ETAT`/`PRESSION`/`REPONSE` pour un indicateur, code de catégorie d'action (`SP`, `CS`…) pour une action.",
                        max_length=50,
                        null=True,
                        verbose_name="Sous-type",
                    ),
                ),
                (
                    "sous_type_libelle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Libellé du sous-type",
                    ),
                ),
                (
                    "statut_pg",
                    models.CharField(max_length=20, verbose_name="Statut du plan"),
                ),
                (
                    "annee_debut",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Année de début"
                    ),
                ),
                (
                    "annee_fin",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Année de fin"
                    ),
                ),
                (
                    "site_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Sites",
                    ),
                ),
                (
                    "organisme_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Organismes gestionnaires",
                    ),
                ),
                (
                    "type_site_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=25),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Types d'aires protégées",
                    ),
                ),
                (
                    "area_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="Identifiants ref_geo des départements ET des régions.",
                        size=None,
                        verbose_name="Zones géographiques",
                    ),
                ),
                (
                    "search_titre",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "titre", config="public.french_unaccent"
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        verbose_name="Vecteur — libellé",
                    ),
                ),
                (
                    "search_full",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.SearchVector(
                                    "titre", config="public.french_unaccent", weight="A"
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "description",
                                    config="public.french_unaccent",
                                    weight="B",
                                ),
                                django.contrib.postgres.search.SearchConfig(
                                    "public.french_unaccent"
                                ),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "contexte", config="public.french_unaccent", weight="C"
                            ),
                            django.contrib.postgres.search.SearchConfig(
                                "public.french_unaccent"
                            ),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        verbose_name="Vecteur — texte complet",
                    ),
                ),
                (
                    "date_indexation",
                    models.DateTimeField(auto_now=True, verbose_name="Indexé le"),
                ),
                (
                    "id_pg",
                    models.ForeignKey(
                        db_column="id_pg",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contenus_indexes",
                        to="plans.plangestion",
                        verbose_name="Plan de gestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenu indexé",
                "verbose_name_plural": "Contenus indexés",
                "db_table": '"ccd_search"."t_recherche_contenu"',
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_titre"], name="idx_recherche_titre_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_full"], name="idx_recherche_full_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["titre"],
                        name="idx_recherche_titre_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["site_ids"], name="idx_recherche_sites"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["organisme_ids"], name="idx_recherche_organismes"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["type_site_codes"], name="idx_recherche_types_site"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["area_ids"], name="idx_recherche_areas"
                    ),
                    models.Index(fields=["type_contenu"], name="idx_recherche_type"),
                    models.Index(fields=["statut_pg"], name="idx_recherche_statut"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="contenuindexe",
            constraint=models.UniqueConstraint(
                fields=("type_contenu", "id_objet"), name="uq_recherche_contenu_objet"
            ),
        ),
    ]
