# Generated by Django 5.0.8 on 2026-07-28 13:05
"""
Ajoute la colonne `rattachements` à l'index de recherche (#634).

PostgreSQL n'accepte pas de modifier l'expression d'une colonne générée : les
deux vecteurs doivent être supprimés puis recréés. Leurs index GIN partent avec
la colonne, il faut donc les retirer et les reposer explicitement.
"""

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        # Les index GIN reposent sur les colonnes générées : ils tombent avec elles.
        migrations.RemoveIndex(
            model_name="contenuindexe", name="idx_recherche_titre_gin",
        ),
        migrations.RemoveIndex(
            model_name="contenuindexe", name="idx_recherche_full_gin",
        ),
        migrations.RemoveField(model_name="contenuindexe", name="search_titre"),
        migrations.RemoveField(model_name="contenuindexe", name="search_full"),
        migrations.AddField(
            model_name="contenuindexe",
            name="rattachements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Espèces (noms scientifiques ET vernaculaires), habitats, éléments géologiques, protocoles standardisés, références PressRef et catégories d'action rattachés à l'objet ou à son enjeu. Interrogé dans les DEUX modes (#634).",
                verbose_name="Objets rattachés",
            ),
        ),
        migrations.AlterField(
            model_name="contenuindexe",
            name="contexte",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Libellés des objets ancêtres. Interrogé uniquement en mode élargi.",
                verbose_name="Contexte",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="search_full",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector(
                                "titre", config="public.french_unaccent", weight="A"
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "rattachements",
                                config="public.french_unaccent",
                                weight="B",
                            ),
                            django.contrib.postgres.search.SearchConfig(
                                "public.french_unaccent"
                            ),
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "description", config="public.french_unaccent", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig(
                            "public.french_unaccent"
                        ),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "contexte", config="public.french_unaccent", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig(
                        "public.french_unaccent"
                    ),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Vecteur — texte complet",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="search_titre",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "titre", config="public.french_unaccent", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "rattachements", config="public.french_unaccent", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig(
                        "public.french_unaccent"
                    ),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Vecteur — libellé et objets rattachés",
            ),
        ),
        migrations.AddIndex(
            model_name="contenuindexe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_titre"], name="idx_recherche_titre_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="contenuindexe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_full"], name="idx_recherche_full_gin"
            ),
        ),
    ]
