# Generated by Django 5.0.8 on 2026-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_contenuindexe_rattachements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenuindexe",
            name="index_version",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Version d'`apps.search.indexing` qui a produit la ligne (#634). Une ligne écrite par une version antérieure est périmée : le contenu du plan n'ayant plus le droit de bouger une fois validé, rien ne la réécrirait autrement, et une recherche ajoutée depuis ne trouverait jamais rien. 0 = index antérieur au suivi de version.",
                verbose_name="Version des extracteurs",
            ),
        ),
    ]
