# Generated by Django 5.0.8 on 2026-08-06 09:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0125_operation_declinaison_par_type_cout"),
        ("search", "0003_index_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contenuindexe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["rattachements"],
                name="idx_recherche_ratt_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
