# Generated by Django 5.0.8 on 2026-07-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0123_fonction_type_poste_nomenclature"),
        # Renumérotée en 0005 derrière l'index trigramme (#634), arrivé
        # entre-temps sur develop en 0004 : les deux migrations partaient
        # sinon du même parent, ce qui laissait deux feuilles dans le graphe.
        ("search", "0004_contenuindexe_idx_recherche_ratt_trgm"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contenuindexe",
            name="uq_recherche_contenu_objet",
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="instance_id",
            field=models.CharField(
                db_index=True,
                default="local",
                help_text="Déploiement CICADA dont provient le document (#636). Vaut `settings.CICADA_INSTANCE_ID` pour les documents produits ici, et l'identifiant de l'émetteur pour un document reçu d'une autre instance. C'est la seule chose qui rende `id_objet` non ambigu : toutes les clés primaires de l'application sont des séquences locales.",
                max_length=64,
                verbose_name="Instance d'origine",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="plan_denorm",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot du bandeau « plan / gestionnaire / période » d'une tuile, capturé au moment de la publication. Renseigné uniquement pour les documents distants : pour les documents locaux, ces libellés restent joints à la volée et ne peuvent donc pas devenir obsolètes.",
                verbose_name="Bandeau du plan (documents distants)",
            ),
        ),
        migrations.AlterField(
            model_name="contenuindexe",
            name="id_pg",
            field=models.ForeignKey(
                blank=True,
                db_column="id_pg",
                help_text="NULL pour un document reçu d'une autre instance : le plan n'existe pas dans cette base. Le bandeau à afficher est alors dans `plan_denorm`.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contenus_indexes",
                to="plans.plangestion",
                verbose_name="Plan de gestion",
            ),
        ),
        migrations.AddConstraint(
            model_name="contenuindexe",
            constraint=models.UniqueConstraint(
                fields=("instance_id", "type_contenu", "id_objet"),
                name="uq_recherche_contenu_objet",
            ),
        ),
    ]
