# Generated by Django 5.0.8 on 2026-09-28 14:46

from django.db import migrations, models


def recopier_prolongations(apps, schema_editor):
    """#676 — Reporte la prolongation des plans déjà indexés, sans réindexer."""
    PlanGestion = apps.get_model("plans", "PlanGestion")
    ContenuIndexe = apps.get_model("search", "ContenuIndexe")
    for id_pg, annees in (
        PlanGestion.objects.filter(annees_extension__gt=0)
        .values_list("id_pg", "annees_extension")
    ):
        ContenuIndexe.objects.filter(id_pg_id=id_pg).update(annees_extension=annees)


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0005_federation_instance_id"),
        ("plans", "0071_remove_etendu_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenuindexe",
            name="annees_extension",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Années d'extension"
            ),
        ),
        migrations.RunPython(recopier_prolongations, migrations.RunPython.noop),
    ]
