# Generated by Django 5.2.17 on 2026-10-06 12:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_contenu_annees_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenuindexe",
            name="chemin",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ancêtres de l'objet, de l'enjeu jusqu'au parent direct, sous la forme [{type, id, libelle}] (#682). C'est ce qui permet à une tuile de résultat de montrer l'arborescence qui mène à l'objet retrouvé — et, en mode élargi, de désigner l'ancêtre dont le libellé a répondu. `parent_type` / `parent_libelle` en sont le dernier maillon, conservés pour les lecteurs qui ne connaissent pas cette colonne.",
                verbose_name="Ascendance",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="enfants",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Libellés des objets descendants (#682) : un enjeu porte ici ses objectifs, indicateurs, métriques et actions. Interrogé seulement si la portée « éléments enfants » est cochée — c'est ce qui fait ressortir un enjeu quand c'est l'un de ses objectifs qui porte le mot cherché.",
                verbose_name="Descendance",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="enjeu_slug",
            field=models.CharField(
                blank=True,
                help_text="Slug de l'enjeu dont l'objet descend (le sien pour un enjeu). Sert à ouvrir l'arborescence réelle du plan sur la bonne branche (#683).",
                max_length=255,
                null=True,
                verbose_name="Slug de l'enjeu de la branche",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="search_contexte",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "contexte", config="public.french_unaccent", weight="C"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Vecteur — éléments parents",
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="search_description",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "description", config="public.french_unaccent", weight="B"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Vecteur — description",
            ),
        ),
        migrations.AlterField(
            model_name="contenuindexe",
            name="contexte",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Libellés des objets ancêtres. Interrogé seulement si la portée « éléments parents » est cochée.",
                verbose_name="Contexte",
            ),
        ),
        # Une colonne générée ne se modifie pas : on la recrée, index compris.
        migrations.RemoveIndex(
            model_name="contenuindexe",
            name="idx_recherche_full_gin",
        ),
        migrations.RemoveField(
            model_name="contenuindexe",
            name="search_full",
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="search_full",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.SearchVector(
                                    "titre", config="public.french_unaccent", weight="A"
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "rattachements",
                                    config="public.french_unaccent",
                                    weight="B",
                                ),
                                django.contrib.postgres.search.SearchConfig(
                                    "public.french_unaccent"
                                ),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "description",
                                config="public.french_unaccent",
                                weight="B",
                            ),
                            django.contrib.postgres.search.SearchConfig(
                                "public.french_unaccent"
                            ),
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "contexte", config="public.french_unaccent", weight="C"
                        ),
                        django.contrib.postgres.search.SearchConfig(
                            "public.french_unaccent"
                        ),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "enfants", config="public.french_unaccent", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig(
                        "public.french_unaccent"
                    ),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Vecteur — texte complet",
            ),
        ),
        migrations.AddIndex(
            model_name="contenuindexe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_full"], name="idx_recherche_full_gin"
            ),
        ),
        migrations.AddField(
            model_name="contenuindexe",
            name="search_enfants",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "enfants", config="public.french_unaccent", weight="C"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Vecteur — éléments enfants",
            ),
        ),
    ]
