# Generated by Django 5.2.17 on 2026-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_ascendance_portees"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date"
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("nuit", "Publication de nuit"),
                            ("manuelle", "Publication manuelle"),
                        ],
                        max_length=10,
                        verbose_name="Origine",
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("reussie", "Réussie"),
                            ("echec", "Échec"),
                            ("ignoree", "Ignorée"),
                        ],
                        max_length=10,
                        verbose_name="Résultat",
                    ),
                ),
                (
                    "plans",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Plans publiés"
                    ),
                ),
                (
                    "documents",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Documents publiés"
                    ),
                ),
                (
                    "depublies",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Plans dépubliés"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Message"
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication vers le hub",
                "verbose_name_plural": "Publications vers le hub",
                "db_table": '"ccd_search"."t_publication_hub"',
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RaccordementHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeton_depot_chiffre",
                    models.TextField(
                        blank=True, default="", verbose_name="Jeton de dépôt (chiffré)"
                    ),
                ),
                (
                    "jeton_lecture_chiffre",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Jeton de lecture (chiffré)",
                    ),
                ),
                (
                    "adhesion_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Aucune demande"),
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Statut de l'adhésion",
                    ),
                ),
                (
                    "adhesion_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comparé de vive voix avec RNF avant acceptation : il lie le jeton de suivi de l'instance, son identifiant et les empreintes de ses jetons, et déjoue une demande faite au nom d'une autre structure.",
                        max_length=7,
                        verbose_name="Code de vérification",
                    ),
                ),
                (
                    "adhesion_instance_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Identifiant proposé",
                    ),
                ),
                (
                    "adhesion_demandee_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Demandée le"
                    ),
                ),
                (
                    "adhesion_actualisee_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actualisée le"
                    ),
                ),
                (
                    "adhesion_motif",
                    models.TextField(
                        blank=True, default="", verbose_name="Motif du refus"
                    ),
                ),
                (
                    "hub_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reçue du suivi à l'acceptation de l'adhésion.",
                        max_length=500,
                        verbose_name="URL du hub",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raccordement au hub",
                "verbose_name_plural": "Raccordement au hub",
                "db_table": '"ccd_search"."t_raccordement_hub"',
            },
        ),
    ]
