# Generated by Django 5.2.17 on 2026-10-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0008_raccordement_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="raccordementhub",
            name="retrait_en_attente",
            field=models.BooleanField(
                default=False,
                help_text="Le partage a été désactivé mais le hub n'a pas pu être joint : le retrait des plans publiés est relancé automatiquement.",
                verbose_name="Retrait du hub en attente",
            ),
        ),
        migrations.AlterField(
            model_name="publicationhub",
            name="origine",
            field=models.CharField(
                choices=[
                    ("nuit", "Publication de nuit"),
                    ("manuelle", "Publication manuelle"),
                    ("relance", "Relance automatique"),
                ],
                max_length=10,
                verbose_name="Origine",
            ),
        ),
        migrations.AlterField(
            model_name="publicationhub",
            name="resultat",
            field=models.CharField(
                choices=[
                    ("reussie", "Réussie"),
                    ("echec", "Échec"),
                    ("ignoree", "Ignorée"),
                    ("retrait", "Retrait"),
                ],
                max_length=10,
                verbose_name="Résultat",
            ),
        ),
    ]
