# Generated by Django 5.0.8 on 2026-07-27 13:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_create_schemas"),
        ("users", "0010_change_redacteur_general_label"),
    ]

    operations = [
        # Le schéma est déjà créé par core.0001_create_schemas ; on le
        # re-garantit ici pour que l'app reste installable seule (bases
        # existantes migrées manuellement, environnements de test).
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS ref_geo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="AreaType",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_code",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Code du type"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(max_length=200, verbose_name="Nom du type"),
                ),
                (
                    "type_desc",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Type de zone géographique",
                "verbose_name_plural": "Types de zones géographiques",
                "db_table": '"ref_geo"."bib_areas_types"',
            },
        ),
        migrations.CreateModel(
            name="LArea",
            fields=[
                ("id_area", models.AutoField(primary_key=True, serialize=False)),
                ("area_code", models.CharField(max_length=25, verbose_name="Code")),
                ("area_name", models.CharField(max_length=250, verbose_name="Nom")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Géométrie"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Centroïde"
                    ),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "id_type",
                    models.ForeignKey(
                        db_column="id_type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="geo.areatype",
                        verbose_name="Type de zone",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_area_parent",
                        help_text="Région de rattachement, pour un département.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="geo.larea",
                        verbose_name="Zone parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone géographique",
                "verbose_name_plural": "Zones géographiques",
                "db_table": '"ref_geo"."l_areas"',
            },
        ),
        migrations.CreateModel(
            name="CorSiteArea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("intersect", "Intersection géométrique"),
                            ("nearest", "Zone la plus proche"),
                            ("manual", "Saisie manuelle"),
                        ],
                        default="intersect",
                        help_text="« Zone la plus proche » signale un site sans intersection terrestre (site marin, ou géométrie approximative rattachée par proximité).",
                        max_length=20,
                        verbose_name="Origine du rattachement",
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        db_column="id_site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="users.site",
                        verbose_name="Site",
                    ),
                ),
                (
                    "id_area",
                    models.ForeignKey(
                        db_column="id_area",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="geo.larea",
                        verbose_name="Zone géographique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rattachement site / zone géographique",
                "verbose_name_plural": "Rattachements sites / zones géographiques",
                "db_table": '"ref_geo"."cor_site_area"',
            },
        ),
        migrations.AddIndex(
            model_name="larea",
            index=models.Index(fields=["area_code"], name="idx_l_areas_code"),
        ),
        migrations.AddConstraint(
            model_name="larea",
            constraint=models.UniqueConstraint(
                fields=("id_type", "area_code"), name="uq_l_areas_type_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="corsitearea",
            constraint=models.UniqueConstraint(
                fields=("id_site", "id_area"), name="uq_cor_site_area"
            ),
        ),
    ]
