# Generated by Django 5.0.8 on 2026-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VMTaxrefListForAutocomplete",
            fields=[
                (
                    "cd_nom",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Code nom"
                    ),
                ),
                (
                    "cd_ref",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Code référence"
                    ),
                ),
                ("search_name", models.TextField(verbose_name="Nom de recherche")),
                (
                    "nom_valide",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Nom valide"
                    ),
                ),
                (
                    "nom_vern",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nom vernaculaire"
                    ),
                ),
                (
                    "lb_nom",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Nom latin"
                    ),
                ),
                (
                    "regne",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Règne"
                    ),
                ),
                (
                    "group2_inpn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Groupe 2 INPN",
                    ),
                ),
                (
                    "id_rang",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Rang"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autocomplete taxon",
                "verbose_name_plural": "Autocomplete taxons",
                "db_table": '"taxonomie"."vm_taxref_list_forautocomplete"',
                "managed": False,
            },
        ),
    ]
